import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const moduleURL=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');
const time=moduleURL(readFileSync(new URL('../lib/time-domain.ts',import.meta.url),'utf8'));
const api=await import(moduleURL(readFileSync(new URL('../lib/expense-domain.ts',import.meta.url),'utf8').replace("'./time-domain'",JSON.stringify(time))));
const employee={companyId:'mir-demo',email:'alex',userName:'Alex',role:'Employé'},admin={companyId:'mir-demo',email:'ester',userName:'Ester',role:'Adjointe'};
function setup(){const identity={company_id:'mir-demo',employees:[{id:'emp-a',company_id:'mir-demo',user_id:'alex',role:'Employé'},{id:'emp-e',company_id:'mir-demo',user_id:'ester',role:'Adjointe'}],jobs:[{id:'job',company_id:'mir-demo',members:['alex','ester']}]};const d={company_id:'mir-demo',expenses:[],attachments:[],items:[],audit:[],notifications:[],approvals:[],categories:[{id:'cat',company_id:'mir-demo',active:true}]};const fields={...api.emptyExpenseFields(),job_id:'job',supplier_name_snapshot:'RONA',category:'cat',description:'Vis',total:84.62};return {identity,d,fields};}
function submitted(){const s=setup();api.saveExpense(s.d,s.identity,employee,'exp',s.fields);s.d.attachments.push({id:'receipt',company_id:'mir-demo',owner_id:'exp',job_id:'job'});api.saveExpense(s.d,s.identity,employee,'exp',{...s.fields,receipt_document_id:'receipt'},1);api.submitExpense(s.d,s.identity,employee,'exp');return s;}
test('one expense ID through submit, approval and reimbursement; repeat submit does not duplicate',()=>{const {d,identity}=submitted();api.submitExpense(d,identity,employee,'exp');assert.equal(d.expenses.length,1);assert.equal(d.notifications.length,1);assert.equal(d.notifications[0].source_id,'exp');const x=d.expenses[0];api.reviewExpense(d,identity,admin,'exp','approved',x.version);api.reviewExpense(d,identity,admin,'exp','reimbursed',x.version,'TEST-1');assert.equal(x.reimbursement_status,'reimbursed');assert.equal(d.approvals.length,1);assert.equal(d.items.length,0);assert.ok(d.audit.length>=4)});
test('company, employee and administrator boundaries enforced in domain',()=>{const {d,identity}=submitted();assert.throws(()=>api.visibleExpenses(d,identity,{...employee,companyId:'other'}));assert.throws(()=>api.reviewExpense(d,identity,employee,'exp','approved',3));assert.throws(()=>api.saveExpense(d,identity,admin,'exp',d.expenses[0],3));});
test('stale decisions rejected and original receipt remains immutable',()=>{const {d,identity}=submitted();const version=d.expenses[0].version;api.reviewExpense(d,identity,admin,'exp','under_review',version);assert.throws(()=>api.reviewExpense(d,identity,admin,'exp','approved',version));assert.equal(d.expenses[0].receipt_document_id,'receipt');});
test('incomplete submission, foreign attachment and unassigned job rejected',()=>{const {d,identity,fields}=setup();api.saveExpense(d,identity,employee,'exp',fields);assert.throws(()=>api.submitExpense(d,identity,employee,'exp'));assert.throws(()=>api.saveExpense(d,identity,employee,'new',{...fields,job_id:'foreign'}));assert.throws(()=>api.saveExpense(d,identity,employee,'exp',{...fields,receipt_document_id:'foreign'},1));});
