'use client';

import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Box, Check, ChevronRight, Download, Factory, FileText, Mail, PackageCheck, Plus, Printer, Search, Settings2, Trash2 } from 'lucide-react';

type Role='Boss'|'Adjointe';
type CenterOrder={id:string;companyId:string;date:string;job:string;requester:string;items:Array<{name:string;qty:number;unit:string;source:'Inventaire MIR'|'Fournisseur';supplier?:string}>;status:string;history:string[]};
const seedOrders:CenterOrder[]=[
 {id:'BC-2026-0841',companyId:'mir-demo',date:'2026-09-02',job:'JOB-214 · Breton',requester:'Fred G.',status:'Reçue',history:['Créée par Fred · 08:41'],items:[{name:'J soffite',qty:24,unit:'morceaux',source:'Inventaire MIR'},{name:'Boîte de soffite',qty:3,unit:'boîtes',source:'Fournisseur',supplier:'Acier Breton'}]},
 {id:'BC-2026-0838',companyId:'mir-demo',date:'2026-09-01',job:'JOB-315 · Leduc',requester:'Alex P.',status:'Commandée fournisseur',history:['Créée par Alex','Courriel envoyé à Acier Breton'],items:[{name:'Moulure coupe-feu',qty:18,unit:'morceaux',source:'Fournisseur',supplier:'Acier Breton'}]},
 {id:'BC-2026-0802',companyId:'mir-demo',date:'2026-08-28',job:'JOB-214 · Breton',requester:'Fred G.',status:'Complétée',history:['Créée','Réservée','Embarquée','Complétée'],items:[{name:'J soffite',qty:42,unit:'morceaux',source:'Inventaire MIR'}]},
];
const catalogSeed=[
 {id:'p1',name:'J soffite',category:'Matériaux',fields:'Couleur · Quantité',units:'boîte, morceau',source:'Les deux',active:true},
 {id:'p2',name:'Boîte de soffite',category:'Matériaux',fields:'Noir / Blanc / Autre',units:'boîte, morceau',source:'Les deux',active:true},
 {id:'p3',name:'Moulure coupe-feu',category:'Pliage',fields:'Longueur · Couleur',units:'morceau',source:'Fournisseur',active:true},
 {id:'p4',name:'Lame Olfa 1″',category:'Outils',fields:'Quantité',units:'paquet',source:'Inventaire MIR',active:true},
];
const inventorySeed=[{name:'J soffite',stock:380,reserved:24,minimum:80,unit:'morceaux'},{name:'Lame Olfa 1″',stock:52,reserved:4,minimum:16,unit:'paquets'},{name:'Boîte de soffite',stock:21,reserved:3,minimum:8,unit:'boîtes'}];
const supplierSeed=[{name:'Acier Breton',rep:'Martin Côté',email:'commandes@acierbreton.ca',phone:'418 555-0184',address:'Lévis'},{name:'Quincaillerie Pro',rep:'Julie Roy',email:'commandes@quincailleriepro.ca',phone:'418 555-0122',address:'Québec'}];
const statuses=['Reçue','À traiter','En préparation','Commandée fournisseur','En attente','Prête','Embarquée','Complétée'];

export function CommandCenter({role,companyId}:{role:Role;companyId:string}){
 const [tab,setTab]=useState('Commandes'); const [orders,setOrders]=useState<CenterOrder[]>([]); const [catalog,setCatalog]=useState(catalogSeed); const [inventory,setInventory]=useState(inventorySeed); const [query,setQuery]=useState(''); const [status,setStatus]=useState('Tous'); const [selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{const load=()=>{const raw=localStorage.getItem(`forge:${companyId}:orders`);setOrders(raw?JSON.parse(raw):seedOrders.filter(o=>o.companyId===companyId))};load();window.addEventListener('forge-orders-updated',load);return()=>window.removeEventListener('forge-orders-updated',load)},[companyId]);
 const save=(next:CenterOrder[])=>{setOrders(next);localStorage.setItem(`forge:${companyId}:orders`,JSON.stringify(next))};
 const filtered=orders.filter(o=>(status==='Tous'||o.status===status)&&`${o.id} ${o.job} ${o.requester} ${o.items.map(i=>i.name).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const metrics=[['NOUVELLES',orders.filter(o=>o.status==='Reçue').length],['À PRÉPARER',orders.filter(o=>['À traiter','En préparation'].includes(o.status)).length],['CHEZ FOURNISSEUR',orders.filter(o=>o.status==='Commandée fournisseur').length],['PRÊTES / EMBARQUÉES',orders.filter(o=>['Prête','Embarquée'].includes(o.status)).length],['COMPLÉTÉES',orders.filter(o=>o.status==='Complétée').length]];
 const totals=useMemo(()=>{const map=new Map<string,{name:string;unit:string;qty:number;orders:string[]}>();orders.forEach(o=>o.items.forEach(i=>{const key=`${i.name}|${i.unit}`;const cur=map.get(key)||{name:i.name,unit:i.unit,qty:0,orders:[]};cur.qty+=i.qty;cur.orders.push(o.id);map.set(key,cur)}));return [...map.values()]},[orders]);
 const active=orders.find(o=>o.id===selected);
 return <section className="forge-command-center" id="orders-admin"><div className="fcc-heading"><div><span>CENTRE DES OPÉRATIONS</span><h2>Commandes & matériaux</h2><p>Un seul endroit pour recevoir, préparer, commander, livrer et analyser.</p></div><button><Plus/> Nouveau bon</button></div><nav>{['Commandes','Inventaire','Catalogue','Fournisseurs','Rapports'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
 {tab==='Commandes'&&<><div className="fcc-metrics">{metrics.map(([k,v])=><article key={k}><span>{k}</span><b>{v}</b></article>)}</div><div className="fcc-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bon, job, employé ou matériau…"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option>Tous</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select><option>Toutes les dates</option><option>Cette semaine</option><option>Ce mois</option><option>2026</option></select></div><div className="fcc-order-list"><div className="fcc-order-head"><span>BON / DATE</span><span>JOB / DEMANDEUR</span><span>ITEMS</span><span>STATUT</span><span/></div>{filtered.map(o=><div className="fcc-order-row" key={o.id}><div><b>{o.id}</b><small>{o.date}</small></div><div><b>{o.job}</b><small>{o.requester}</small></div><div><b>{o.items.length} article{o.items.length>1?'s':''}</b><small>{o.items.map(i=>i.name).join(', ')}</small></div><select value={o.status} onChange={e=>save(orders.map(x=>x.id===o.id?{...x,status:e.target.value,history:[...x.history,`${e.target.value} · ${new Date().toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'})}`]}:x))}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>setSelected(o.id)}><ChevronRight/></button></div>)}</div></>}
 {tab==='Inventaire'&&<div className="fcc-cards"><div className="fcc-section-title"><div><h3>Inventaire MIR</h3><p>Le stock est réservé à la commande et retiré seulement au chargement.</p></div><button><Plus/> Ajouter un item</button></div>{inventory.map(i=><article className="inventory-line" key={i.name}><Box/><div><b>{i.name}</b><small>Minimum {i.minimum} {i.unit}</small></div><span><small>EN STOCK</small><b>{i.stock}</b></span><span><small>RÉSERVÉ</small><b>{i.reserved}</b></span><span><small>DISPONIBLE</small><b>{i.stock-i.reserved}</b></span><button onClick={()=>setInventory(items=>items.map(x=>x.name===i.name?{...x,stock:x.stock-x.reserved,reserved:0}:x))}><Check/> Embarqué</button></article>)}</div>}
 {tab==='Catalogue'&&<div className="fcc-cards"><div className="fcc-section-title"><div><h3>Catalogue 100 % modifiable</h3><p>Catégories, champs, unités, source et fournisseur par défaut.</p></div><button onClick={()=>setCatalog(c=>[...c,{id:`p${Date.now()}`,name:'Nouvel item',category:'Matériaux',fields:'Quantité',units:'morceau',source:'Les deux',active:true}])}><Plus/> Créer un produit</button></div>{catalog.map(p=><article className={`catalog-line ${p.active?'':'inactive'}`} key={p.id}><PackageCheck/><div><input value={p.name} onChange={e=>setCatalog(c=>c.map(x=>x.id===p.id?{...x,name:e.target.value}:x))}/><small>{p.category} · {p.fields} · {p.units}</small></div><select value={p.source} onChange={e=>setCatalog(c=>c.map(x=>x.id===p.id?{...x,source:e.target.value}:x))}><option>Inventaire MIR</option><option>Fournisseur</option><option>Les deux</option></select><button onClick={()=>setCatalog(c=>c.map(x=>x.id===p.id?{...x,active:!x.active}:x))}>{p.active?'Actif':'Inactif'}</button><button><Settings2/></button></article>)}</div>}
 {tab==='Fournisseurs'&&<div className="fcc-cards"><div className="fcc-section-title"><div><h3>Fournisseurs</h3><p>Coordonnées, représentant et préparation des courriels.</p></div><button><Plus/> Nouveau fournisseur</button></div>{supplierSeed.map(s=><article className="supplier-line" key={s.name}><Factory/><div><b>{s.name}</b><small>{s.rep} · {s.address}</small></div><span><b>{s.email}</b><small>{s.phone}</small></span><button><Mail/> Préparer un courriel</button></article>)}</div>}
 {tab==='Rapports'&&<div className="fcc-report"><div className="fcc-section-title"><div><h3>Consommation — 2026</h3><p>Les unités différentes restent séparées. Cliquez un total pour ouvrir les bons.</p></div><div><button><Printer/> Imprimer</button><button><Download/> CSV / Excel</button></div></div><div className="report-filters"><select><option>Tous les employés</option><option>Fred G.</option><option>Alex P.</option></select><select><option>Toutes les jobs</option><option>JOB-214 · Breton</option><option>JOB-315 · Leduc</option></select><select><option>Tous les fournisseurs</option><option>Acier Breton</option></select><select><option>2026</option><option>2025</option></select></div><div className="consumption-grid">{totals.map(t=><button key={t.name+t.unit} onClick={()=>setSelected(t.orders[0])}><span>{t.name}</span><b>{t.qty.toLocaleString('fr-CA')} <small>{t.unit}</small></b><em>{t.orders.length} bon{t.orders.length>1?'s':''} de commande</em></button>)}</div></div>}
 {active&&<div className="fcc-drawer"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><span>DÉTAIL DU BON</span><h3>{active.id}</h3><p>{active.job} · {active.requester} · {active.date}</p>{active.items.map(i=><article key={i.name}><b>{i.name}</b><span>{i.qty} {i.unit}</span><small>{i.source}{i.supplier?` · ${i.supplier}`:''}</small></article>)}<h4>Historique</h4>{active.history.map((h,i)=><div className="history-line" key={i}><i/><span>{h}</span></div>)}<button className="drawer-email"><Mail/> Préparer le courriel fournisseur</button></div>}</section>
}
