'use client';

import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Box, Check, ChevronRight, Download, Factory, FileText, Mail, PackageCheck, Plus, Printer, Search, Settings2, Trash2 } from 'lucide-react';
import { CatalogBuilder } from './catalog-builder';

type Role='Boss'|'Adjointe';
type CenterOrder={id:string;companyId:string;date:string;job:string;requester:string;items:Array<{name:string;qty:number;unit:string;source:'Inventaire MIR'|'Fournisseur';supplier?:string;detail?:string}>;status:string;history:string[]};
type Supplier={name:string;rep:string;email:string;phone:string;address:string;notes?:string;active?:boolean};
const seedOrders:CenterOrder[]=[
 {id:'BC-2026-0841',companyId:'mir-demo',date:'2026-09-02',job:'JOB-214 · Breton',requester:'Fred G.',status:'Reçue',history:['Créée par Fred · 08:41'],items:[{name:'J soffite',qty:24,unit:'morceaux',source:'Inventaire MIR'},{name:'Boîte de soffite',qty:3,unit:'boîtes',source:'Fournisseur',supplier:'Acier Breton'}]},
 {id:'BC-2026-0838',companyId:'mir-demo',date:'2026-09-01',job:'JOB-315 · Leduc',requester:'Alex P.',status:'Commandée fournisseur',history:['Créée par Alex','Courriel envoyé à Acier Breton'],items:[{name:'Moulure coupe-feu',qty:18,unit:'morceaux',source:'Fournisseur',supplier:'Acier Breton'}]},
 {id:'BC-2026-0802',companyId:'mir-demo',date:'2026-08-28',job:'JOB-214 · Breton',requester:'Fred G.',status:'Complétée',history:['Créée','Réservée','Embarquée','Complétée'],items:[{name:'J soffite',qty:42,unit:'morceaux',source:'Inventaire MIR'}]},
];
const catalogSeed=[
 {id:'p1',name:'J soffite',category:'Matériaux',fields:'Couleur · Quantité',units:'boîte, morceau',source:'Les deux',active:true},
 {id:'p2',name:'Boîte de soffite',category:'Matériaux',fields:'Noir / Blanc / Autre',units:'boîte, morceau',source:'Les deux',active:true},
 {id:'p3',name:'Moulure coupe-feu',category:'Pliage',fields:'Longueur · Couleur',units:'morceau',source:'Fournisseur',active:true},
 {id:'p4',name:'Lame Olfa 1″',category:'Outils',fields:'Quantité',units:'paquet',source:'Inventaire MIR',active:true},
];
const inventorySeed=[{name:'J soffite',stock:380,reserved:24,minimum:80,unit:'morceaux'},{name:'Lame Olfa 1″',stock:52,reserved:4,minimum:16,unit:'paquets'},{name:'Boîte de soffite',stock:21,reserved:3,minimum:8,unit:'boîtes'}];
const supplierSeed:Supplier[]=[{name:'Acier Breton',rep:'Martin Côté',email:'commandes@acierbreton.ca',phone:'418 555-0184',address:'Lévis',notes:'Livraison chantier en 2 jours',active:true},{name:'Quincaillerie Pro',rep:'Julie Roy',email:'commandes@quincailleriepro.ca',phone:'418 555-0122',address:'Québec',active:true}];
const statuses=['Reçue','À traiter','En préparation','Commandée fournisseur','En attente','Prête','Embarquée','Complétée'];

export function CommandCenter({role,companyId}:{role:Role;companyId:string}){
 const [tab,setTab]=useState('Commandes'); const [orders,setOrders]=useState<CenterOrder[]>([]); const [catalog,setCatalog]=useState(catalogSeed); const [inventory,setInventory]=useState(inventorySeed); const [suppliers,setSuppliers]=useState(supplierSeed); const [query,setQuery]=useState(''); const [status,setStatus]=useState('Tous'); const [jobFilter,setJobFilter]=useState('Toutes'); const [employeeFilter,setEmployeeFilter]=useState('Tous'); const [supplierFilter,setSupplierFilter]=useState('Tous'); const [sourceFilter,setSourceFilter]=useState('Toutes'); const [yearFilter,setYearFilter]=useState('2026'); const [selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{const load=()=>{const raw=localStorage.getItem(`forge:${companyId}:orders`);const stored=(raw?JSON.parse(raw):[]) as CenterOrder[];const demo=seedOrders.filter(o=>o.companyId===companyId&&!stored.some(s=>s.id===o.id));setOrders([...stored,...demo])};load();const rawCatalog=localStorage.getItem(`forge:${companyId}:catalog`);if(rawCatalog)setCatalog(JSON.parse(rawCatalog));const rawInventory=localStorage.getItem(`forge:${companyId}:inventory`);if(rawInventory)setInventory(JSON.parse(rawInventory));const rawSuppliers=localStorage.getItem(`forge:${companyId}:suppliers`);if(rawSuppliers)setSuppliers(JSON.parse(rawSuppliers));window.addEventListener('forge-orders-updated',load);return()=>window.removeEventListener('forge-orders-updated',load)},[companyId]);
 const save=(next:CenterOrder[])=>{setOrders(next);localStorage.setItem(`forge:${companyId}:orders`,JSON.stringify(next))};
 const saveCatalog=(next:typeof catalog)=>{setCatalog(next);localStorage.setItem(`forge:${companyId}:catalog`,JSON.stringify(next));window.dispatchEvent(new Event('forge-catalog-updated'))};
 const saveInventory=(next:typeof inventory)=>{setInventory(next);localStorage.setItem(`forge:${companyId}:inventory`,JSON.stringify(next))};
 const saveSuppliers=(next:Supplier[])=>{setSuppliers(next);localStorage.setItem(`forge:${companyId}:suppliers`,JSON.stringify(next))};
 const filtered=orders.filter(o=>(status==='Tous'||o.status===status)&&(jobFilter==='Toutes'||o.job===jobFilter)&&(employeeFilter==='Tous'||o.requester===employeeFilter)&&(supplierFilter==='Tous'||o.items.some(i=>i.supplier===supplierFilter))&&(sourceFilter==='Toutes'||o.items.some(i=>i.source===sourceFilter))&&(yearFilter==='Toutes'||o.date.startsWith(yearFilter))&&`${o.id} ${o.job} ${o.requester} ${o.items.map(i=>i.name).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const metrics=[['NOUVELLES',orders.filter(o=>o.status==='Reçue').length],['À PRÉPARER',orders.filter(o=>['À traiter','En préparation'].includes(o.status)).length],['CHEZ FOURNISSEUR',orders.filter(o=>o.status==='Commandée fournisseur').length],['PRÊTES / EMBARQUÉES',orders.filter(o=>['Prête','Embarquée'].includes(o.status)).length],['COMPLÉTÉES',orders.filter(o=>o.status==='Complétée').length]];
 const totals=useMemo(()=>{const map=new Map<string,{name:string;unit:string;qty:number;orders:string[]}>();filtered.forEach(o=>o.items.forEach(i=>{const key=`${i.name}|${i.unit}`;const cur=map.get(key)||{name:i.name,unit:i.unit,qty:0,orders:[]};cur.qty+=i.qty;cur.orders.push(o.id);map.set(key,cur)}));return [...map.values()]},[filtered]);
 const changeStatus=(order:CenterOrder,nextStatus:string)=>{if(order.status===nextStatus)return;let nextInventory=inventory;if(nextStatus==='Embarquée'&&order.status!=='Embarquée'&&order.status!=='Complétée'){nextInventory=inventory.map(stock=>{const qty=order.items.filter(i=>i.source==='Inventaire MIR'&&i.name===stock.name&&i.unit===stock.unit).reduce((n,i)=>n+i.qty,0);return qty?{...stock,stock:Math.max(0,stock.stock-qty),reserved:Math.max(0,stock.reserved-qty)}:stock});saveInventory(nextInventory)}if(order.status==='Embarquée'&& !['Embarquée','Complétée'].includes(nextStatus)){nextInventory=inventory.map(stock=>{const qty=order.items.filter(i=>i.source==='Inventaire MIR'&&i.name===stock.name&&i.unit===stock.unit).reduce((n,i)=>n+i.qty,0);return qty?{...stock,stock:stock.stock+qty,reserved:stock.reserved+qty}:stock});saveInventory(nextInventory)}save(orders.map(o=>o.id===order.id?{...o,status:nextStatus,history:[...o.history,`${nextStatus} · ${new Date().toLocaleString('fr-CA',{dateStyle:'short',timeStyle:'short'})} · ${role}`]}:o))};
 const exportCsv=()=>{const rows=[['Bon','Date','Job','Demandeur','Item','Quantité','Unité','Source','Fournisseur','Statut'],...filtered.flatMap(o=>o.items.map(i=>[o.id,o.date,o.job,o.requester,i.name,String(i.qty),i.unit,i.source,i.supplier||'',o.status]))];const blob=new Blob([rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`forge-commandes-${yearFilter}.csv`;a.click();URL.revokeObjectURL(url)};
 const active=orders.find(o=>o.id===selected);
 return <section className="forge-command-center" id="orders-admin"><div className="fcc-heading"><div><span>CENTRE DES OPÉRATIONS</span><h2>Commandes & matériaux</h2><p>Un seul endroit pour recevoir, préparer, commander, livrer et analyser.</p></div><button><Plus/> Nouveau bon</button></div><nav>{['Commandes','Inventaire','Catalogue','Fournisseurs','Rapports'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
 {tab==='Commandes'&&<><div className="fcc-metrics">{metrics.map(([k,v])=><article key={k}><span>{k}</span><b>{v}</b></article>)}</div><div className="fcc-toolbar advanced"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bon, job, employé ou matériau…"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option>Tous</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select value={jobFilter} onChange={e=>setJobFilter(e.target.value)}><option>Toutes</option>{[...new Set(orders.map(o=>o.job))].map(j=><option key={j}>{j}</option>)}</select><select value={employeeFilter} onChange={e=>setEmployeeFilter(e.target.value)}><option>Tous</option>{[...new Set(orders.map(o=>o.requester))].map(v=><option key={v}>{v}</option>)}</select><select value={supplierFilter} onChange={e=>setSupplierFilter(e.target.value)}><option>Tous</option>{suppliers.map(s=><option key={s.name}>{s.name}</option>)}</select><select value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option>Toutes</option><option>Inventaire MIR</option><option>Fournisseur</option></select><select value={yearFilter} onChange={e=>setYearFilter(e.target.value)}><option>Toutes</option><option>2026</option><option>2025</option></select></div><div className="fcc-order-list"><div className="fcc-order-head"><span>BON / DATE</span><span>JOB / DEMANDEUR</span><span>ITEMS</span><span>STATUT</span><span/></div>{filtered.map(o=><div className="fcc-order-row" key={o.id}><div><b>{o.id}</b><small>{o.date}</small></div><div><b>{o.job}</b><small>{o.requester}</small></div><div><b>{o.items.length} article{o.items.length>1?'s':''}</b><small>{o.items.map(i=>i.name).join(', ')}</small></div><select value={o.status} onChange={e=>changeStatus(o,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>setSelected(o.id)}><ChevronRight/></button></div>)}{!filtered.length&&<div className="fcc-empty">Aucun bon ne correspond à tous les filtres sélectionnés.</div>}</div></>}
 {tab==='Inventaire'&&<div className="fcc-cards"><div className="fcc-section-title"><div><h3>Inventaire MIR</h3><p>Le stock est réservé à la commande et retiré seulement au chargement.</p></div><button onClick={()=>{const name=window.prompt('Nom du nouvel item');if(name?.trim())saveInventory([...inventory,{name:name.trim(),stock:0,reserved:0,minimum:0,unit:'morceaux'}])}}><Plus/> Ajouter un item</button></div>{inventory.map(i=><article className="inventory-line" key={i.name}><Box/><div><b>{i.name}</b><small>Minimum {i.minimum} {i.unit}</small></div><span><small>EN STOCK</small><b>{i.stock}</b></span><span><small>RÉSERVÉ</small><b>{i.reserved}</b></span><span><small>DISPONIBLE</small><b>{i.stock-i.reserved}</b></span><button onClick={()=>saveInventory(inventory.map(x=>x.name===i.name?{...x,stock:Math.max(0,x.stock-x.reserved),reserved:0}:x))}><Check/> Embarqué</button></article>)}</div>}
 {tab==='Catalogue'&&<div className="fcc-cards"><CatalogBuilder companyId={companyId} suppliers={suppliers.filter(s=>s.active!==false).map(s=>s.name)} onSaved={()=>{}}/><div className="legacy-catalog"><div className="fcc-section-title"><div><h3>Articles simples existants</h3><p>Ils restent modifiables et leur historique est conservé.</p></div><button onClick={()=>saveCatalog([...catalog,{id:`p${Date.now()}`,name:'Nouvel item',category:'Matériaux',fields:'Quantité',units:'morceau',source:'Les deux',active:true}])}><Plus/> Article simple</button></div>{catalog.map(p=><article className={`catalog-line ${p.active?'':'inactive'}`} key={p.id}><PackageCheck/><div><input value={p.name} onChange={e=>saveCatalog(catalog.map(x=>x.id===p.id?{...x,name:e.target.value}:x))}/><small>{p.category} · {p.fields} · {p.units}</small></div><select value={p.source} onChange={e=>saveCatalog(catalog.map(x=>x.id===p.id?{...x,source:e.target.value}:x))}><option>Inventaire MIR</option><option>Fournisseur</option><option>Les deux</option></select><button onClick={()=>saveCatalog(catalog.map(x=>x.id===p.id?{...x,active:!x.active}:x))}>{p.active?'Actif':'Inactif'}</button><button onClick={()=>{const fields=window.prompt('Champs personnalisés (séparés par ·)',p.fields);const units=window.prompt('Unités permises (séparées par une virgule)',p.units);if(fields!==null&&units!==null)saveCatalog(catalog.map(x=>x.id===p.id?{...x,fields,units}:x))}}><Settings2/></button></article>)}</div></div>}
 {tab==='Fournisseurs'&&<div className="fcc-cards"><div className="fcc-section-title"><div><h3>Fournisseurs</h3><p>Coordonnées, représentant et préparation des courriels.</p></div><button onClick={()=>{const name=window.prompt('Nom de l’entreprise');const email=window.prompt('Courriel de commande');if(name?.trim()&&email?.trim())saveSuppliers([...suppliers,{name:name.trim(),rep:'À compléter',email:email.trim(),phone:'À compléter',address:'À compléter',active:true}])}}><Plus/> Nouveau fournisseur</button></div>{suppliers.map(s=><article className={`supplier-line ${s.active===false?'inactive':''}`} key={s.name}><Factory/><div><b>{s.name}</b><small>{s.rep} · {s.address}</small></div><span><b>{s.email}</b><small>{s.phone}{s.notes?` · ${s.notes}`:''}</small></span><button onClick={()=>{window.location.href=`mailto:${s.email}?subject=${encodeURIComponent('Bon de commande FORGE — Les Revêtements MIR')}&body=${encodeURIComponent(`Bonjour ${s.rep},\n\nVeuillez trouver la commande MIR préparée dans FORGE. Livraison demandée au chantier dans 2 jours.\n\nMerci.`)}`}}><Mail/> Préparer un courriel</button><button onClick={()=>saveSuppliers(suppliers.map(x=>x.name===s.name?{...x,active:x.active===false}:x))}>{s.active===false?'Réactiver':'Désactiver'}</button></article>)}</div>}
 {tab==='Rapports'&&<div className="fcc-report"><div className="fcc-section-title"><div><h3>Consommation — {yearFilter==='Toutes'?'toutes les années':yearFilter}</h3><p>Les unités différentes restent séparées. Cliquez un total pour ouvrir les bons.</p></div><div><button onClick={()=>window.print()}><Printer/> Imprimer</button><button onClick={exportCsv}><Download/> CSV / Excel</button></div></div><div className="report-filters"><select value={employeeFilter} onChange={e=>setEmployeeFilter(e.target.value)}><option>Tous</option>{[...new Set(orders.map(o=>o.requester))].map(v=><option key={v}>{v}</option>)}</select><select value={jobFilter} onChange={e=>setJobFilter(e.target.value)}><option>Toutes</option>{[...new Set(orders.map(o=>o.job))].map(v=><option key={v}>{v}</option>)}</select><select value={supplierFilter} onChange={e=>setSupplierFilter(e.target.value)}><option>Tous</option>{suppliers.map(s=><option key={s.name}>{s.name}</option>)}</select><select value={yearFilter} onChange={e=>setYearFilter(e.target.value)}><option>Toutes</option><option>2026</option><option>2025</option></select></div><div className="consumption-grid">{totals.map(t=><button key={t.name+t.unit} onClick={()=>setSelected(t.orders[0])}><span>{t.name}</span><b>{t.qty.toLocaleString('fr-CA')} <small>{t.unit}</small></b><em>{t.orders.length} bon{t.orders.length>1?'s':''} de commande</em></button>)}{!totals.length&&<div className="fcc-empty">Aucune consommation pour ces filtres.</div>}</div></div>}
 {active&&<div className="fcc-drawer"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><span>DÉTAIL DU BON</span><h3>{active.id}</h3><p>{active.job} · {active.requester} · {active.date}</p>{active.items.map((i,index)=><article key={`${i.name}-${index}`}><b>{i.name}</b><span>{i.qty} {i.unit}</span><small>{i.source}{i.supplier?` · ${i.supplier}`:''}</small>{i.detail&&<em className="order-item-detail">{i.detail}</em>}</article>)}<label className="drawer-status">STATUT<select value={active.status} onChange={e=>changeStatus(active,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><h4>Historique permanent</h4>{active.history.map((h,i)=><div className="history-line" key={i}><i/><span>{h}</span></div>)}<button className="drawer-email" onClick={()=>{const supplier=active.items.find(i=>i.supplier)?.supplier||suppliers[0]?.name;const record=suppliers.find(s=>s.name===supplier);if(record)window.location.href=`mailto:${record.email}?subject=${encodeURIComponent(`${active.id} · ${active.job}`)}&body=${encodeURIComponent(`Bonjour ${record.rep},\n\nCommande ${active.id} pour ${active.job}:\n${active.items.filter(i=>i.source==='Fournisseur').map(i=>`- ${i.name}: ${i.qty} ${i.unit}`).join('\n')}\n\nLivraison demandée au chantier dans 2 jours.`)}`}}><Mail/> Préparer le courriel fournisseur</button></div>}</section>
}
