'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {type Actor,type TimeData,dateKey} from '../lib/time-domain';
import {ccqSource,employeeRoles,employmentStatuses,emptyEmployeeProfile,nextEmployeeNumber,saveEmployeeProfile,type EmployeeProfile} from '../lib/employee-profile';
import {changeTimeDemo} from '../lib/time-demo';
import './employee-form.css';
const steps=['Identité','Emploi','CCQ & rémunération','Équipe & assignations','Accès Forge','Documents','Résumé'];
export function EmployeeForm({data,actor,employee,onClose}:{data:TimeData;actor:Actor;employee?:TimeData['employees'][number];onClose:()=>void}){
 const [id]=useState(()=>employee?.id||crypto.randomUUID()),[version]=useState(employee?.profile_version||0);
 const [p,setP]=useState<EmployeeProfile>(()=>employee?.profile?structuredClone(employee.profile):{...emptyEmployeeProfile(),firstName:employee?.name.split(' ')[0]||'',lastName:employee?.name.split(' ').slice(1).join(' ')||'',trade:employee?.trade||''});
 const [role,setRole]=useState<Actor['role']>(employee?.role||'Employé'),[phone,setPhone]=useState(employee?.phone||''),[step,setStep]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [rate,setRate]=useState(''),[bonus,setBonus]=useState('0'),[bonusType,setBonusType]=useState('Aucun'),[cost,setCost]=useState(''),[effective,setEffective]=useState(()=>dateKey(new Date(),data.settings.timezone)),[docType,setDocType]=useState('Carte CCQ');
 const set=(key:keyof EmployeeProfile,value:unknown)=>setP(x=>({...x,[key]:value}));
 const field=(key:keyof EmployeeProfile,label:string,type='text',required=false)=><label>{label}<input type={type} required={required} value={String(p[key])} onChange={e=>set(key,e.target.value)}/></label>;
 const select=(key:keyof EmployeeProfile,label:string,options:{id:string;name:string}[])=><label>{label}<select value={String(p[key])} onChange={e=>set(key,e.target.value)}><option value="">Non assigné</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>;
 const file=async(f:File,photo=false)=>{setError('');if(f.size>750000){setError('Maximum 750 Ko par fichier dans cette démo.');return}if(photo&&!['image/png','image/jpeg','image/webp'].includes(f.type)){setError('Utilisez une photo JPG, PNG ou WebP.');return}try{const content=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(f)});if(photo)set('photo',content);else setP(x=>({...x,documents:[...x.documents,{id:crypto.randomUUID(),name:f.name,type:docType,expires:'',data:content}]}))}catch{setError('Impossible de lire ce fichier.')}};
 const addRate=()=>{setError('');if(!effective||rate===''||!Number.isFinite(Number(rate))||Number(rate)<0||Number(bonus)<0||(cost!==''&&Number(cost)<0)){setError('Vérifiez la date et les montants.');return}if(p.compensations.some(c=>c.effectiveFrom===effective)){setError('Une rémunération existe déjà pour cette date.');return}set('compensations',[...p.compensations,{id:crypto.randomUUID(),effectiveFrom:effective,actualRate:Number(rate),bonusType,bonusValue:Number(bonus),employerCost:cost===''?null:Number(cost),createdAt:new Date().toISOString()}]);setRate('')};
 const save=async()=>{setBusy(true);setError('');try{await changeTimeDemo(actor,d=>{saveEmployeeProfile(d,actor,{id,version,role,phone,profile:p})});onClose()}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible.')}finally{setBusy(false)}};
 const latest=[...p.compensations].sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))[0];
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="ef-dialog" showCloseButton={false}><header className="ef-heading"><div><DialogTitle>{employee?'Fiche employé':'Nouvel employé'}</DialogTitle><DialogDescription>{employee?.employee_number||nextEmployeeNumber(data)} · Données fictives — démo locale</DialogDescription></div><button type="button" onClick={onClose} disabled={busy} aria-label="Fermer">×</button></header><nav className="ef-steps" aria-label="Étapes de la fiche">{steps.map((s,i)=><button key={s} type="button" aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}><span>{i+1}</span>{s}</button>)}</nav><div className="ef-body"><form id="employee-profile-form" onSubmit={e=>{e.preventDefault();if(step<6)setStep(step+1);else void save()}}><h2>{steps[step]}</h2>{error&&<p role="alert" className="ef-error">{error}</p>}
 {step===0&&<><div className="ef-fields">{field('firstName','Prénom','text',true)}{field('lastName','Nom','text',true)}<label>Téléphone<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label>{field('email','Courriel','email')}{field('birthDate','Date de naissance','date')}{field('address','Adresse')}{field('city','Ville')}{field('province','Province')}{field('postalCode','Code postal')}<label>Photo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{if(e.target.files?.[0])void file(e.target.files[0],true)}}/></label></div><h3>Contacts d’urgence</h3>{p.contacts.map((c,i)=><fieldset key={c.id}><legend>Contact {i+1}</legend><div className="ef-fields">{(['name','relationship','phone','secondaryPhone','email','notes'] as const).map((key,j)=><label key={key}>{['Nom complet','Lien avec l’employé','Téléphone principal','Téléphone secondaire','Courriel','Notes'][j]}<input required={key==='name'||key==='phone'} value={c[key]} onChange={e=>set('contacts',p.contacts.map(x=>x.id===c.id?{...x,[key]:e.target.value}:x))}/></label>)}</div><label className="ef-check"><input type="radio" name="primary-contact" checked={c.primary} onChange={()=>set('contacts',p.contacts.map(x=>({...x,primary:x.id===c.id})))}/>Contact principal</label><button type="button" onClick={()=>set('contacts',p.contacts.filter(x=>x.id!==c.id))}>Retirer ce contact</button></fieldset>)}<button type="button" onClick={()=>set('contacts',[...p.contacts,{id:crypto.randomUUID(),name:'',relationship:'',phone:'',secondaryPhone:'',email:'',notes:'',primary:!p.contacts.length}])}>+ Ajouter un contact</button></>}
 {step===1&&<div className="ef-fields"><label>Rôle Forge<select value={role} onChange={e=>setRole(e.target.value as Actor['role'])}>{employeeRoles.filter(r=>actor.role==='Boss'||r!=='Boss'||employee?.role==='Boss').map(r=><option key={r}>{r}</option>)}</select></label><label>Statut d’emploi<select value={p.employmentStatus} onChange={e=>set('employmentStatus',e.target.value)}>{employmentStatuses.map(s=><option key={s}>{s}</option>)}</select></label>{field('hiredAt','Date d’embauche','date')}{field('endedAt','Date de fin','date')}{field('trade','Métier')}{field('notes','Notes internes')}</div>}
 {step===2&&<><div className="ef-fields">{field('trade','Métier')}{field('grade','Niveau / grade')}{field('sector','Secteur CCQ')}{field('union','Syndicat')}</div><div className="ef-reference"><b>Référence conventionnelle officielle</b><p>Les taux CCQ ne sont pas encore importés dans ce formulaire. Aucun montant fictif n’est présenté comme un taux officiel.</p><a href={ccqSource} target="_blank" rel="noreferrer">Consulter les grilles CCQ ↗</a></div><h3>Historique de rémunération</h3>{p.compensations.map(c=><div className="ef-rate" key={c.id}><b>{c.effectiveFrom}</b><span>{c.actualRate?.toFixed(2)} $ / h</span><small>Bonus : {c.bonusType} {c.bonusValue} · Coût employeur : {c.employerCost===null?'à compléter':c.employerCost.toFixed(2)+' $ / h'}</small></div>)}<fieldset><legend>Ajouter un taux daté — démo</legend><div className="ef-fields"><label>Date d’effet<input type="date" value={effective} onChange={e=>setEffective(e.target.value)}/></label><label>Taux réel employé ($ / h)<input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Bonus<select value={bonusType} onChange={e=>setBonusType(e.target.value)}>{['Aucun','Horaire','Fixe','Pourcentage','Prime','Autre'].map(v=><option key={v}>{v}</option>)}</select></label><label>Valeur du bonus<input type="number" min="0" step="0.01" value={bonus} onChange={e=>setBonus(e.target.value)}/></label><label>Coût employeur manuel ($ / h)<input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(e.target.value)}/></label></div><button type="button" onClick={addRate}>Ajouter à l’historique</button><p>Les taux précédents sont conservés. Le calcul automatique des cotisations n’est pas encore disponible.</p></fieldset></>}
 {step===3&&<div className="ef-fields">{select('teamId','Équipe',(data.teams||[]).map(t=>({id:t.id,name:t.name})))}{select('supervisorId','Chef',data.employees.filter(e=>e.role==='Chef').map(e=>({id:e.id,name:e.name})))}{select('jobId','Job initiale',data.jobs.map(j=>({id:j.id,name:j.number+' — '+j.name})))}{field('skills','Tags / compétences')}</div>}
 {step===4&&<><label className="ef-check"><input type="checkbox" checked={p.accessRequested} onChange={e=>set('accessRequested',e.target.checked)}/>Simuler une invitation Forge</label>{p.accessRequested&&field('email','Courriel de l’invitation','email',true)}<p>Aucun courriel envoyé et aucun compte réel créé. La fiche peut exister sans accès Forge.</p><label>Preset Accueil<select value={p.homePreset} onChange={e=>set('homePreset',e.target.value)}><option>Conserver le preset actuel</option><option>Employé — terrain</option><option>Chef — chantier</option></select></label></>}
 {step===5&&<><label>Type de document<select value={docType} onChange={e=>setDocType(e.target.value)}>{['Carte CCQ','Permis','Certification','Carte de compétence','Autre'].map(t=><option key={t}>{t}</option>)}</select></label><label>Ajouter un fichier fictif<input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>{if(e.target.files?.[0])void file(e.target.files[0])}}/></label><p>Fichiers locaux uniquement · 750 Ko maximum chacun.</p>{p.documents.map(doc=><div className="ef-document" key={doc.id}><a href={doc.data} download={doc.name}>{doc.name}</a><small>{doc.type}</small><label>Expiration<input type="date" value={doc.expires} onChange={e=>set('documents',p.documents.map(d=>d.id===doc.id?{...d,expires:e.target.value}:d))}/></label><button type="button" onClick={()=>set('documents',p.documents.filter(d=>d.id!==doc.id))}>Retirer</button></div>)}</>}
 {step===6&&<dl className="ef-summary">{[['Nom',p.firstName+' '+p.lastName],['Rôle',role],['Statut',p.employmentStatus],['Téléphone',phone],['Courriel',p.email],['Adresse',[p.address,p.city,p.province,p.postalCode].filter(Boolean).join(', ')],['Embauche',p.hiredAt],['Métier',p.trade],['Grade',p.grade],['Secteur',p.sector],['Syndicat',p.union],['Équipe',data.teams?.find(t=>t.id===p.teamId)?.name],['Chef',data.employees.find(e=>e.id===p.supervisorId)?.name],['Job',data.jobs.find(j=>j.id===p.jobId)?.number],['Contacts d’urgence',String(p.contacts.length)],['Documents',String(p.documents.length)],['Accès Forge',p.accessRequested?'Invitation simulée':'Sans compte'],['Rémunérations datées',String(p.compensations.length)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Non renseigné'}</dd></div>)}</dl>}
 </form><aside className="ef-preview">{p.photo?<img src={p.photo} alt="Photo de l’employé"/>:<div className="ef-initials">{p.firstName[0]||'?'}{p.lastName[0]||''}</div>}<h2>{p.firstName||'Prénom'} {p.lastName||'Nom'}</h2><p>{employee?.employee_number||nextEmployeeNumber(data)}</p><span className="ef-pill">{p.employmentStatus}</span><dl><dt>Rôle</dt><dd>{role}</dd><dt>Métier</dt><dd>{p.trade||'À préciser'}</dd><dt>Dernier taux enregistré</dt><dd>{latest?latest.actualRate?.toFixed(2)+' $ / h':'Non renseigné'}</dd><dt>Équipe</dt><dd>{data.teams?.find(t=>t.id===p.teamId)?.name||'Non assignée'}</dd></dl><small>Une seule fiche partagée dans la démo.</small></aside></div><footer className="ef-footer"><button type="button" disabled={busy} onClick={()=>step?setStep(step-1):onClose()}>{step?'Précédent':'Annuler'}</button><span>{step+1} / 7</span><button className="ef-primary" type="submit" form="employee-profile-form" disabled={busy}>{busy?'Enregistrement…':step===6?'Enregistrer la fiche':'Suivant →'}</button></footer></DialogContent></Dialog>;
}
