'use client';
import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, ArrowLeft, Bell, CalendarDays, Check, ChevronRight, Clock3, CloudRain, FileBadge, FileText, Folder, HeartPulse, History, MapPin, MessageSquare, PackageCheck, Paperclip, Plus, ReceiptText, Search, Settings, ShieldAlert, Stethoscope, Sun, UserRound, Wind } from 'lucide-react';
import type { ForgeSession } from './forge-access';
import { MyHours } from './my-hours';
import { TimeNotifications } from './time-admin';
import { PersonalSettings } from './forge-suite';
import { ProjectsOverview, JobHero, type FieldJob } from './project-overview';
import { JobShortcuts } from './job-shortcuts';

export type FieldView='home'|'projects'|'project'|'project-sections'|'project-info'|'project-plans'|'project-photos'|'project-architect'|'project-special'|'menu'|'profile'|'hours'|'absences'|'emergency'|'documents'|'incidents'|'documentation'|'settings';
type Navigate=(view:FieldView|'punch'|'orders'|'messages'|'purchases')=>void;
export type FieldPunchState={punched:boolean;selectedJob:string;activeJob:string;startedAt:number|null;onToggle:()=>void;onChangeJob:(jobId:string)=>void};
type Absence={absence_request_id:string;company_id:string;employee_id:string;type:string;start_date:string;end_date:string;full_day:boolean;note:string;status:'pending'|'reported'|'approved'|'rejected'|'cancelled';created_at:string};
type Incident={incident_id:string;company_id:string;job_id:string;reported_by_user_id:string;type:string;severity:string;incident_at:string;location:string;description:string;status:string};
const employeeId=(session:ForgeSession)=>`employee:${session.companyId}:${session.email}`;
const key=(companyId:string,type:string)=>`forge:${companyId}:${type}`;
const read=<T,>(storageKey:string,fallback:T):T=>{if(typeof window==='undefined')return fallback;try{return JSON.parse(localStorage.getItem(storageKey)||'null')||fallback}catch{return fallback}};

export function FieldWorkspace({view,session,role,navigate,punch,logoSrc,jobs=[],onNewOrder}:{view:FieldView;session:ForgeSession;role:'Chef'|'Employé';navigate:Navigate;punch:FieldPunchState;logoSrc:string;jobs?:FieldJob[];onNewOrder:(job:FieldJob)=>void}){
 const [openedJob,setOpenedJob]=useState<string|null>(null);
 const allowedJobs=jobs.filter(j=>j.company_id===session.companyId&&j.members.includes(session.email));
 const dossierJob=allowedJobs.find(j=>j.id===openedJob)||allowedJobs.find(j=>j.number===punch.selectedJob)||allowedJobs[0];
 const [absences,setAbslify]=useState<Absence[]>(()=>read(key(session.companyId,'absence-requests'),[{absence_request_id:'ABS-2026-014',company_id:session.companyId,employee_id:employeeId(session),type:'Vacances',start_date:'2026-09-21',end_date:'2026-09-25',full_day:true,note:'',status:'approved',created_at:'2026-08-28T14:00:00Z'}]));
 const [incidents,setIncidents]=useState<Incident[]>(()=>read(key(session.companyId,'incidents'),[]));
 const [dialog,setDialog]=useState<'leave'|'sick'|'incident'|null>(null);
 const profilePhotoKey=key(session.companyId,`profile-photo:${session.email}`);
 const [profilePhoto,setProfilePhoto]=useState(()=>typeof window==='undefined'?'':localStorage.getItem(profilePhotoKey)||'');
 useEffect(()=>{const sync=()=>setProfilePhoto(localStorage.getItem(profilePhotoKey)||'');window.addEventListener('forge-profile-updated',sync);return()=>window.removeEventListener('forge-profile-updated',sync)},[profilePhotoKey]);
 const saveAbsences=(next:Absence[])=>{setAbslify(next);localStorage.setItem(key(session.companyId,'absence-requests'),JSON.stringify(next));window.dispatchEvent(new Event('forge-absences-updated'))};
 const saveIncidents=(next:Incident[])=>{setIncidents(next);localStorage.setItem(key(session.companyId,'incidents'),JSON.stringify(next));window.dispatchEvent(new Event('forge-incidents-updated'))};
 const submitAbsence=(e:React.FormEvent<HTMLFormElement>,sick=false)=>{e.preventDefault();const f=new FormData(e.currentTarget);const item:Absence={absence_request_id:`ABS-${Date.now()}`,company_id:session.companyId,employee_id:employeeId(session),type:sick?'Maladie':String(f.get('type')||'Vacances'),start_date:String(f.get('start')),end_date:String(f.get('end')||f.get('start')),full_day:true,note:String(f.get('note')||''),status:sick?'reported':'pending',created_at:new Date().toISOString()};saveAbsences([item,...absences]);writeEvent(session,'absence_request',item.absence_request_id,sick?'absence_reported':'absence_submitted');setDialog(null)};
 const submitIncident=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const item:Incident={incident_id:`INC-${Date.now()}`,company_id:session.companyId,job_id:String(f.get('job')),reported_by_user_id:session.email,type:String(f.get('type')),severity:String(f.get('severity')),incident_at:String(f.get('date')),location:String(f.get('location')),description:String(f.get('description')),status:'submitted'};saveIncidents([item,...incidents]);writeEvent(session,'incident',item.incident_id,'incident_submitted');setDialog(null)};
 if(view==='settings')return <div className="field-workspace"><Back navigate={navigate}/><PersonalSettings session={session}/></div>;
 return <section className={`field-workspace field-view-${view}`}>
  <header className="field-mobile-head"><img className="field-company-logo" src={logoSrc} alt={session.companyName}/><div><button aria-label="Notifications"><Bell/><i>3</i></button><button className="field-account-avatar" onClick={()=>navigate('settings')} aria-label="Ouvrir les paramètres du compte">{profilePhoto?<img src={profilePhoto} alt="Photo de profil"/>:<span>{session.userName.slice(0,2).toUpperCase()}</span>}</button></div></header>
  {view==='home'&&<HomeView session={session} role={role} navigate={navigate} request={setDialog} punch={punch}/>}
  {view==='projects'&&<ProjectsOverview jobs={allowedJobs} activeJob={punch.activeJob} onOpen={job=>{setOpenedJob(job.id);navigate('project')}}/>}
  {view==='project'&&dossierJob&&<><JobHero job={dossierJob} onBack={()=>navigate('projects')}/><JobShortcuts key={dossierJob.id+session.email} storageKey={key(session.companyId,`job-shortcuts:${session.email}:${dossierJob.id}`)} onNavigate={dest=>dest==='orders'?onNewOrder(dossierJob):navigate(dossierJob.number==='JOB-214'?dest:'project-sections')}/><button className="job-all-sections" onClick={()=>navigate('project-sections')}>Informations et autres sections <ChevronRight/></button></>}
  {view==='project-sections'&&dossierJob&&<><button className="field-back" onClick={()=>navigate('project')}><ArrowLeft/> Retour au résumé de {dossierJob.number}</button>{dossierJob.number==='JOB-214'?<ProjectView navigate={dest=>dest==='orders'?onNewOrder(dossierJob):navigate(dest)} incidents={incidents}/>:<p className="job-empty-note">Aucun document de démonstration n’est disponible pour ce dossier.</p>}</>}
  {view==='project-info'&&<JobInfoView navigate={navigate}/>}
  {view==='project-plans'&&<JobPlansView navigate={navigate}/>}
  {view==='project-photos'&&<JobPhotosView navigate={navigate}/>}
  {view==='project-architect'&&<JobArchitectView navigate={navigate}/>}
  {view==='project-special'&&<JobSpecialView navigate={navigate}/>}
  {view==='menu'&&<MenuView role={role} navigate={navigate}/>}
  {view==='profile'&&<ProfileView session={session} navigate={navigate}/>}
  {view==='hours'&&<MyHours actor={session}/>}
  {view==='absences'&&<AbsencesView absences={absences} navigate={navigate} request={setDialog} cancel={id=>saveAbsences(absences.map(a=>a.absence_request_id===id?{...a,status:'cancelled'}:a))}/>}
  {view==='emergency'&&<EmergencyView session={session} navigate={navigate}/>}
  {view==='documents'&&<DocumentsView navigate={navigate}/>}
  {view==='incidents'&&<IncidentsView incidents={incidents} navigate={navigate} request={()=>setDialog('incident')}/>}
  {view==='documentation'&&<DocumentationView navigate={navigate}/>}
  {dialog&&<div className="field-dialog"><form onSubmit={e=>dialog==='incident'?submitIncident(e):submitAbsence(e,dialog==='sick')}><button type="button" className="dialog-close" onClick={()=>setDialog(null)}>×</button><span>{dialog==='incident'?'SÉCURITÉ':dialog==='sick'?'ABSENCE IMMÉDIATE':'ABSENCE & CONGÉS'}</span><h2>{dialog==='incident'?'Déclarer un incident':dialog==='sick'?'Signaler une maladie':'Demander un congé'}</h2>{dialog==='incident'?<><label>Job<select name="job"><option>JOB-214</option><option>JOB-315</option></select></label><label>Type<select name="type"><option>Accident avec blessure</option><option>Quasi-accident</option><option>Dommage matériel</option><option>Incident sécurité</option></select></label><label>Gravité<select name="severity"><option>Mineure</option><option>Modérée</option><option>Importante</option></select></label><label>Date et heure<input name="date" type="datetime-local" required/></label><label>Lieu<input name="location" required/></label><label>Description<textarea name="description" required/></label><label className="file-action"><Paperclip/> Ajouter des photos<input type="file" accept="image/*" multiple/></label></>:<>{dialog!=='sick'&&<label>Type<select name="type"><option>Vacances</option><option>Congé personnel</option><option>Rendez-vous</option><option>Congé parental</option></select></label>}<label>Date de début<input name="start" type="date" required/></label>{dialog==='leave'&&<label>Date de fin<input name="end" type="date" required/></label>}<label>Note facultative<textarea name="note"/></label></>}<button className="field-primary"><Check/> {dialog==='incident'?'Soumettre le rapport':dialog==='sick'?'Signaler mon absence':'Envoyer la demande'}</button></form></div>}
 </section>
}

function Back({navigate}:{navigate:Navigate}){return <button className="field-back" onClick={()=>navigate('menu')}><ArrowLeft/> Retour</button>}
function HomeView({session,role,navigate,request,punch}:{session:ForgeSession;role:'Chef'|'Employé';navigate:Navigate;request:(v:'leave'|'sick'|'incident')=>void;punch:FieldPunchState}){
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{if(!punch.punched)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[punch.punched]);
 const jobId=punch.punched?punch.activeJob:punch.selectedJob;
 const job=jobDirectory[jobId]||{name:'Job assignée',address:'Adresse à confirmer'};
 const elapsed=punch.startedAt?Math.max(0,now-punch.startedAt):0;
 const elapsedLabel=`${String(Math.floor(elapsed/3600000)).padStart(2,'0')}:${String(Math.floor(elapsed/60000)%60).padStart(2,'0')}:${String(Math.floor(elapsed/1000)%60).padStart(2,'0')}`;
 const weather=read<{location_label:string;temperature:number;condition:string;rain_probability:number;wind_speed:number}|null>(key(session.companyId,`weather:${jobId}`),null);
 const workedSeconds=Math.floor(elapsed/1000);
 const workedMinutes=Math.floor(workedSeconds/60);
 const workedLabel=`${Math.floor(workedMinutes/60)} h ${String(workedMinutes%60).padStart(2,'0')} min ${String(workedSeconds%60).padStart(2,'0')} s`;
 return <><div className="field-greeting"><span>{new Intl.DateTimeFormat('fr-CA',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span><div className="home-weather"><Sun/><b>{weather?`${weather.location_label} · ${weather.temperature} °C · ${weather.condition}`:'Météo indisponible'}</b>{weather&&<small><CloudRain/> Pluie {weather.rain_probability} % <Wind/> Vent {weather.wind_speed} km/h</small>}</div><h1>Bonne journée, {session.userName}.</h1><p>Sécuritaire aujourd’hui. On bâtit demain.</p></div><article className={`current-job ${punch.punched?'is-punched':''}`}><button className="job-open" onClick={()=>navigate('project')} aria-label={`Ouvrir le dossier ${jobId}`}><span>{punch.punched?'JOB ACTIVE':'MA JOB ACTUELLE'} · {punch.punched?'EN COURS':'SUGGÉRÉE'}</span><h2>{jobId}</h2><b>{job.name}</b><small><MapPin/> {job.address}</small>{punch.punched&&<em>Depuis {new Date(punch.startedAt||Date.now()).toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'})} · {elapsedLabel}</em>}</button><div className="home-punch-actions"><button onClick={punch.onToggle}><Clock3/> {punch.punched?'PUNCH OUT':'PUNCH IN'}</button></div></article><section className="today-summary"><div><span>AUJOURD’HUI</span><b>{workedLabel}</b></div><small>{punch.punched?<b>{jobId} · {workedLabel}</b>:<b>Aucun segment aujourd’hui</b>}</small></section>{role==='Chef'&&<section className="chef-home-strip"><article><span>ÉQUIPE AUJOURD’HUI</span><b>Voir les présences</b></article><article><span>COMPTE RENDU</span><b>À compléter au Punch Out</b></article><article><span>PROGRESSION</span><b>Consulter la Job</b></article></section>}<section className="field-section"><div className="field-section-title"><h2>Raccourcis rapides</h2><small>Maintenir pour modifier</small></div><HomeShortcutGrid session={session} navigate={navigate} request={request}/></section><section className="field-section"><div className="field-section-title"><h2>Notifications</h2><button>Voir toutes <ChevronRight/></button></div><TimeNotifications actor={session} onOpen={()=>navigate('hours')}/><div className="home-notifications"><button onClick={()=>navigate('messages')}><MessageSquare/><span><b>Nouveau message dans {jobId}</b><small>Patrick · On commence à 7 h demain.</small></span><i/></button><button onClick={()=>navigate('documents')}><AlertTriangle/><span><b>Document expirant bientôt</b><small>Votre carte CCQ expire dans 30 jours.</small></span><i/></button><button onClick={()=>navigate('projects')}><CalendarDays/><span><b>Nouvelle Job assignée</b><small>JOB-301 · Centre commercial</small></span></button></div></section></>
}
const jobDirectory:Record<string,{name:string;address:string}>={'JOB-214':{name:'Résidence Breton',address:'1280, rue Industrielle, Québec'},'JOB-315':{name:'Leduc',address:'480, boulevard Leduc, Québec'},'JOB-418':{name:'Bélanger',address:'72, rue Bélanger, Lévis'},'JOB-301':{name:'Centre commercial',address:'Lévis'}};
const shortcutRegistry={hours:{label:'Mes heures',Icon:Clock3,dest:'hours'},orders:{label:'Mes commandes',Icon:PackageCheck,dest:'orders'},purchases:{label:'Mes achats / reçus',Icon:ReceiptText,dest:'purchases'},absences:{label:'Mes absences',Icon:CalendarDays,dest:'absences'},documentation:{label:'Documentation',Icon:Folder,dest:'documentation'},incident:{label:'Signaler un incident',Icon:AlertTriangle,dest:'incidents'},sick:{label:'Signaler une maladie',Icon:Stethoscope,dest:'sick'},leave:{label:'Demander un congé',Icon:CalendarDays,dest:'leave'},job:{label:'Dossier de Job',Icon:Folder,dest:'project'},chat:{label:'Discussion Job',Icon:MessageSquare,dest:'messages'}} as const;
type ShortcutKey=keyof typeof shortcutRegistry;
function HomeShortcutGrid({session,navigate,request}:{session:ForgeSession;navigate:Navigate;request:(v:'leave'|'sick'|'incident')=>void}){const storage=key(session.companyId,`home-layout:${session.email}`);const defaults:ShortcutKey[]=['hours','orders','purchases','absences','documentation','incident','sick','leave'];const [items,setItems]=useState<ShortcutKey[]>(()=>read(storage,defaults));const [editing,setEditing]=useState(false);const [dragged,setDragged]=useState<ShortcutKey|null>(null);const timer=useRef<number|null>(null);const save=(next:ShortcutKey[])=>{const unique=[...new Set(next)].slice(0,8);setItems(unique);localStorage.setItem(storage,JSON.stringify(unique));window.dispatchEvent(new Event('forge-home-layout-updated'))};const activate=(k:ShortcutKey)=>{const dest=shortcutRegistry[k].dest;if(dest==='leave'||dest==='sick')request(dest);else navigate(dest)};const available=(Object.keys(shortcutRegistry) as ShortcutKey[]).filter(k=>!items.includes(k));return <><div className={`shortcut-grid ${editing?'editing':''}`}>{items.map(k=>{const {label,Icon}=shortcutRegistry[k];return <button key={k} draggable onDragStart={()=>setDragged(k)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(!dragged||dragged===k)return;const next=[...items];const from=next.indexOf(dragged),to=next.indexOf(k);next.splice(from,1);next.splice(to,0,dragged);save(next);setDragged(null)}} onPointerDown={()=>{timer.current=window.setTimeout(()=>setEditing(true),650)}} onPointerUp={()=>{if(timer.current)window.clearTimeout(timer.current)}} onPointerCancel={()=>{if(timer.current)window.clearTimeout(timer.current)}} onClick={()=>editing?undefined:activate(k)}><Icon/><span>{label}</span>{editing&&<i onClick={e=>{e.stopPropagation();save(items.filter(x=>x!==k))}}>×</i>}</button>})}{editing&&items.length<8&&<button className="add-shortcut" onClick={()=>available[0]&&save([...items,available[0]])}><Plus/><span>Ajouter</span></button>}</div>{editing&&<div className="shortcut-editbar"><span>Glissez pour déplacer. × pour retirer.</span><button onClick={()=>setEditing(false)}>Terminer</button><button onClick={()=>save(defaults)}>Réinitialiser</button></div>}</>}
function ProjectView({navigate,incidents}:{navigate:Navigate;incidents:Incident[]}){const links=[['Informations du chantier',FileText,'project-info','Entrepreneur, contacts, dates et consignes'],['Plans & documents',Folder,'project-plans','3 fichiers disponibles'],['Rapport d’architecte',FileBadge,'project-architect','Rapport AR-214-03 · 4 observations'],['Photos du chantier',FileBadge,'project-photos','8 photos · mise à jour aujourd’hui'],['Demandes spéciales',AlertTriangle,'project-special','3 consignes actives'],['Commandes',PackageCheck,'orders','2 commandes en cours'],['Achats & reçus',ReceiptText,'purchases','4 reçus liés à la Job'],['Discussion',MessageSquare,'messages','2 nouveaux messages'],['Incidents',ShieldAlert,'incidents',`${incidents.length} rapport(s)`],['Historique',History,'project-info','18 activités enregistrées']] as const;return <><button className="field-back" onClick={()=>navigate('projects')}><ArrowLeft/> Retour aux projets</button><div className="field-page-title"><span>JOB-214 · DOSSIER DE CHANTIER</span><h1>Résidence Breton</h1><p>1280, rue Industrielle, Québec</p></div><div className="project-summary"><b>Chantier en cours · 68 %</b><span>Entrepreneur : Construction Breton inc.</span><span>Fred G. · Chef d’équipe · 4 employés assignés</span><small>Début : 18 août 2026 · Livraison prévue : 30 octobre 2026</small></div><section className="job-attention"><b>À vérifier aujourd’hui</b><span>Rapport d’architecte : solin de fenêtre à confirmer avant installation.</span></section><div className="menu-list job-menu">{links.map(([label,Icon,dest,meta])=><button key={label} onClick={()=>navigate(dest)}><Icon/><span><b>{label}</b><small>{meta}</small></span><ChevronRight/></button>)}</div></>}

const jobPhotos=[
 {src:'https://s3.amazonaws.com/buildercloud/eeed87f8367b16b579fa5123d9c12e20.png',title:'Façade avant',meta:'Aujourd’hui · Fred G. · Progression'},
 {src:'https://na.rdcpix.com/3b1d619b4cce7761b9f5d6a2d3df2731w-c2567989673rd-w832_h468_r4_q80.jpg',title:'Élévation arrière',meta:'8 sept. · Marc T. · Progression'},
 {src:'https://media.angi.com/s3fs-public/workers-working-framing-house-398986233.jpeg?impolicy=leadImage',title:'Zone de travail',meta:'7 sept. · Alex P. · Avant travaux'}
];
function JobBack({navigate,title}:{navigate:Navigate;title:string}){return <><button className="field-back" onClick={()=>navigate('project')}><ArrowLeft/> Retour au dossier JOB-214</button><div className="field-page-title"><span>JOB-214</span><h1>{title}</h1><p>Résidence Breton</p></div></>}
function JobInfoView({navigate}:{navigate:Navigate}){return <><JobBack navigate={navigate} title="Informations du chantier"/><div className="job-info-grid"><article><span>ENTREPRENEUR GÉNÉRAL</span><b>Construction Breton inc.</b><p>Jean Breton · 418 555-0184</p><p>jean@constructionbreton.ca</p></article><article><span>NUMÉRO DE JOB</span><b>JOB-214</b><p>Bon client : CB-2026-118</p><p>Permis : QC-24-01892</p></article><article><span>DATES</span><b>18 août → 30 octobre 2026</b><p>Inspection prévue : 18 septembre</p><p>Livraison phase 2 : 22 septembre</p></article><article><span>ÉQUIPE</span><b>Fred G. · Chef</b><p>Alex P., Marco T., David L.</p><p>Quart prévu : 7 h à 15 h 30</p></article></div><section className="job-note"><b>Portée des travaux</b><p>Revêtement extérieur, soffite, fascia, moulures architecturales et finition des ouvertures.</p></section></>}
function JobPlansView({navigate}:{navigate:Navigate}){const docs=[['Plan architecture — révision C','PDF · 24 pages · 8 sept. 2026','PLAN-ARCH-214-C'],['Détails revêtement et solins','PDF · 12 pages · 5 sept. 2026','DETAIL-REV-214-B'],['Plan d’implantation','PDF · 3 pages · 18 août 2026','IMPL-214-A']];return <><JobBack navigate={navigate} title="Plans & documents"/><div className="document-list job-docs">{docs.map((d,i)=><article key={d[2]}><FileText/><span><b>{d[0]}</b><small>{d[1]}</small><em>{d[2]}</em></span><strong>{i===0?'Courant':'Référence'}</strong><ChevronRight/></article>)}</div><button className="outline-action"><Plus/> Joindre un document de test</button></>}
function JobPhotosView({navigate}:{navigate:Navigate}){return <><JobBack navigate={navigate} title="Photos du chantier"/><div className="job-photo-grid">{jobPhotos.map(p=><article key={p.title}><img src={p.src} alt={p.title}/><span><b>{p.title}</b><small>{p.meta}</small></span></article>)}</div><button className="field-primary"><Plus/> Ajouter une photo</button></>}
function JobArchitectView({navigate}:{navigate:Navigate}){return <><JobBack navigate={navigate} title="Rapport d’architecte"/><section className="architect-card"><header><div><span>RAPPORT AR-214-03</span><h2>Visite du 8 septembre 2026</h2></div><strong>À traiter</strong></header><p>Architecte : Marie-Claude Roy, OAQ</p><div>{[['01','Confirmer le retour du solin aux fenêtres du deuxième étage.','À vérifier'],['02','Remplacer deux panneaux égratignés sur l’élévation est.','Ouvert'],['03','Joint de finition conforme sur la façade avant.','Conforme'],['04','Ajouter une photo après correction du coin nord-ouest.','Photo requise']].map(x=><article key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><strong>{x[2]}</strong></article>)}</div></section></>}
function JobSpecialView({navigate}:{navigate:Navigate}){return <><JobBack navigate={navigate} title="Demandes spéciales"/><div className="special-list">{[['Accès au chantier','Utiliser uniquement l’entrée côté est avant 8 h.','Tous'],['Protection des finis','Protéger les fenêtres noires avant les travaux de coupe.','Équipe revêtement'],['Livraison','Appeler Jean Breton 30 minutes avant toute livraison.','Chef d’équipe']].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><div><b>{x[0]}</b><p>{x[1]}</p><small>Visible par : {x[2]}</small></div></article>)}</div></>}
function MenuView({role,navigate}:{role:string;navigate:Navigate}){const groups=[['MON ESPACE',[['Mon profil',UserRound,'profile'],['Mes heures',Clock3,'hours'],['Mes commandes',PackageCheck,'orders'],['Mes achats / reçus',ReceiptText,'purchases'],['Mes absences',CalendarDays,'absences']]],['MES INFORMATIONS',[['Urgence',HeartPulse,'emergency'],['Mes documents',FileBadge,'documents']]],['RESSOURCES',[['Documentation',Folder,'documentation'],['Sécurité / Incidents',ShieldAlert,'incidents']]],['APPLICATION',[['Paramètres',Settings,'settings']]]] as const;return <><div className="field-page-title"><span>{role.toUpperCase()}</span><h1>Menu</h1></div>{groups.map(([title,items])=><section className="menu-group" key={title}><h2>{title}</h2><div className="menu-list">{items.map(([label,Icon,dest])=><button key={label} onClick={()=>navigate(dest)}><Icon/><span><b>{label}</b></span><ChevronRight/></button>)}</div></section>)}</>}
function ProfileView({session,navigate}:{session:ForgeSession;navigate:Navigate}){return <><Back navigate={navigate}/><div className="profile-hero"><span>{session.userName.slice(0,2).toUpperCase()}</span><div><h1>{session.userName} Tremblay</h1><p>Charpentier-menuisier · Employé actif</p><small>ID {employeeId(session)}</small></div></div><div className="profile-tabs"><button className="active">Profil</button><button onClick={()=>navigate('documents')}>Documents</button><button onClick={()=>navigate('emergency')}>Urgence</button><button onClick={()=>navigate('absences')}>Absences</button></div><div className="info-grid"><article><span>COORDONNÉES</span><b>{session.email}</b><p>418 555-0142</p></article><article><span>EMPLOI</span><b>Les Revêtements MIR</b><p>Chef : Fred G. · JOB-214</p></article><article><span>CCQ</span><b>Apprenti · période 2</b><p>Institutionnel et commercial</p></article><article><span>HISTORIQUE</span><b>Embauché le 12 avril 2024</b><p>Profil mis à jour le 3 septembre</p></article></div></>}
function AbsencesView({absences,navigate,request,cancel}:{absences:Absence[];navigate:Navigate;request:(v:'leave'|'sick')=>void;cancel:(id:string)=>void}){return <><Back navigate={navigate}/><div className="field-page-title"><span>DISPONIBILITÉ</span><h1>Mes absences</h1></div><div className="dual-actions"><button onClick={()=>request('leave')}><CalendarDays/><b>Demander un congé</b></button><button onClick={()=>request('sick')}><Stethoscope/><b>Signaler maladie</b></button></div><div className="absence-list">{absences.map(a=><article key={a.absence_request_id}><CalendarDays/><span><b>{a.type}</b><small>{a.start_date} → {a.end_date}</small><em>{a.absence_request_id}</em></span><strong className={a.status}>{statusLabel(a.status)}</strong>{a.status==='pending'&&<button onClick={()=>cancel(a.absence_request_id)}>Annuler</button>}</article>)}</div></>}
function EmergencyView({session,navigate}:{session:ForgeSession;navigate:Navigate}){const storage=key(session.companyId,`emergency:${employeeId(session)}`);const [data,setData]=useState(()=>read(storage,{contact:'Marie Tremblay',relationship:'Conjointe',phone:'418 555-0198',blood:'Inconnu',note:''}));return <><Back navigate={navigate}/><div className="field-page-title"><span>INFORMATIONS SENSIBLES</span><h1>Urgence</h1><p>Ces renseignements sont protégés et accessibles uniquement aux personnes autorisées.</p></div><form className="field-form" onSubmit={e=>{e.preventDefault();localStorage.setItem(storage,JSON.stringify(data));writeEvent(session,'employee_emergency_info',employeeId(session),'emergency_info_updated')}}><label>Contact d’urgence<input value={data.contact} onChange={e=>setData({...data,contact:e.target.value})}/></label><label>Lien avec le contact<input value={data.relationship} onChange={e=>setData({...data,relationship:e.target.value})}/></label><label>Téléphone<input value={data.phone} onChange={e=>setData({...data,phone:e.target.value})}/></label><label>Groupe sanguin<select value={data.blood} onChange={e=>setData({...data,blood:e.target.value})}><option>Inconnu</option><option>A+</option><option>A-</option><option>O+</option><option>O-</option></select></label><label>Note d’urgence<textarea value={data.note} onChange={e=>setData({...data,note:e.target.value})}/></label><button className="field-primary"><Check/> Enregistrer</button></form></>}
function DocumentsView({navigate}:{navigate:Navigate}){return <><Back navigate={navigate}/><div className="field-page-title"><span>DOSSIER EMPLOYÉ</span><h1>Mes documents</h1></div><div className="document-list">{[['Carte CCQ','Expire dans 30 jours','warning'],['ASP Construction','Valide','valid'],['SIMDUT 2015','Valide','valid'],['Secourisme','Sans expiration','neutral']].map(d=><article key={d[0]}><FileBadge/><span><b>{d[0]}</b><small>{d[1]}</small></span><strong className={d[2]}>{d[2]==='warning'?'Expire bientôt':'Valide'}</strong><ChevronRight/></article>)}</div><button className="outline-action"><Plus/> Ajouter un document</button></>}
function IncidentsView({incidents,navigate,request}:{incidents:Incident[];navigate:Navigate;request:()=>void}){return <><Back navigate={navigate}/><div className="field-page-title"><span>SANTÉ ET SÉCURITÉ</span><h1>Incidents</h1></div><button className="incident-action" onClick={request}><ShieldAlert/><span><b>Déclarer un incident / accident</b><small>Prévenir immédiatement les responsables concernés</small></span><ChevronRight/></button><div className="incident-list">{incidents.length?incidents.map(i=><article key={i.incident_id}><AlertTriangle/><span><b>{i.type} · {i.job_id}</b><small>{i.incident_at} · {i.location}</small><em>{i.incident_id}</em></span><strong>{i.status}</strong></article>):<div className="empty-state"><ShieldAlert/><b>Aucun incident déclaré</b><small>Les rapports apparaîtront ici et dans la Job concernée.</small></div>}</div></>}
function DocumentationView({navigate}:{navigate:Navigate}){return <><Back navigate={navigate}/><div className="field-page-title"><span>RESSOURCES</span><h1>Documentation importante</h1></div><label className="field-search"><Search/><input placeholder="Rechercher un guide…"/></label><div className="document-list">{['James Hardie','Maibec CanExel','Maibec','Allura','Light Trim','GCR — Revêtement','Code du bâtiment'].map(d=><article key={d}><Folder/><span><b>{d}</b><small>Guide officiel · version courante</small></span><ChevronRight/></article>)}</div></>}
function statusLabel(s:Absence['status']){return s==='approved'?'Approuvée':s==='reported'?'Déclarée':s==='cancelled'?'Annulée':s==='rejected'?'Refusée':'En attente'}
function writeEvent(session:ForgeSession,objectType:string,objectId:string,action:string){const auditKey=key(session.companyId,'audit');const audit=read<Record<string,unknown>[]>(auditKey,[]);localStorage.setItem(auditKey,JSON.stringify([{audit_id:`AUD-${Date.now()}`,company_id:session.companyId,object_type:objectType,object_id:objectId,action,performed_by_user_id:session.email,timestamp:new Date().toISOString()},...audit]));const notifications=read<Record<string,unknown>[]>(key(session.companyId,'notifications'),[]);localStorage.setItem(key(session.companyId,'notifications'),JSON.stringify([{notification_id:`NOT-${Date.now()}`,company_id:session.companyId,source_type:objectType,source_id:objectId,created_at:new Date().toISOString(),read_at:null,deep_link:`#field/${objectType}`},...notifications]))}
