'use client';
import { useState } from 'react';
import { AlertTriangle, ArrowLeft, Bell, CalendarDays, Check, ChevronRight, Clock3, FileBadge, FileText, Folder, HeartPulse, History, MapPin, MessageSquare, PackageCheck, Paperclip, Plus, ReceiptText, Search, Settings, ShieldAlert, Stethoscope, UserRound } from 'lucide-react';
import type { ForgeSession } from './forge-access';
import { PersonalSettings } from './forge-suite';

export type FieldView='home'|'projects'|'project'|'menu'|'profile'|'hours'|'absences'|'emergency'|'documents'|'incidents'|'documentation'|'settings';
type Navigate=(view:FieldView|'punch'|'orders'|'messages'|'purchases')=>void;
type Absence={absence_request_id:string;company_id:string;employee_id:string;type:string;start_date:string;end_date:string;full_day:boolean;note:string;status:'pending'|'reported'|'approved'|'rejected'|'cancelled';created_at:string};
type Incident={incident_id:string;company_id:string;job_id:string;reported_by_user_id:string;type:string;severity:string;incident_at:string;location:string;description:string;status:string};
const employeeId=(session:ForgeSession)=>`employee:${session.companyId}:${session.email}`;
const key=(companyId:string,type:string)=>`forge:${companyId}:${type}`;
const read=<T,>(storageKey:string,fallback:T):T=>{if(typeof window==='undefined')return fallback;try{return JSON.parse(localStorage.getItem(storageKey)||'null')||fallback}catch{return fallback}};

export function FieldWorkspace({view,session,role,navigate}:{view:FieldView;session:ForgeSession;role:'Chef'|'Employé';navigate:Navigate}){
 const [absences,setAbslify]=useState<Absence[]>(()=>read(key(session.companyId,'absence-requests'),[{absence_request_id:'ABS-2026-014',company_id:session.companyId,employee_id:employeeId(session),type:'Vacances',start_date:'2026-09-21',end_date:'2026-09-25',full_day:true,note:'',status:'approved',created_at:'2026-08-28T14:00:00Z'}]));
 const [incidents,setIncidents]=useState<Incident[]>(()=>read(key(session.companyId,'incidents'),[]));
 const [dialog,setDialog]=useState<'leave'|'sick'|'incident'|null>(null);
 const saveAbsences=(next:Absence[])=>{setAbslify(next);localStorage.setItem(key(session.companyId,'absence-requests'),JSON.stringify(next));window.dispatchEvent(new Event('forge-absences-updated'))};
 const saveIncidents=(next:Incident[])=>{setIncidents(next);localStorage.setItem(key(session.companyId,'incidents'),JSON.stringify(next));window.dispatchEvent(new Event('forge-incidents-updated'))};
 const submitAbsence=(e:React.FormEvent<HTMLFormElement>,sick=false)=>{e.preventDefault();const f=new FormData(e.currentTarget);const item:Absence={absence_request_id:`ABS-${Date.now()}`,company_id:session.companyId,employee_id:employeeId(session),type:sick?'Maladie':String(f.get('type')||'Vacances'),start_date:String(f.get('start')),end_date:String(f.get('end')||f.get('start')),full_day:true,note:String(f.get('note')||''),status:sick?'reported':'pending',created_at:new Date().toISOString()};saveAbsences([item,...absences]);writeEvent(session,'absence_request',item.absence_request_id,sick?'absence_reported':'absence_submitted');setDialog(null)};
 const submitIncident=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const item:Incident={incident_id:`INC-${Date.now()}`,company_id:session.companyId,job_id:String(f.get('job')),reported_by_user_id:session.email,type:String(f.get('type')),severity:String(f.get('severity')),incident_at:String(f.get('date')),location:String(f.get('location')),description:String(f.get('description')),status:'submitted'};saveIncidents([item,...incidents]);writeEvent(session,'incident',item.incident_id,'incident_submitted');setDialog(null)};
 if(view==='settings')return <div className="field-workspace"><Back navigate={navigate}/><PersonalSettings session={session}/></div>;
 return <section className="field-workspace">
  <header className="field-mobile-head"><b>FORGE</b><div><button aria-label="Notifications"><Bell/><i>3</i></button><span>{session.userName.slice(0,2).toUpperCase()}</span><small>{session.userName}<em>{role}</em></small></div></header>
  {view==='home'&&<HomeView session={session} navigate={navigate} request={setDialog}/>} 
  {view==='projects'&&<ProjectsView navigate={navigate}/>} 
  {view==='project'&&<ProjectView navigate={navigate} incidents={incidents}/>} 
  {view==='menu'&&<MenuView role={role} navigate={navigate}/>} 
  {view==='profile'&&<ProfileView session={session} navigate={navigate}/>} 
  {view==='hours'&&<HoursView navigate={navigate}/>} 
  {view==='absences'&&<AbsencesView absences={absences} navigate={navigate} request={setDialog} cancel={id=>saveAbsences(absences.map(a=>a.absence_request_id===id?{...a,status:'cancelled'}:a))}/>} 
  {view==='emergency'&&<EmergencyView session={session} navigate={navigate}/>} 
  {view==='documents'&&<DocumentsView navigate={navigate}/>} 
  {view==='incidents'&&<IncidentsView incidents={incidents} navigate={navigate} request={()=>setDialog('incident')}/>} 
  {view==='documentation'&&<DocumentationView navigate={navigate}/>} 
  {dialog&&<div className="field-dialog"><form onSubmit={e=>dialog==='incident'?submitIncident(e):submitAbsence(e,dialog==='sick')}><button type="button" className="dialog-close" onClick={()=>setDialog(null)}>×</button><span>{dialog==='incident'?'SÉCURITÉ':dialog==='sick'?'ABSENCE IMMÉDIATE':'ABSENCE & CONGÉS'}</span><h2>{dialog==='incident'?'Déclarer un incident':dialog==='sick'?'Signaler une maladie':'Demander un congé'}</h2>{dialog==='incident'?<><label>Job<select name="job"><option>JOB-214</option><option>JOB-315</option></select></label><label>Type<select name="type"><option>Accident avec blessure</option><option>Quasi-accident</option><option>Dommage matériel</option><option>Incident sécurité</option></select></label><label>Gravité<select name="severity"><option>Mineure</option><option>Modérée</option><option>Importante</option></select></label><label>Date et heure<input name="date" type="datetime-local" required/></label><label>Lieu<input name="location" required/></label><label>Description<textarea name="description" required/></label><label className="file-action"><Paperclip/> Ajouter des photos<input type="file" accept="image/*" multiple/></label></>:<>{dialog!=='sick'&&<label>Type<select name="type"><option>Vacances</option><option>Congé personnel</option><option>Rendez-vous</option><option>Congé parental</option></select></label>}<label>Date de début<input name="start" type="date" required/></label>{dialog==='leave'&&<label>Date de fin<input name="end" type="date" required/></label>}<label>Note facultative<textarea name="note"/></label></>}<button className="field-primary"><Check/> {dialog==='incident'?'Soumettre le rapport':dialog==='sick'?'Signaler mon absence':'Envoyer la demande'}</button></form></div>}
 </section>
}

function Back({navigate}:{navigate:Navigate}){return <button className="field-back" onClick={()=>navigate('menu')}><ArrowLeft/> Retour</button>}
function HomeView({session,navigate,request}:{session:ForgeSession;navigate:Navigate;request:(v:'leave'|'sick'|'incident')=>void}){const shortcuts=[['Mes heures',Clock3,'hours'],['Mes commandes',PackageCheck,'orders'],['Mes achats / reçus',ReceiptText,'purchases'],['Mes absences',CalendarDays,'absences'],['Documentation',Folder,'documentation'],['Signaler un incident',AlertTriangle,'incidents'],['Signaler une maladie',Stethoscope,'sick'],['Demander un congé',CalendarDays,'leave']] as const;return <><div className="field-greeting"><span>LUNDI 8 SEPTEMBRE 2026</span><h1>Bonne journée, {session.userName}.</h1><p>Sécuritaire aujourd’hui. On bâtit demain.</p></div><article className="current-job"><div><span>MA JOB ACTUELLE</span><h2>JOB-214</h2><b>Résidence Breton</b><small><MapPin/> Québec</small></div><button onClick={()=>navigate('punch')}><Clock3/> PUNCH IN</button></article><section className="field-section"><div className="field-section-title"><h2>Raccourcis rapides</h2><button onClick={()=>navigate('menu')}>Tout voir <ChevronRight/></button></div><div className="shortcut-grid">{shortcuts.map(([label,Icon,dest])=><button key={label} onClick={()=>dest==='leave'||dest==='sick'?request(dest):navigate(dest)}><Icon/><span>{label}</span></button>)}</div></section><section className="field-section"><div className="field-section-title"><h2>Notifications</h2><button>Voir toutes <ChevronRight/></button></div><div className="home-notifications"><button onClick={()=>navigate('messages')}><MessageSquare/><span><b>Nouveau message dans JOB-214</b><small>Patrick · On commence à 7 h demain.</small></span><i/></button><button onClick={()=>navigate('documents')}><AlertTriangle/><span><b>Document expirant bientôt</b><small>Votre carte CCQ expire dans 30 jours.</small></span><i/></button><button onClick={()=>navigate('projects')}><CalendarDays/><span><b>Nouvelle Job assignée</b><small>JOB-301 · Centre commercial</small></span></button></div></section></>}
function ProjectsView({navigate}:{navigate:Navigate}){return <><div className="field-page-title"><span>FORGE</span><h1>Projets</h1></div><label className="field-search"><Search/><input placeholder="Rechercher un projet…"/></label><h2>Mes projets</h2><div className="field-project-list">{[['JOB-214','Résidence Breton','Québec · En cours'],['JOB-301','Centre commercial','Lévis · Assigné'],['JOB-188','Duplex Tremblay','Québec · En attente']].map((p,i)=><button className={i===0?'active':''} key={p[0]} onClick={()=>navigate('project')}><span><b>{p[0]} — {p[1]}</b><small>{p[2]}</small></span><ChevronRight/></button>)}</div></>}
function ProjectView({navigate,incidents}:{navigate:Navigate;incidents:Incident[]}){const links=[['Aperçu',FileText],['Plans & documents',Folder],['Photos',FileBadge],['Commandes',PackageCheck],['Achats & reçus',ReceiptText],['Discussion',MessageSquare],['Incidents',ShieldAlert],['Historique',History]];return <><button className="field-back" onClick={()=>navigate('projects')}><ArrowLeft/> Retour aux projets</button><div className="field-page-title"><span>JOB-214</span><h1>Résidence Breton</h1><p>1280, rue Industrielle, Québec</p></div><div className="project-summary"><b>Chantier en cours</b><span>Fred G. · Chef d’équipe</span><small>Dernière activité aujourd’hui, 9 h 12</small></div><div className="menu-list">{links.map(([label,Icon])=><button key={label as string} onClick={()=>label==='Incidents'?navigate('incidents'):label==='Commandes'?navigate('orders'):label==='Discussion'?navigate('messages'):undefined}><Icon/><span><b>{label as string}</b>{label==='Incidents'&&<small>{incidents.length} rapport(s)</small>}</span><ChevronRight/></button>)}</div></>}
function MenuView({role,navigate}:{role:string;navigate:Navigate}){const groups=[['MON ESPACE',[['Mon profil',UserRound,'profile'],['Mes heures',Clock3,'hours'],['Mes commandes',PackageCheck,'orders'],['Mes achats / reçus',ReceiptText,'purchases'],['Mes absences',CalendarDays,'absences']]],['MES INFORMATIONS',[['Urgence',HeartPulse,'emergency'],['Mes documents',FileBadge,'documents']]],['RESSOURCES',[['Documentation',Folder,'documentation'],['Sécurité / Incidents',ShieldAlert,'incidents']]],['APPLICATION',[['Paramètres',Settings,'settings']]]] as const;return <><div className="field-page-title"><span>{role.toUpperCase()}</span><h1>Menu</h1></div>{groups.map(([title,items])=><section className="menu-group" key={title}><h2>{title}</h2><div className="menu-list">{items.map(([label,Icon,dest])=><button key={label} onClick={()=>navigate(dest)}><Icon/><span><b>{label}</b></span><ChevronRight/></button>)}</div></section>)}</>}
function ProfileView({session,navigate}:{session:ForgeSession;navigate:Navigate}){return <><Back navigate={navigate}/><div className="profile-hero"><span>{session.userName.slice(0,2).toUpperCase()}</span><div><h1>{session.userName} Tremblay</h1><p>Charpentier-menuisier · Employé actif</p><small>ID {employeeId(session)}</small></div></div><div className="profile-tabs"><button className="active">Profil</button><button onClick={()=>navigate('documents')}>Documents</button><button onClick={()=>navigate('emergency')}>Urgence</button><button onClick={()=>navigate('absences')}>Absences</button></div><div className="info-grid"><article><span>COORDONNÉES</span><b>{session.email}</b><p>418 555-0142</p></article><article><span>EMPLOI</span><b>Les Revêtements MIR</b><p>Chef : Fred G. · JOB-214</p></article><article><span>CCQ</span><b>Apprenti · période 2</b><p>Institutionnel et commercial</p></article><article><span>HISTORIQUE</span><b>Embauché le 12 avril 2024</b><p>Profil mis à jour le 3 septembre</p></article></div></>}
function HoursView({navigate}:{navigate:Navigate}){return <><Back navigate={navigate}/><div className="field-page-title"><span>TEMPS DE TRAVAIL</span><h1>Mes heures</h1></div><div className="hours-kpis"><article><span>AUJOURD’HUI</span><b>7 h 30</b></article><article><span>CETTE SEMAINE</span><b>35 h 30</b></article></div><div className="timeline-list">{[['8 sept.','JOB-214','06:31 → 15:42','9 h 11'],['7 sept.','JOB-315','07:02 → 15:18','8 h 01'],['6 sept.','JOB-214','06:44 → 15:19','8 h 35']].map(r=><article key={r[0]}><Clock3/><span><b>{r[0]} · {r[1]}</b><small>{r[2]}</small></span><strong>{r[3]}</strong></article>)}</div></>}
function AbsencesView({absences,navigate,request,cancel}:{absences:Absence[];navigate:Navigate;request:(v:'leave'|'sick')=>void;cancel:(id:string)=>void}){return <><Back navigate={navigate}/><div className="field-page-title"><span>DISPONIBILITÉ</span><h1>Mes absences</h1></div><div className="dual-actions"><button onClick={()=>request('leave')}><CalendarDays/><b>Demander un congé</b></button><button onClick={()=>request('sick')}><Stethoscope/><b>Signaler maladie</b></button></div><div className="absence-list">{absences.map(a=><article key={a.absence_request_id}><CalendarDays/><span><b>{a.type}</b><small>{a.start_date} → {a.end_date}</small><em>{a.absence_request_id}</em></span><strong className={a.status}>{statusLabel(a.status)}</strong>{a.status==='pending'&&<button onClick={()=>cancel(a.absence_request_id)}>Annuler</button>}</article>)}</div></>}
function EmergencyView({session,navigate}:{session:ForgeSession;navigate:Navigate}){const storage=key(session.companyId,`emergency:${employeeId(session)}`);const [data,setData]=useState(()=>read(storage,{contact:'Marie Tremblay',relationship:'Conjointe',phone:'418 555-0198',blood:'Inconnu',note:''}));return <><Back navigate={navigate}/><div className="field-page-title"><span>INFORMATIONS SENSIBLES</span><h1>Urgence</h1><p>Ces renseignements sont protégés et accessibles uniquement aux personnes autorisées.</p></div><form className="field-form" onSubmit={e=>{e.preventDefault();localStorage.setItem(storage,JSON.stringify(data));writeEvent(session,'employee_emergency_info',employeeId(session),'emergency_info_updated')}}><label>Contact d’urgence<input value={data.contact} onChange={e=>setData({...data,contact:e.target.value})}/></label><label>Lien avec le contact<input value={data.relationship} onChange={e=>setData({...data,relationship:e.target.value})}/></label><label>Téléphone<input value={data.phone} onChange={e=>setData({...data,phone:e.target.value})}/></label><label>Groupe sanguin<select value={data.blood} onChange={e=>setData({...data,blood:e.target.value})}><option>Inconnu</option><option>A+</option><option>A-</option><option>O+</option><option>O-</option></select></label><label>Note d’urgence<textarea value={data.note} onChange={e=>setData({...data,note:e.target.value})}/></label><button className="field-primary"><Check/> Enregistrer</button></form></>}
function DocumentsView({navigate}:{navigate:Navigate}){return <><Back navigate={navigate}/><div className="field-page-title"><span>DOSSIER EMPLOYÉ</span><h1>Mes documents</h1></div><div className="document-list">{[['Carte CCQ','Expire dans 30 jours','warning'],['ASP Construction','Valide','valid'],['SIMDUT 2015','Valide','valid'],['Secourisme','Sans expiration','neutral']].map(d=><article key={d[0]}><FileBadge/><span><b>{d[0]}</b><small>{d[1]}</small></span><strong className={d[2]}>{d[2]==='warning'?'Expire bientôt':'Valide'}</strong><ChevronRight/></article>)}</div><button className="outline-action"><Plus/> Ajouter un document</button></>}
function IncidentsView({incidents,navigate,request}:{incidents:Incident[];navigate:Navigate;request:()=>void}){return <><Back navigate={navigate}/><div className="field-page-title"><span>SANTÉ ET SÉCURITÉ</span><h1>Incidents</h1></div><button className="incident-action" onClick={request}><ShieldAlert/><span><b>Déclarer un incident / accident</b><small>Prévenir immédiatement les responsables concernés</small></span><ChevronRight/></button><div className="incident-list">{incidents.length?incidents.map(i=><article key={i.incident_id}><AlertTriangle/><span><b>{i.type} · {i.job_id}</b><small>{i.incident_at} · {i.location}</small><em>{i.incident_id}</em></span><strong>{i.status}</strong></article>):<div className="empty-state"><ShieldAlert/><b>Aucun incident déclaré</b><small>Les rapports apparaîtront ici et dans la Job concernée.</small></div>}</div></>}
function DocumentationView({navigate}:{navigate:Navigate}){return <><Back navigate={navigate}/><div className="field-page-title"><span>RESSOURCES</span><h1>Documentation importante</h1></div><label className="field-search"><Search/><input placeholder="Rechercher un guide…"/></label><div className="document-list">{['James Hardie','Maibec CanExel','Maibec','Allura','Light Trim','GCR — Revêtement','Code du bâtiment'].map(d=><article key={d}><Folder/><span><b>{d}</b><small>Guide officiel · version courante</small></span><ChevronRight/></article>)}</div></>}
function statusLabel(s:Absence['status']){return s==='approved'?'Approuvée':s==='reported'?'Déclarée':s==='cancelled'?'Annulée':s==='rejected'?'Refusée':'En attente'}
function writeEvent(session:ForgeSession,objectType:string,objectId:string,action:string){const auditKey=key(session.companyId,'audit');const audit=read<Record<string,unknown>[]>(auditKey,[]);localStorage.setItem(auditKey,JSON.stringify([{audit_id:`AUD-${Date.now()}`,company_id:session.companyId,object_type:objectType,object_id:objectId,action,performed_by_user_id:session.email,timestamp:new Date().toISOString()},...audit]));const notifications=read<Record<string,unknown>[]>(key(session.companyId,'notifications'),[]);localStorage.setItem(key(session.companyId,'notifications'),JSON.stringify([{notification_id:`NOT-${Date.now()}`,company_id:session.companyId,source_type:objectType,source_id:objectId,created_at:new Date().toISOString(),read_at:null,deep_link:`#field/${objectType}`},...notifications]))}
