'use client';
import {useState} from 'react';
import type {DynamicProduct} from './catalog-builder';
import {displayed,measured,profilePoints,validateGeometry,type FoldingGeometry,type FoldingSegment} from '../lib/folding-domain';

export function FoldingDrawing({geometry}:{geometry:FoldingGeometry}){
 const points=profilePoints(geometry),xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=Math.min(...xs),minY=Math.min(...ys),w=Math.max(...xs)-minX||1,h=Math.max(...ys)-minY||1;
 const scale=Math.min(430/w,200/h),mapped=points.map(p=>({x:35+(p.x-minX)*scale,y:35+(p.y-minY)*scale}));
 return <svg viewBox="0 0 500 270" role="img" aria-label="Profil paramétrique et cotes" style={{width:'100%',maxHeight:270,background:'var(--forge-bg, #0b1410)',borderRadius:10}}><polyline points={mapped.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="var(--accent)" strokeWidth="3"/>{geometry.segments.map((s,i)=><text key={s.id} x={(mapped[i].x+mapped[i+1].x)/2} y={(mapped[i].y+mapped[i+1].y)/2-10} textAnchor="middle" fill="currentColor" fontSize="13">{s.label} · {displayed(s.length,geometry.unit)} {geometry.unit==='inch'?'″':'mm'}</text>)}</svg>;
}
export function FoldingSettings({product,onChange}:{product:DynamicProduct;onChange:(p:DynamicProduct)=>void}){
 const [error,setError]=useState('');const definition=product.folding;
 if(!definition)return <section><h3>Profil paramétrique</h3><p>Définissez les vraies dimensions. Le croquis existant reste conservé; ses pixels ne seront pas convertis en mesures.</p><button type="button" onClick={()=>onChange({...product,folding:{draft:{unit:'inch',material:'Acier',thickness:.018,segments:[{id:crypto.randomUUID(),label:'A',length:1,angle:0,mode:'fixed',min:.125,max:144,step:.125,doubleFold:'none'}]},versions:[]}})}>Configurer les dimensions réelles</button></section>;
 const g=definition.draft;
 function update(patch:Partial<FoldingGeometry>){onChange({...product,folding:{...definition!,publishOnSave:false,draft:{...g,...patch}}})}
 function segment(id:string,patch:Partial<FoldingSegment>){update({segments:g.segments.map(s=>s.id===id?{...s,...patch}:s)})}
 const measure=(value:number,onValue:(v:number)=>void,label:string)=><input key={`${label}-${value}-${g.unit}`} aria-label={label} defaultValue={displayed(value,g.unit)} onBlur={e=>{try{onValue(measured(e.target.value,g.unit));setError('')}catch(err){setError((err as Error).message);e.target.value=displayed(value,g.unit)}}}/>;
 const errors=validateGeometry(g);
 return <section className="folding-settings"><h3>Dimensions et versions</h3><p>V{definition.versions.at(-1)?.number||0} publiée · modifications en brouillon · démo locale</p><div className="builder-basic"><label>Unité<select value={g.unit} onChange={e=>update({unit:e.target.value as 'inch'|'mm'})}><option value="inch">Pouces</option><option value="mm">Millimètres</option></select></label><label>Matériau<input value={g.material} onChange={e=>update({material:e.target.value})}/></label><label>Épaisseur{measure(g.thickness,v=>update({thickness:v}),'Épaisseur')}</label></div><FoldingDrawing geometry={g}/>
 {g.segments.map((s,i)=><fieldset key={s.id}><legend>Segment {s.label||i+1}</legend><div className="builder-basic"><label>Label<input value={s.label} onChange={e=>segment(s.id,{label:e.target.value})}/></label><label>Longueur{measure(s.length,v=>segment(s.id,{length:v}),`Longueur ${s.id}`)}</label><label>Rotation relative (°)<input type="number" min="-180" max="180" value={s.angle} onChange={e=>segment(s.id,{angle:Number(e.target.value)})}/></label><label>Dimension<select value={s.mode} onChange={e=>segment(s.id,{mode:e.target.value as FoldingSegment['mode']})}><option value="fixed">Fixe</option><option value="employee_input">Fournie par l’employé</option></select></label>{s.mode==='employee_input'&&<><label>Minimum{measure(s.min,v=>segment(s.id,{min:v}),`Minimum ${s.id}`)}</label><label>Maximum{measure(s.max,v=>segment(s.id,{max:v}),`Maximum ${s.id}`)}</label><label>Pas{measure(s.step,v=>segment(s.id,{step:v}),`Pas ${s.id}`)}</label></>}</div>{i===g.segments.length-1&&g.segments.length>1&&<button type="button" onClick={()=>update({segments:g.segments.slice(0,-1)})}>Retirer le dernier segment</button>}</fieldset>)}
 <button type="button" disabled={g.segments.length>=100} onClick={()=>update({segments:[...g.segments,{id:crypto.randomUUID(),label:String.fromCharCode(65+g.segments.length),length:1,angle:90,mode:'fixed',min:.125,max:144,step:.125,doubleFold:'none'}]})}>Ajouter un segment</button>
 {(error||errors.length>0)&&<p role="alert">{error||errors.join(' ')}</p>}<label className="check-row"><input type="checkbox" disabled={errors.length>0} checked={!!definition.publishOnSave} onChange={e=>onChange({...product,folding:{...definition,publishOnSave:e.target.checked}})}/> Publier une nouvelle version lors de la sauvegarde</label><p>Sans publication, les commandes utilisent la dernière version publiée.</p><details><summary>Historique · {definition.versions.length} version(s)</summary>{definition.versions.map(v=><details key={v.id}><summary>V{v.number} · {new Date(v.publishedAt).toLocaleString('fr-CA')}</summary><FoldingDrawing geometry={v.geometry}/></details>)}</details></section>;
}
