'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ChevronRight,Plus,Camera,Mic,Send,Search,X,FileText,Image,Folder,Users,Link,Square,Trash2,MessageSquare,LockKeyhole} from 'lucide-react';
import {MessageReaders,type MessageReader} from './message-readers';
import type {ForgeSession} from './forge-access';
import type {FieldJob} from './project-overview';
type Asset={id:string;name:string;kind:'image'|'audio'|'document'|'job'|'link';url?:string;entityId?:string};
type Message={id:string;conversation_id:string;sender:string;body:string;created_at:string;attachments:Asset[];reply?:string;readers?:MessageReader[]};
export function ForgeMessages({session,jobs,onJob}:{session:ForgeSession;jobs:FieldJob[];onJob:(number:string)=>void}){
 const allowed=jobs.filter(j=>j.company_id===session.companyId&&(session.role==='Boss'||session.role==='Adjointe'||j.members.includes(session.email)));
 // Local preview only. Production IDs/participants come from the authorized central resolver.
 const privateDiscussions=session.role==='Employé'||session.role==='Chef'?['Boss','Adjointe'].map(recipient=>({
  id:`preview:private:${encodeURIComponent(session.companyId)}:${encodeURIComponent(session.email.toLowerCase())}:${recipient}`,
  number:'',name:recipient,members:[session.userName+' · '+session.role,recipient],private:true
 })):[];
 const discussions=[...privateDiscussions,...allowed.map(j=>({...j,private:false}))];
 const [selected,setSelected]=useState('');const current=discussions.find(j=>j.id===selected)||discussions.find(j=>!j.private)||discussions[0];
 const [messages,setMessages]=useState<Message[]>([]);const [body,setBody]=useState('');const [pending,setPending]=useState<Asset[]>([]);
 const [sheet,setSheet]=useState<'discussions'|'attach'|'info'|'files'|null>(null);const [query,setQuery]=useState('');const [find,setFind]=useState('');const [searching,setSearching]=useState(false);const [error,setError]=useState('');const [reply,setReply]=useState<Message|null>(null);const [unseen,setUnseen]=useState(false);
 const [recording,setRecording]=useState(false);const [seconds,setSeconds]=useState(0);const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const discard=useRef(false);
 const files=useRef<HTMLInputElement>(null);const camera=useRef<HTMLInputElement>(null);const feed=useRef<HTMLDivElement>(null);const nearBottom=useRef(true);const urls=useRef<string[]>([]);
 const title=current?(current.private?current.name:`${current.number} · ${current.name}`):'Aucune discussion';
 const sample:Message[]=session.companyId==='mir-demo'&&current&&!current.private?[{id:`${current.id}:sample1`,conversation_id:current.id,sender:'Ester',body:'J’ai reçu tes photos. Je les joins à la commande du chantier.',created_at:'2026-09-10T09:42:00',attachments:[]},{id:`${current.id}:sample2`,conversation_id:current.id,sender:session.email,body:'Parfait ! Il faut livrer directement au chantier dans 2 jours.',created_at:'2026-09-10T09:44:00',attachments:[],readers:[{id:'demo-simon',name:'Simon'}]},{id:`${current.id}:sample3`,conversation_id:current.id,sender:'Simon',body:'La commande est prête. Je vous envoie le bordereau.',created_at:'2026-09-10T09:46:00',attachments:[]}]:[];
 const thread=[...sample,...messages.filter(m=>m.conversation_id===current?.id)];const visible=thread.filter(m=>`${m.body} ${m.sender}`.toLocaleLowerCase().includes(find.toLocaleLowerCase()));
 const scrollBottom=()=>{feed.current?.scrollTo({top:feed.current.scrollHeight,behavior:'smooth'});setUnseen(false)};
 useEffect(()=>{if(nearBottom.current)scrollBottom();else setUnseen(true)},[messages.length]);
 useEffect(()=>{nearBottom.current=true;setFind('');setReply(null);setBody('');setPending([]);feed.current?.scrollTo({top:feed.current.scrollHeight})},[current?.id]);
 useEffect(()=>{if(!recording)return;const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[recording]);
 useEffect(()=>()=>{discard.current=true;recorder.current?.state==='recording'&&recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());urls.current.forEach(u=>URL.revokeObjectURL(u))},[]);
 const addFile=(file:File)=>{if(file.size>15*1024*1024){setError('Maximum 15 Mo par fichier.');return}const kind=file.type.startsWith('image/')?'image':file.type.startsWith('audio/')?'audio':file.type==='application/pdf'?'document':null;if(!kind){setError('Choisissez une photo, un PDF ou un fichier audio.');return}const url=URL.createObjectURL(file);urls.current.push(url);setPending(p=>p.length>=5?p:[...p,{id:crypto.randomUUID(),name:file.name,kind,url}]);setSheet(null)};
 const send=()=>{if(!current||(!body.trim()&&!pending.length))return;nearBottom.current=true;setMessages(m=>[...m,{id:crypto.randomUUID(),conversation_id:current.id,sender:session.email,body:body.trim(),created_at:new Date().toISOString(),attachments:pending,reply:reply?.body}]);setBody('');setPending([]);setReply(null);setError('')};
 const voice=async()=>{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('Enregistrement audio indisponible dans ce navigateur.');return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const rec=new MediaRecorder(stream.current);recorder.current=rec;const chunks:Blob[]=[];discard.current=false;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);if(!discard.current)addFile(new File(chunks,'Message vocal.webm',{type:rec.mimeType||'audio/webm'}))};rec.start();setSeconds(0);setRecording(true)}catch{setError('Microphone inaccessible. Vérifiez l’autorisation du navigateur.')}};
 const asset=(a:Asset)=><div key={a.id} className="fm-asset">{a.kind==='image'?<a href={a.url} target="_blank" rel="noreferrer"><img src={a.url} alt={a.name} loading="lazy"/></a>:a.kind==='audio'?<audio controls preload="none" src={a.url}/>:a.kind==='job'?<button onClick={()=>{const job=allowed.find(j=>j.id===a.entityId);if(job)onJob(job.number)}}><Folder/>{allowed.find(j=>j.id===a.entityId)?.number||'Job indisponible'}<ChevronRight/></button>:<a href={a.url} target="_blank" rel="noreferrer"><FileText/>{a.name}<ChevronRight/></a>}</div>;
 const discussionList=<><label className="fm-search"><Search/><input placeholder="Rechercher une discussion…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="fm-discussions">{discussions.filter(j=>`${j.number} ${j.name} ${j.private?'privée':''}`.toLowerCase().includes(query.toLowerCase())).map(j=><button key={j.id} className={j.id===current?.id?'active':''} onClick={()=>{setSelected(j.id);setSheet(null)}}><span className="fm-avatar">{j.private?<LockKeyhole/>:<Folder/>}</span><span><b>{j.private?j.name:`${j.number} · ${j.name}`}</b><small>{j.private?`Privée · vous et ${j.name}`:`${j.members.length} membres assignés`}</small></span><ChevronRight/></button>)}{!discussions.length&&<p>Aucune discussion disponible.</p>}</div></>;
 return <article id="messages" className="forge-messages" aria-label="Messages"><aside className="fm-sidebar"><h2>Discussions</h2>{discussionList}</aside><section className="fm-conversation"><header className="fm-header"><div><button className="fm-back" onClick={()=>setSheet('discussions')}><ArrowLeft/> Messages</button><button aria-label="Choisir une discussion" className="fm-title" onClick={()=>setSheet('discussions')}><b>{title}</b></button><small>{current?(current.private?`Privée · vous et ${current.name}`:`${current.members.length} membres assignés`):'Choisissez une discussion'}</small></div><button className="fm-info-button" aria-label="Informations de la discussion" onClick={()=>setSheet('info')}>Infos</button></header><div className="fm-demo-note">Aperçu local · messages et fichiers non envoyés aux employés</div>{searching&&<label className="fm-search"><Search/><input autoFocus placeholder="Rechercher dans la discussion…" value={find} onChange={e=>setFind(e.target.value)}/><button aria-label="Fermer la recherche" onClick={()=>{setSearching(false);setFind('')}}><X/></button></label>}
 <div className="fm-feed" ref={feed} onScroll={()=>{const e=feed.current;if(e)nearBottom.current=e.scrollHeight-e.scrollTop-e.clientHeight<60}}>{visible.map(m=><div key={m.id} className={`fm-message ${m.sender===session.email?'mine':''}`}><span className="fm-avatar">{(m.sender===session.email?session.userName:m.sender).slice(0,2).toUpperCase()}</span><div className="fm-message-content"><div className="fm-meta"><b>{m.sender===session.email?'Vous':m.sender}</b><time>{new Date(m.created_at).toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'})}</time></div><div className="fm-bubble">{m.reply&&<blockquote>{m.reply}</blockquote>}{m.body&&<p>{m.body}</p>}{m.attachments.map(asset)}</div>{m.sender===session.email&&<MessageReaders readers={m.readers||[]} sender={m.sender} connected={false}/>}{m.sender!==session.email&&<button className="fm-reply" onClick={()=>setReply(m)}>Répondre</button>}</div></div>)}{!visible.length&&<div className="fm-empty"><MessageSquare/><p>{find?'Aucun résultat.':'Commencez la discussion.'}</p></div>}</div>{unseen&&<button className="fm-new" onClick={scrollBottom}>Nouveaux messages ↓</button>}
 <div className="fm-compose-zone">{error&&<p role="alert" className="fm-error">{error}<button aria-label="Fermer" onClick={()=>setError('')}><X/></button></p>}{reply&&<div className="fm-pending"><span>Réponse : {reply.body}</span><button aria-label="Annuler la réponse" onClick={()=>setReply(null)}><X/></button></div>}{pending.map(a=><div key={a.id} className="fm-pending"><span>{a.name}</span><button aria-label={`Retirer ${a.name}`} onClick={()=>setPending(p=>p.filter(x=>x.id!==a.id))}><X/></button></div>)}{recording?<div className="fm-composer"><button aria-label="Annuler l’enregistrement" onClick={()=>{discard.current=true;recorder.current?.stop()}}><Trash2/></button><span role="status">Enregistrement · {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</span><button aria-label="Terminer l’enregistrement" onClick={()=>recorder.current?.stop()}><Square/></button></div>:<form className="fm-composer" onSubmit={e=>{e.preventDefault();send()}}><button type="button" aria-label="Joindre à la discussion" onClick={()=>setSheet('attach')} disabled={!current}><Plus/></button><input aria-label="Écrire un message" placeholder="Écrire un message…" value={body} onChange={e=>setBody(e.target.value)} disabled={!current}/><button type="button" aria-label="Prendre une photo" onClick={()=>camera.current?.click()} disabled={!current}><Camera/></button>{body.trim()||pending.length?<button aria-label="Envoyer dans l’aperçu local" className="fm-send"><Send/></button>:<button type="button" aria-label="Enregistrer un message vocal" onClick={()=>void voice()} disabled={!current}><Mic/></button>}</form>}</div></section>
 <input ref={files} type="file" accept="image/*,audio/*,application/pdf" multiple hidden onChange={e=>{Array.from(e.target.files||[]).slice(0,5-pending.length).forEach(addFile);e.target.value=''}}/><input ref={camera} type="file" accept="image/*" capture="environment" hidden onChange={e=>{if(e.target.files?.[0])addFile(e.target.files[0]);e.target.value=''}}/>
 {sheet&&<div className="fm-backdrop" onClick={()=>setSheet(null)}><section className="fm-sheet" role="dialog" aria-modal="true" aria-label={sheet==='discussions'?'Discussions':sheet==='attach'?'Joindre à la discussion':'Informations de la discussion'} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSheet(null)}}><header><h2>{sheet==='discussions'?'Discussions':sheet==='attach'?'Joindre à la discussion':sheet==='files'?'Fichiers partagés':'Informations'}</h2><button autoFocus aria-label="Fermer" onClick={()=>setSheet(null)}><X/></button></header><div className="fm-sheet-body">{sheet==='discussions'?discussionList:sheet==='attach'?<><button onClick={()=>camera.current?.click()}><Camera/>Prendre une photo</button><button onClick={()=>files.current?.click()}><Image/>Photo, document ou audio</button><button disabled={!current||current.private} onClick={()=>{if(current&&!current.private)setPending(p=>p.length>=5?p:[...p,{id:crypto.randomUUID(),name:current.number,kind:'job',entityId:current.id}]);setSheet(null)}}><Folder/>Joindre cette Job</button><form onSubmit={e=>{e.preventDefault();const value=new FormData(e.currentTarget).get('url')?.toString()||'';try{const url=new URL(value);if(!['http:','https:'].includes(url.protocol))throw Error();setPending(p=>p.length>=5?p:[...p,{id:crypto.randomUUID(),name:url.hostname,kind:'link',url:url.href}]);setSheet(null)}catch{setError('Utilisez un lien http ou https.')}}}><label><Link/>Lien / URL<input name="url" type="url" placeholder="https://…" required/></label><button>Ajouter le lien</button></form><p>Les commandes, reçus et autres objets seront disponibles après connexion aux services centraux.</p></>:sheet==='files'?<>{thread.flatMap(m=>m.attachments).map(asset)}{!thread.some(m=>m.attachments.length)&&<p>Aucun fichier partagé dans cet aperçu.</p>}</>:<><h3>{title}</h3>{current&&!current.private&&<button onClick={()=>onJob(current.number)}><Folder/>Voir le projet<ChevronRight/></button>}<h3><Users/> Membres</h3>{current?.members.map(m=><p key={m}>{m}</p>)}<button onClick={()=>setSheet('files')}><FileText/>Fichiers, médias et objets liés<ChevronRight/></button><button onClick={()=>{setSheet(null);setSearching(true)}}><Search/>Rechercher dans la discussion</button></>}</div></section></div>}</article>;
}
