'use client';
import {useRef,useState} from 'react';
import {X,ArrowRight,ArrowLeft,HardHat,MapPin,Users,Clock3,CalendarDays,Info,UploadCloud,FileText,Check,Pencil} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription} from '../components/ui/alert-dialog';
import {saveJob,canReview,duration,type JobRecord,type Actor,type TimeData} from '../lib/time-domain';
import {validateJobStep} from '../lib/job-form-validation';
import {jobHours} from '../lib/job-view';
import {changeTimeDemo} from '../lib/time-demo';
import './job-form.css';
import {JobPhotoEditor} from './job-photo-editor';

const steps=['Général','Adresse','Planification','Équipe','Détails','Documents / photo','Résumé'];
const titles=['Informations générales','Adresse du chantier','Planification','Équipe et assignations','Consignes du chantier','Documents initiaux','Vérifier avant de créer'];
const hints=['Commencez par les informations essentielles de votre chantier.','Une seule adresse pour le dossier et les équipes.','Définissez les dates prévues et les heures estimées.','Choisissez les personnes assignées à cette Job.','Ajoutez les informations utiles à l’équipe sur le terrain.','Plans, documents et photos avant travaux.','Vérifiez les informations avant de confirmer.'];
type FieldKey='number'|'name'|'client'|'contractor'|'phone'|'address'|'unit'|'city'|'province'|'postal_code'|'planned_start'|'planned_end'|'planned_delivery'|'estimated_hours';
export function JobForm({actor,data,initial,onClose,onSaved}:{actor:Actor;data:TimeData;initial?:JobRecord;onClose:()=>void;onSaved:(id:string)=>void}){
 const [job,setJob]=useState<JobRecord>(()=>initial?structuredClone(initial):{id:'',company_id:actor.companyId,number:'',name:'',members:[],status:'Planifiée',province:'Québec'});
 const original=useRef(JSON.stringify(job)),saving=useRef(false),finalId=useRef(initial?.id||'');
 const [step,setStep]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmClose,setConfirmClose]=useState(false),[memberQuery,setMemberQuery]=useState('');
 const panel=useRef<HTMLDivElement>(null);
 const photoInput=useRef<HTMLInputElement>(null);
 const [photoBusy,setPhotoBusy]=useState(false);
 async function addPhoto(file?:File){
  if(!file)return;
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Choisissez une photo JPG, PNG ou WEBP.');return}
  if(file.size>10*1024*1024){setError('La photo doit faire au maximum 10 Mo.');return}
  setPhotoBusy(true);setError('');
  try{const bitmap=await createImageBitmap(file);const ratio=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));const context=canvas.getContext('2d');if(!context){bitmap.close();throw Error('Impossible de préparer la photo.')}context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const url=canvas.toDataURL('image/jpeg',.78);if(url.length>1500000)throw Error('Cette photo est trop volumineuse. Choisissez une image plus petite.');setJob(prev=>({...prev,cover_photo:url,cover_photo_name:file.name,cover_photo_crop:{x:50,y:50,zoom:1}}));}catch(e){setError(e instanceof Error?e.message:'Impossible de lire cette photo.')}finally{setPhotoBusy(false);if(photoInput.current)photoInput.current.value=''}
 }
 const employees=data.employees.filter(e=>e.company_id===actor.companyId&&e.user_id),teams=(data.teams||[]).filter(t=>t.company_id===actor.companyId);
 const leader=employees.find(e=>e.id===job.lead_id),team=teams.find(t=>t.id===job.team_id);
 const [addingContact,setAddingContact]=useState<'client'|'contractor'|null>(null),[contactName,setContactName]=useState('');
 const [newContacts,setNewContacts]=useState<string[]>([]);
 const normalizeContact=(name:string)=>name.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('fr').replace(/[^a-z0-9]/g,'');
 const contactNames=[...data.jobs.filter(j=>j.company_id===actor.companyId).flatMap(j=>[j.client,j.contractor]),...newContacts,job.client,job.contractor].filter((s):s is string=>!!s?.trim());
 const clients=[...new Map(contactNames.map(name=>[normalizeContact(name),name.trim()])).values()].sort((a,b)=>a.localeCompare(b,'fr'));
 function addContact(){const name=contactName.trim();if(!name||!addingContact)return;const existing=clients.find(c=>normalizeContact(c)===normalizeContact(name));const selected=existing||name;if(!existing)setNewContacts(prev=>[...prev,selected]);change(addingContact,selected);setAddingContact(null);setContactName('');}
 const contactSelect=(key:'client'|'contractor',label:string)=><label className="jw-field"><span>{label}{key==='client'&&<em> *</em>}</span><select aria-label={label} value={job[key]||''} onChange={e=>{if(e.target.value==='__add_contact__'){setAddingContact(key);setContactName('')}else change(key,e.target.value)}}><option value="">{key==='client'?'Choisir un client':'Même que le client'}</option>{clients.map(name=><option key={name} value={name}>{name}</option>)}<option value="__add_contact__">+ Ajouter nouveau</option></select></label>;
 const address=[job.address,job.unit&&'Unité '+job.unit,job.city,job.province,job.postal_code].filter(Boolean).join(', ');
 const live=initial?jobHours(data)[initial.id]:undefined;
 const date=(value?:string)=>value?new Date(value+'T12:00:00').toLocaleDateString('fr-CA',{day:'numeric',month:'long',year:'numeric'}):'Non renseignée';
 const change=(key:keyof JobRecord,value:string|number|undefined)=>setJob(prev=>({...prev,[key]:value}));
 function requestClose(){if(saving.current)return;if(JSON.stringify(job)!==original.current)setConfirmClose(true);else onClose()}
 function move(next:number){setError('');setStep(next);panel.current?.scrollTo({top:0});}
 function goStep(next:number){if(busy)return;if(next>step){for(let i=0;i<next;i++){const message=validateJobStep(job,i,data,actor);if(message){setStep(i);setError(message);return}}}move(next)}
 async function submit(){
  if(saving.current||photoBusy)return;
  for(let i=0;i<=(step===6?5:step);i++){const message=validateJobStep(job,i,data,actor);if(message){setStep(i);setError(message);return}}
  if(step<6){move(step+1);return}
  saving.current=true;setBusy(true);setError('');
  try{
   if(!finalId.current)finalId.current=crypto.randomUUID();
   const value={...job,id:finalId.current};
   await changeTimeDemo(actor,d=>{for(let i=0;i<6;i++){const message=validateJobStep(value,i,d,actor);if(message)throw Error(message)}saveJob(d,actor,value)});
   onSaved(value.id);
  }catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible.')}finally{saving.current=false;setBusy(false)}
 }
 const field=(key:FieldKey,label:string,type='text',required=false,placeholder='',list?:string)=><label className="jw-field" key={key}><span>{label}{required&&<em aria-hidden="true"> *</em>}</span><input type={type} required={required} list={list} placeholder={placeholder} min={type==='number'?0:undefined} step={type==='number'?'any':undefined} value={job[key]??''} onChange={e=>change(key,type==='number'?(e.target.value===''?undefined:Number(e.target.value)):e.target.value)}/></label>;
 const textArea=(key:'description'|'planning_notes'|'site_instructions',label:string,placeholder='')=><label className="jw-field"><span>{label}</span><textarea rows={key==='site_instructions'?7:3} maxLength={key==='description'?500:undefined} value={job[key]||''} placeholder={placeholder} onChange={e=>change(key,e.target.value)}/>{key==='description'&&<small>{job.description?.length||0} / 500</small>}</label>;
 const summaries=[
  {title:'Général',values:[['Numéro',job.number],['Chantier',job.name],['Client',job.client],['Entrepreneur',job.contractor],['Téléphone',job.phone],['Type',job.project_type],['Description',job.description]]},
  {title:'Adresse',values:[['Adresse du chantier',address]]},
  {title:'Planification',values:[['Statut',job.status],['Début prévu',date(job.planned_start)],['Échéance prévue',date(job.planned_end)],['Livraison prévue',date(job.planned_delivery)],['Heures estimées',job.estimated_hours===undefined?'Non renseignées':job.estimated_hours+' h'],['Notes',job.planning_notes]]},
  {title:'Équipe',values:[['Chef',leader?.name||'À assigner'],['Équipe',team?.name||'Aucune'],['Employés',employees.filter(e=>job.members.includes(e.user_id)).map(e=>e.name).join(', ')||'Aucun']]},
  {title:'Détails',values:[['Consignes',job.site_instructions||'Aucune']]},
  {title:'Documents',values:[['Photo principale',job.cover_photo_name||'Aucune'],['Autres documents','Aucun document ajouté — service non relié']]}
 ];
 return <Dialog open onOpenChange={open=>{if(!open)requestClose()}}>
  <DialogContent className="jw-dialog" showCloseButton={false}>
   <header className="jw-header"><div><DialogTitle className="jw-title">{initial?'Modifier la Job':'Nouvelle Job'}</DialogTitle><DialogDescription className="jw-subtitle">{initial?'Mettre à jour le chantier':'Créer un nouveau chantier'}</DialogDescription></div><div className="jw-motto"><HardHat/><span>Des chantiers bien organisés.<br/>Des projets qui avancent.</span></div><button className="jw-close" type="button" disabled={busy} onClick={requestClose} aria-label="Fermer"><X/></button></header>
   <nav aria-label="Étapes de la Job" className="jw-stepper"><ol>{steps.map((label,i)=><li key={label} className={step===i?'is-current':i<step?'is-complete':''}><button type="button" aria-current={step===i?'step':undefined} disabled={busy} onClick={()=>goStep(i)}><span>{i<step?<Check/>:i+1}</span><b>{label}</b></button></li>)}</ol></nav>
   <div className="jw-layout"><form className="jw-form" noValidate onSubmit={e=>{e.preventDefault();void submit()}}>
    <div className="jw-fields-panel" ref={panel}><header><h2>{titles[step]}</h2><p>{hints[step]}</p></header><fieldset className="jw-fields" disabled={busy||!canReview(actor)}>
     {step===0&&<><div className="jw-grid">{field('number','Numéro de Job','text',true,'Ex. : JOB-521')}{field('name','Nom du chantier','text',true,'Ex. : Résidence Gagnon')}{contactSelect('client','Client')}{contactSelect('contractor','Entrepreneur (si différent)')}{field('phone','Téléphone','tel',false,'Ex. : 418 555-0123')}<label className="jw-field"><span>Type de projet<em> *</em></span><select value={job.project_type||''} required onChange={e=>change('project_type',e.target.value)}><option value="">Sélectionner un type</option>{['Résidentiel','Commercial','Industriel','Institutionnel','Autre'].map(v=><option key={v}>{v}</option>)}</select></label></div>{textArea('description','Description','Décrivez brièvement le chantier et les travaux à réaliser…')}<section className="jw-photo-section"><h3>Photo principale du chantier</h3><p>Une photo pour identifier facilement le chantier.</p><input ref={photoInput} type="file" accept="image/jpeg,image/png,image/webp" hidden aria-label="Choisir une photo du chantier" onChange={e=>void addPhoto(e.target.files?.[0])}/><button type="button" className="jw-photo-upload" disabled={photoBusy} onClick={()=>photoInput.current?.click()}><UploadCloud/><span>{photoBusy?'Préparation…':job.cover_photo?'Remplacer la photo':'Ajouter une photo'}<small>JPG, PNG, WEBP · maximum 10 Mo</small></span></button>{job.cover_photo&&<div className="jw-photo-selected"><span>{job.cover_photo_name||'Photo sélectionnée'}</span><button type="button" onClick={()=>setJob(prev=>({...prev,cover_photo:undefined,cover_photo_name:undefined}))}>Retirer</button></div>}</section></>}
     {step===1&&<div className="jw-grid">{field('address','Adresse','text',true,'Numéro et rue')}{field('unit','Unité / suite')}{field('city','Ville','text',true)}{field('province','Province','text',true)}{field('postal_code','Code postal','text',true,'G1A 1A1')}<p className="jw-muted">Les coordonnées GPS ne sont pas encore reliées à ce formulaire.</p></div>}
     {step===2&&<><div className="jw-grid">{field('planned_start','Date de début prévue','date')}{field('planned_end','Échéance prévue','date')}{field('planned_delivery','Livraison prévue','date')}{field('estimated_hours','Heures estimées','number',false,'Ex. : 410')}<label className="jw-field"><span>Statut initial</span><select value={job.status||'Planifiée'} onChange={e=>change('status',e.target.value)}>{['Planifiée','Active','En attente','Terminée'].map(v=><option key={v}>{v}</option>)}</select></label></div>{textArea('planning_notes','Notes de planification','Contraintes de calendrier, séquence des travaux…')}</>}
     {step===3&&<><div className="jw-grid"><label className="jw-field"><span>Équipe</span><select value={job.team_id||''} onChange={e=>{const t=teams.find(t=>t.id===e.target.value);const members=t?employees.filter(p=>t.member_ids.includes(p.id)||p.id===t.lead_id).map(p=>p.user_id):[];setJob(prev=>({...prev,team_id:e.target.value,lead_id:t?.lead_id||prev.lead_id,members:[...new Set([...prev.members,...members])]}))}}><option value="">Aucune équipe</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="jw-field"><span>Chef</span><select value={job.lead_id||''} onChange={e=>{const person=employees.find(p=>p.id===e.target.value);setJob(prev=>({...prev,lead_id:e.target.value,members:person?[...new Set([...prev.members,person.user_id])]:prev.members}))}}><option value="">Chef à assigner</option>{employees.filter(e=>e.role==='Chef').map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label></div><label className="jw-field"><span>Rechercher un employé</span><input value={memberQuery} onChange={e=>setMemberQuery(e.target.value)} placeholder="Nom de l’employé…"/></label><div className="jw-members"><h3>Employés assignés · {job.members.length}</h3>{employees.filter(e=>e.name.toLocaleLowerCase().includes(memberQuery.toLocaleLowerCase())).map(e=><label className="jw-member" key={e.id}><input type="checkbox" checked={job.members.includes(e.user_id)} onChange={event=>setJob(prev=>({...prev,members:event.target.checked?[...new Set([...prev.members,e.user_id])]:prev.members.filter(id=>id!==e.user_id),lead_id:!event.target.checked&&prev.lead_id===e.id?'':prev.lead_id}))}/><span>{e.name}<small>{e.role}</small></span></label>)}</div><p className="jw-muted">Seuls les employés avec un compte peuvent être assignés dans le registre actuel.</p></>}
     {step===4&&textArea('site_instructions','Consignes et demandes particulières','Accès au chantier, stationnement, consignes pour l’équipe…')}
     {step===5&&<div className="jw-documents"><FileText/><h3>Documents et photos du chantier</h3><p>Le service de fichiers n’est pas encore relié. Vous pouvez créer le chantier sans pièces jointes.</p><div><button type="button" disabled>Ajouter un plan</button><button type="button" disabled>Ajouter un document</button><button type="button" disabled>Photo avant travaux</button></div></div>}
     {step===6&&<div className="jw-summary">{summaries.map((section,i)=><section key={section.title}><header><h3>{section.title}</h3><button type="button" onClick={()=>move(i)}><Pencil/>Modifier</button></header><dl>{section.values.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Non renseigné'}</dd></div>)}</dl></section>)}</div>}
    </fieldset></div>
    {error&&<p className="jw-error" role="alert">{error}</p>}
    <footer className="jw-footer"><button type="button" disabled={busy} onClick={()=>step?move(step-1):requestClose()}>{step?<ArrowLeft/>:<X/>}{step?'Précédent':'Annuler'}</button><span>Étape {step+1} sur 7</span><button className="jw-primary" disabled={busy||photoBusy||!canReview(actor)} type="submit">{busy?'Enregistrement…':step===6?(initial?'Enregistrer':'Créer la Job'):'Suivant'}<ArrowRight/></button></footer>
   </form>
   <aside className="jw-preview"><h2>Aperçu de la Job</h2><p>Voici un aperçu de la carte telle qu’elle apparaîtra.</p><article className="jw-preview-card"><div className="jw-preview-photo">{job.cover_photo?<JobPhotoEditor job={job} onChange={crop=>setJob(prev=>({...prev,cover_photo_crop:crop}))}/>:<HardHat/>}<span className="jw-preview-status">{step<2&&!initial?'Brouillon':job.status||'Planifiée'}</span>{!job.cover_photo&&<small>Photo à ajouter</small>}</div><div className="jw-preview-body"><small>{job.number||'Numéro à définir'}</small><h3>{job.name||'Nom du chantier'}</h3><p><MapPin/><span>{job.address?address:'Adresse à venir'}</span></p><div className="jw-preview-progress"><span/><small>{initial?'Progression non renseignée':'0 %'}</small></div><p><HardHat/><span>Client : {job.client||'À préciser'}</span></p>{job.project_type&&<p><FileText/><span>{job.project_type}</span></p>}<p><Users/><span>Chef : {leader?.name||'À assigner'}</span></p><p><Users/><span>{job.members.length} membre{job.members.length!==1?'s':''} assigné{job.members.length!==1?'s':''}</span></p><p><Clock3/><span>Aujourd’hui : {duration(live?.today||0)}</span></p><p><Clock3/><span>En cours : {live?.employees.size||0} emp. · {duration(live?.live||0)}</span></p>{job.estimated_hours!==undefined&&<p><Clock3/><span>Estimées : {job.estimated_hours} h</span></p>}<p><CalendarDays/><span>{job.planned_end?'Échéance : '+date(job.planned_end):job.planned_delivery?'Livraison : '+date(job.planned_delivery):'Échéance à définir'}</span></p>{step===6&&<div className="jw-ready"><Check/>{initial?'Prêt à enregistrer':'Prêt à créer'}</div>}</div></article><p className="jw-preview-info"><Info/><span>Cet aperçu suit votre saisie. Rien n’est enregistré avant la confirmation finale.</span></p></aside>
   </div>
   <Dialog open={addingContact!==null} onOpenChange={open=>{if(!open)setAddingContact(null)}}><DialogContent className="jw-contact-dialog" showCloseButton={false}><DialogTitle>Ajouter un {addingContact==='contractor'?'entrepreneur':'client'}</DialogTitle><DialogDescription>Il sera conservé avec la Job et proposé dans les prochaines Jobs enregistrées.</DialogDescription><label className="jw-field"><span>Nom de l’entreprise</span><input value={contactName} onChange={e=>setContactName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addContact()}}} placeholder="Ex. : Construction Gagnon"/></label><div><button type="button" onClick={()=>setAddingContact(null)}>Annuler</button><button type="button" disabled={!contactName.trim()} onClick={addContact}>Ajouter et sélectionner</button></div></DialogContent></Dialog>
   <AlertDialog open={confirmClose} onOpenChange={setConfirmClose}><AlertDialogContent className="jw-confirm"><AlertDialogTitle>Quitter {initial?'la modification':'la création'} ?</AlertDialogTitle><AlertDialogDescription>Les informations non enregistrées seront perdues.</AlertDialogDescription><div><button onClick={()=>setConfirmClose(false)}>Continuer la saisie</button><button onClick={onClose}>Quitter</button></div></AlertDialogContent></AlertDialog>
  </DialogContent>
 </Dialog>;
}
