'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Check, ChevronLeft, ChevronRight, Clock3, History, Plus, X } from 'lucide-react';
import { addDays, dateKey, duration, employeeId, localInstant, requestCorrection, submitWeek, timeLabel, totals, weekOf, weekStatus, type Actor, type Correction, type Proposal, type Segment, type TimeData } from '../lib/time-domain';
import { changeTimeDemo } from '../lib/time-demo';
import { useTimeData } from './use-time-data';
import './my-hours.css';

export const periodLabel=(week:string)=>`${new Date(`${week}T12:00:00`).toLocaleDateString('fr-CA',{day:'numeric',month:'long'})} au ${new Date(`${addDays(week,6)}T12:00:00`).toLocaleDateString('fr-CA',{day:'numeric',month:'long',year:'numeric'})}`;
export function Status({value}:{value:string}){return <span className={`mh-status ${value.includes('attente')||value==='À confirmer'?'pending':value==='Refusée'?'rejected':value==='Approuvée'?'approved':''}`}>{value}</span>;}
export function Breakdown({value}:{value:{gross:number;deduction:number;payable:number}}){return <dl className="mh-breakdown"><div><dt>Brut</dt><dd>{duration(value.gross)}</dd></div><div><dt>Déduction automatique</dt><dd>− {duration(value.deduction)}</dd></div><div><dt>Payable</dt><dd>{duration(value.payable)}</dd></div></dl>;}
export function CorrectionForm({data,segment,initial,day,onSubmit,onCancel,label='Envoyer la demande'}:{data:TimeData;segment?:Segment|null;initial?:Proposal;day:string;onSubmit:(p:Proposal,reason:string,note:string)=>Promise<void>;onCancel:()=>void;label?:string}){
 const proposal=initial||(segment?.end_time?{job_id:segment.job_id,start_time:segment.start_time,end_time:segment.end_time}:undefined);
 const [job,setJob]=useState(proposal?.job_id||data.jobs[0]?.id||''),[start,setStart]=useState(proposal?timeLabel(proposal.start_time,data.settings.timezone):'07:00'),[end,setEnd]=useState(proposal?timeLabel(proposal.end_time,data.settings.timezone):'15:00'),[endDay,setEndDay]=useState(proposal?dateKey(proposal.end_time,data.settings.timezone):day),[reason,setReason]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const ref=useRef<HTMLSelectElement>(null);useEffect(()=>ref.current?.focus(),[]);
 return <form className="mh-form" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);try{await onSubmit({job_id:job,start_time:localInstant(day,start,data.settings.timezone),end_time:localInstant(endDay,end,data.settings.timezone)},reason,note);}catch(e){setError(e instanceof Error?e.message:'Envoi impossible. Réessayez.');}finally{setBusy(false);}}}>
 <p>{segment?'Proposez une correction du segment sélectionné.':'L’ajout sera officiel après approbation.'}</p>
 <label>Job<select ref={ref} value={job} onChange={e=>setJob(e.target.value)} required>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.number} — {j.name}</option>)}</select></label>
 <div className="mh-form-pair"><label>Heure de début<input type="time" value={start} onChange={e=>setStart(e.target.value)} required/></label><label>Heure de fin<input type="time" value={end} onChange={e=>setEnd(e.target.value)} required/></label></div>
 <label>Date de fin<input type="date" min={day} max={addDays(day,1)} value={endDay} onChange={e=>setEndDay(e.target.value)} required/></label>
 <label>Raison obligatoire<select value={reason} onChange={e=>setReason(e.target.value)} required><option value="">Choisir une raison</option>{['Oubli de Punch','Heure de début incorrecte','Sortie plus tardive','Mauvaise Job','Autre correction'].map(r=><option key={r}>{r}</option>)}</select></label>
 <label>Note facultative<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000}/></label>
 {segment&&<div className="mh-original"><span>VALEUR ORIGINALE</span><b>{timeLabel(segment.start_time,data.settings.timezone)} → {segment.end_time?timeLabel(segment.end_time,data.settings.timezone):'En cours'}</b><small>{data.jobs.find(j=>j.id===segment.job_id)?.number}</small></div>}
 {error&&<p className="mh-error" role="alert">{error}</p>}<button className="mh-primary" disabled={busy||!job}>{busy?'Envoi…':label}</button><button type="button" onClick={onCancel} disabled={busy}>Annuler</button>
 </form>;
}
export function MyHours({actor}:{actor:Actor}){
 const data=useTimeData(actor.companyId);const [week,setWeek]=useState(''),[selected,setSelected]=useState<string|null>(null),[screen,setScreen]=useState<'detail'|'edit'|'sent'>('detail'),[editId,setEditId]=useState<string|null>(null),[sentId,setSentId]=useState<string|null>(null),[history,setHistory]=useState(false),[picker,setPicker]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const heading=useRef<HTMLHeadingElement>(null);
 const today=data?dateKey(new Date(),data.settings.timezone):'',current=data?weekOf(today,data.settings.weekStartsOn):'';
 useEffect(()=>{if(current&&!week)setWeek(current);},[current,week]);
 useEffect(()=>{if(selected)heading.current?.focus();},[selected,screen]);
 useEffect(()=>{if(!data)return;const sync=()=>{const requestId=window.location.hash.split('/request/')[1];if(requestId){const c=data.corrections.find(c=>c.id===requestId&&c.employee_id===employeeId(actor));const s=data.submissions.find(s=>s.id===requestId&&s.employee_id===employeeId(actor));if(c){const day=dateKey(c.original?.start_time||c.proposed.start_time,data.settings.timezone);setWeek(weekOf(day,data.settings.weekStartsOn));setSelected(day);setSentId(c.id);setScreen('sent');}else if(s){setWeek(s.week);setSelected(null);}}};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[data,actor.email,actor.companyId]);
 if(!data||!week)return <p role="status">Chargement des heures…</p>;
 const id=employeeId(actor),own=data.segments.filter(s=>s.employee_id===id&&s.company_id===actor.companyId),allTotals=totals(own,data.settings),rows=own.filter(s=>dateKey(s.start_time,data.settings.timezone)>=week&&dateKey(s.start_time,data.settings.timezone)<addDays(week,7));
 const sum=(list:Segment[])=>list.reduce((a,s)=>{const b=allTotals.byId[s.id];return {gross:a.gross+b.gross,deduction:a.deduction+b.deduction,payable:a.payable+b.payable};},{gross:0,deduction:0,payable:0});
 const days=Array.from({length:7},(_,i)=>addDays(week,i)),dayRows=own.filter(s=>dateKey(s.start_time,data.settings.timezone)===selected).sort((a,b)=>a.start_time.localeCompare(b.start_time)),status=weekStatus(data,id,week),submission=data.submissions.find(s=>s.employee_id===id&&s.week===week),baseDayStatus=submission?({submitted:'Soumise',approved:'Approuvée',rejected:'Refusée'}[submission.status]):'À confirmer',editing=data.segments.find(s=>s.id===editId),sent=data.corrections.find(c=>c.id===sentId);
 const allowed={...data,jobs:data.jobs.filter(j=>j.company_id===actor.companyId&&j.members.includes(actor.email))};
 const pending=(s:Segment)=>data.corrections.some(c=>c.original_segment_id===s.id&&c.status==='pending');
 const close=()=>{setSelected(null);setScreen('detail');setError('');if(window.location.hash.includes('/request/'))window.location.hash='field/hours';};
 const moveWeek=(next:string)=>{setWeek(weekOf(next,data.settings.weekStartsOn));close();setPicker(false);setHistory(false);};
 const request=async(p:Proposal,reason:string,note:string)=>{let result:Correction|undefined;await changeTimeDemo(actor,d=>{result=requestCorrection(d,actor,editId,p,reason,note)});setSentId(result!.id);setScreen('sent');};
 const editable=dayRows.filter(s=>s.end_time&&!pending(s));
 return <section className={`my-hours ${selected?'has-detail':''}`}>
 <div className="mh-week"><header className="mh-heading"><div><span className="mh-eyebrow">TEMPS DE TRAVAIL</span><h1>{history?'Historique des semaines':'Mes heures'}</h1><p>{periodLabel(week)}</p></div><button className="mh-history" onClick={()=>{close();setHistory(!history)}}><History/>{history?'Retour à la semaine':'Voir l’historique'}</button></header>
 <div className="mh-week-picker"><button aria-label="Semaine précédente" onClick={()=>moveWeek(addDays(week,-7))}><ChevronLeft/></button><button aria-expanded={picker} onClick={()=>setPicker(!picker)}>{periodLabel(week)}</button><button aria-label="Semaine suivante" onClick={()=>moveWeek(addDays(week,7))}><ChevronRight/></button>{picker&&<div className="mh-date-picker"><label>Choisir une date dans la semaine<input type="date" value={week} onChange={e=>e.target.value&&moveWeek(e.target.value)}/></label><button onClick={()=>moveWeek(current)}>Semaine actuelle</button></div>}</div>
 {history?<div className="mh-history-list">{[...new Set([...own.map(s=>weekOf(dateKey(s.start_time,data.settings.timezone),data.settings.weekStartsOn)),...data.submissions.filter(s=>s.employee_id===id).map(s=>s.week)])].sort().reverse().map(w=><button key={w} onClick={()=>moveWeek(w)}><span>{periodLabel(w)}<b>{duration(sum(own.filter(s=>dateKey(s.start_time,data.settings.timezone)>=w&&dateKey(s.start_time,data.settings.timezone)<addDays(w,7))).payable)}</b></span><Status value={weekStatus(data,id,w)}/><ChevronRight/></button>)}</div>:<>
 <div className="mh-summary"><div><span>Total semaine</span><strong>{duration(sum(rows).payable)}</strong></div><div><span>Statut</span><Status value={status}/></div><button className="mh-primary" disabled={busy||!rows.length||rows.some(s=>!s.end_time)||!['À confirmer','Refusée'].includes(status)} onClick={async()=>{setBusy(true);setError('');try{await changeTimeDemo(actor,d=>submitWeek(d,actor,week));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Check/>{busy?'Envoi…':'Confirmer mes heures'}</button></div>
 {error&&<p role="alert" className="mh-error">{error}</p>}
 <div className="mh-days">{days.map(day=>{const list=rows.filter(s=>dateKey(s.start_time,data.settings.timezone)===day),jobs=[...new Set(list.map(s=>s.job_id))],dayPending=data.corrections.some(c=>c.employee_id===id&&c.status==='pending'&&dateKey(c.proposed.start_time,data.settings.timezone)===day);return <button key={day} aria-pressed={selected===day} className={selected===day?'selected':''} onClick={()=>{setSelected(day);setScreen('detail');}}><span>{new Date(`${day}T12:00:00`).toLocaleDateString('fr-CA',{weekday:'short',day:'numeric'})}</span><b>{list.length?duration(sum(list).payable):'—'}</b><small>{jobs.length>1?`${jobs.length} Jobs`:data.jobs.find(j=>j.id===jobs[0])?.number||'Aucune heure'}</small><Status value={dayPending?'Modification en attente':list.some(s=>!s.end_time)?'En cours':list.length?baseDayStatus:'Aucune heure'}/></button>})}</div>
 <section className="mh-chart"><h2>Aperçu de la semaine</h2><div>{days.map(day=>{const value=sum(rows.filter(s=>dateKey(s.start_time,data.settings.timezone)===day)).payable;return <div key={day}><small>{duration(value)}</small><i style={{height:`${Math.max(2,Math.min(140,value/5))}px`}}/><span>{new Date(`${day}T12:00:00`).toLocaleDateString('fr-CA',{weekday:'short'})}</span></div>})}</div></section>
 <p className="mh-rule"><Clock3/>Déduction de {data.settings.deduction} min pour un quart de {duration(data.settings.minimum)} à {duration(data.settings.maximum)}. Les heures pointées sont conservées.</p>
 </>}
 <small className="mh-demo">Mode Démo · données partagées entre les rôles sur ce navigateur.</small></div>
 {selected&&<aside className="mh-detail" onKeyDown={e=>{if(e.key==='Escape')close();}}><header><button aria-label="Retour à la semaine" onClick={close}><ArrowLeft/></button><h2 ref={heading} tabIndex={-1}>{screen==='edit'?'Modifier ma journée':screen==='sent'?'Demande envoyée':new Date(`${selected}T12:00:00`).toLocaleDateString('fr-CA',{weekday:'long',day:'numeric',month:'long'})}</h2><button aria-label="Fermer le détail" onClick={close}><X/></button></header>
 {screen==='detail'&&<><div className="mh-day-total"><span>Total de la journée</span><strong>{duration(sum(dayRows).payable)}</strong><Status value={status}/></div><Breakdown value={sum(dayRows)}/><h3>Segments de travail</h3><div className="mh-segments">{dayRows.map(s=><article key={s.id}><span className="mh-dot"/><div><b>{timeLabel(s.start_time,data.settings.timezone)} → {s.end_time?timeLabel(s.end_time,data.settings.timezone):'En cours'}</b><small>{data.jobs.find(j=>j.id===s.job_id)?.number} — {data.jobs.find(j=>j.id===s.job_id)?.name}</small>{s.gps_context&&<small>{s.gps_context}</small>}<span>{duration(allTotals.byId[s.id].payable)}</span>{pending(s)&&<Status value="Modification en attente"/>}</div><button disabled={!s.end_time||pending(s)} onClick={()=>{setEditId(s.id);setScreen('edit')}} aria-label={`Modifier le segment de ${timeLabel(s.start_time,data.settings.timezone)}`}><ChevronRight/></button></article>)}</div>{!dayRows.length&&<p>Aucun segment pour cette journée.</p>}
 {data.corrections.filter(c=>c.employee_id===id&&dateKey(c.proposed.start_time,data.settings.timezone)===selected).map(c=><button className="mh-request-link" key={c.id} onClick={()=>{setSentId(c.id);setScreen('sent')}}>{c.original_segment_id?'Correction':'Segment oublié'} · {c.status==='pending'?'En attente':c.status==='approved'?'Approuvée':'Refusée'}<ChevronRight/></button>)}
 <button disabled={selected>today||!allowed.jobs.length} onClick={()=>{setEditId(null);setScreen('edit')}}><Plus/> Ajouter un segment oublié</button><button className="mh-primary" disabled={!editable.length} onClick={()=>{setEditId(editable[0].id);setScreen('edit')}}>Modifier cette journée</button></>}
 {screen==='edit'&&<>{editId&&editable.length>1&&<label>Segment à corriger<select value={editId} onChange={e=>setEditId(e.target.value)}>{editable.map(s=><option key={s.id} value={s.id}>{timeLabel(s.start_time,data.settings.timezone)} → {timeLabel(s.end_time!,data.settings.timezone)}</option>)}</select></label>}<CorrectionForm key={editId||'new'} data={allowed} segment={editing} day={selected} onSubmit={request} onCancel={()=>setScreen('detail')}/></>}
 {screen==='sent'&&sent&&<><Status value={sent.status==='pending'?'Modification en attente':sent.status==='approved'?'Approuvée':'Refusée'}/><p>{sent.status==='pending'?'Le Boss et l’Adjointe ont été notifiés. Les heures officielles restent inchangées en attendant la décision.':`Demande traitée par ${sent.reviewed_by_user_id}.`}</p><div className="mh-comparison"><article><span>VALEUR ORIGINALE</span><b>{sent.original?`${timeLabel(sent.original.start_time,data.settings.timezone)} → ${timeLabel(sent.original.end_time!,data.settings.timezone)}`:'Segment oublié'}</b><small>{data.jobs.find(j=>j.id===sent.original?.job_id)?.number}</small></article><article><span>VALEUR PROPOSÉE</span><b>{timeLabel(sent.proposed.start_time,data.settings.timezone)} → {timeLabel(sent.proposed.end_time,data.settings.timezone)}</b><small>{data.jobs.find(j=>j.id===sent.proposed.job_id)?.number}</small></article></div><h3>{sent.reason}</h3><p>{sent.note}</p>{sent.reviewer_note&&<p>Note de révision : {sent.reviewer_note}</p>}<button className="mh-primary" onClick={close}>Retour à mes heures</button></>}
 </aside>}
 </section>;
}
