'use client';
import {useEffect,useState} from 'react';
import {Plus,Search,PackageCheck} from 'lucide-react';
import type {ForgeSession} from './forge-access';
type StoredOrder={id:string;companyId:string;job:string;job_id?:string;requester:string;requested_by_user_id?:string;date:string;status:string;items:{name:string;qty:number;unit:string;detail?:string}[]};
export function MyOrders({session,onNew}:{session:ForgeSession;onNew:()=>void}){
 const [orders,setOrders]=useState<StoredOrder[]>([]),[query,setQuery]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const key=`forge:${session.companyId}:orders`;const load=()=>{try{const stored=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(stored))throw Error();setOrders(stored.filter((o:StoredOrder)=>o.companyId===session.companyId&&(o.requested_by_user_id?o.requested_by_user_id===session.email:o.requester===session.userName)));setError('')}catch{setOrders([]);setError('Impossible de charger les commandes enregistrées.')}};load();const storage=(e:StorageEvent)=>{if(e.key===key||e.key===null)load()};window.addEventListener('forge-orders-updated',load);window.addEventListener('storage',storage);return()=>{window.removeEventListener('forge-orders-updated',load);window.removeEventListener('storage',storage)}},[session.companyId,session.email,session.userName]);
 const visible=orders.filter(o=>`${o.id} ${o.job} ${o.status}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <section id="orders" className="my-orders"><header><h1>Mes commandes</h1><button onClick={onNew}><Plus/> Nouvelle commande</button></header><p className="my-orders-note">Aperçu local · commandes non transmises aux employés</p><label className="my-orders-search"><Search/><input aria-label="Rechercher mes commandes" placeholder="Numéro, chantier ou statut…" value={query} onChange={e=>setQuery(e.target.value)}/></label><h2>Historique · {visible.length}</h2>{error&&<p role="alert">{error}</p>}{visible.map(o=><details className="my-order" key={o.id}><summary><span><b>{o.id}</b><strong>{o.job}</strong><small>{o.date} · {o.items.length} article{o.items.length>1?'s':''}</small></span><em>{o.status}</em></summary><ul>{o.items.map((item,i)=><li key={i}><b>{item.name}</b><span>{item.qty} {item.unit}</span>{item.detail&&<small>{item.detail}</small>}</li>)}</ul></details>)}{!error&&!visible.length&&<div className="my-orders-empty"><PackageCheck/><p>{query?'Aucune commande correspondante.':'Tes commandes apparaîtront ici après leur enregistrement.'}</p></div>}</section>;
}
