'use client';
import {useEffect,useState,useRef} from 'react';
import {Plus,Search,PackageCheck} from 'lucide-react';
import type {ForgeSession} from './forge-access';
import {OrderDetailOverlay} from './order-detail-overlay';
type StoredOrder={id:string;sequence?:number;companyId:string;job:string;job_id?:string;requester:string;requested_by_user_id?:string;date:string;status:string;items:{name:string;qty:number;unit:string;detail?:string}[]};
export function MyOrders({session,onNew,drafts,onResume,onDeleteDraft}:{session:ForgeSession;onNew:()=>void;drafts:{id:string;count:number;job:string}[];onResume:(id:string)=>void;onDeleteDraft:(id:string)=>void}){
 const [orders,setOrders]=useState<StoredOrder[]>([]),[query,setQuery]=useState(''),[error,setError]=useState('');
 const root=useRef<HTMLElement>(null);
 const [sort,setSort]=useState<'newest'|'oldest'|'job'>('newest');
 useEffect(()=>{
  const workspace=root.current?.closest<HTMLElement>('.workspace');
  const header=workspace?.querySelector<HTMLElement>('.shared-mobile-head')||workspace?.querySelector<HTMLElement>('.topbar');
  const content=root.current?.parentElement;
  if(!workspace||!header||!content)return;
  const measure=()=>content.style.setProperty('--orders-header-height',`${header.offsetTop+header.offsetHeight}px`);
  measure();const observer=new ResizeObserver(measure);observer.observe(workspace);observer.observe(header);
  return()=>{observer.disconnect();content.style.removeProperty('--orders-header-height')};
 },[]);
 const [confirmDelete,setConfirmDelete]=useState<string|null>(null);
 const [opened,setOpened]=useState<{order:StoredOrder;trigger:HTMLButtonElement}|null>(null);
 useEffect(()=>{const key=`forge:${session.companyId}:orders`;const load=()=>{try{const stored=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(stored))throw Error();const counts=new Map<string,number>();const numbered=[...stored].reverse().map((o:StoredOrder)=>{const job=o.job_id||o.job;const sequence=(counts.get(job)||0)+1;counts.set(job,sequence);return {...o,sequence}}).reverse();setOrders(numbered.filter((o:StoredOrder)=>o.companyId===session.companyId&&(o.requested_by_user_id?o.requested_by_user_id===session.email:o.requester===session.userName)));setError('')}catch{setOrders([]);setError('Impossible de charger les commandes enregistrées.')}};load();const storage=(e:StorageEvent)=>{if(e.key===key||e.key===null)load()};window.addEventListener('forge-orders-updated',load);window.addEventListener('storage',storage);return()=>{window.removeEventListener('forge-orders-updated',load);window.removeEventListener('storage',storage)}},[session.companyId,session.email,session.userName]);
 const visible=orders.filter(o=>`${o.id} Commande ${o.sequence} ${o.job} ${o.status}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>sort==='job'?a.job.localeCompare(b.job,'fr',{numeric:true})||(b.sequence||0)-(a.sequence||0):sort==='oldest'?a.date.localeCompare(b.date)||orders.indexOf(b)-orders.indexOf(a):b.date.localeCompare(a.date)||orders.indexOf(a)-orders.indexOf(b));
 return <section ref={root} id="orders" className="my-orders"><header><h1>Mes commandes</h1><button onClick={onNew}><Plus/> Nouvelle commande</button></header>{drafts.map(draft=><section key={draft.id} className="my-order-draft" aria-label="Commande en cours"><div><b>Commande en cours</b><small>{draft.job||'Chantier à choisir'} · {draft.count} article{draft.count>1?'s':''}</small></div>{confirmDelete===draft.id?<><p>Supprimer ce brouillon et son panier?</p><div className="draft-actions"><button type="button" onClick={()=>setConfirmDelete(null)}>Annuler</button><button type="button" onClick={()=>{onDeleteDraft(draft.id);setConfirmDelete(null)}}>Confirmer la suppression</button></div></>:<div className="draft-actions"><button type="button" onClick={()=>onResume(draft.id)}>Reprendre</button><button type="button" onClick={()=>setConfirmDelete(draft.id)}>Supprimer</button></div>}</section>)}<p className="my-orders-note">Aperçu local · commandes non transmises aux employés</p><label className="my-orders-search"><Search/><input aria-label="Rechercher mes commandes" placeholder="Numéro, chantier ou statut…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="my-orders-sort" aria-label="Trier les commandes"><span>Trier par</span><button type="button" aria-label={sort==='job'?'Tri par chantier. Passer au tri par date':'Tri par date. Passer au tri par chantier'} onClick={()=>setSort(sort==='job'?'newest':'job')}>{sort==='job'?'Chantier':'Date ↓'} <span aria-hidden="true">⇄</span></button></div><h2>Historique · {visible.length}</h2>{error&&<p role="alert">{error}</p>}{visible.map(o=><button type="button" className="my-order my-order-open" key={o.id} onClick={event=>setOpened({order:o,trigger:event.currentTarget})}><span className="my-order-summary"><span><b className="order-job-title">{o.job}</b><strong className="order-sequence-label">Commande {o.sequence}</strong><small>{o.date} · {o.items.length} article{o.items.length>1?'s':''}</small></span><em>{o.status}</em></span></button>)}{!error&&!visible.length&&<div className="my-orders-empty"><PackageCheck/><p>{query?'Aucune commande correspondante.':'Tes commandes apparaîtront ici après leur enregistrement.'}</p></div>}{opened&&<OrderDetailOverlay order={opened.order} trigger={opened.trigger} onClose={()=>setOpened(null)}/>}</section>;
}
