'use client';
import {useEffect,useState} from 'react';
import {ClipboardList,Clock3,HardHat,Search,ChevronRight,BookOpen} from 'lucide-react';
import {useTimeData} from './use-time-data';
import type {ForgeSession} from './forge-access';
type Order={id:string;companyId:string;job:string;requester:string;date:string;status:string;priority?:string;items:unknown[]};
export function OperationsHome({session,go}:{session:ForgeSession;go:(route:string)=>void}){
 const time=useTimeData(session.companyId),[orders,setOrders]=useState<Order[]>([]),[query,setQuery]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const load=()=>{try{const raw=JSON.parse(localStorage.getItem(`forge:${session.companyId}:orders`)||'[]');if(!Array.isArray(raw))throw Error();setOrders(raw.filter((o:Order)=>o.companyId===session.companyId));setError('')}catch{setError('Impossible de lire les commandes locales. Aucune donnée n’a été remplacée.')}};load();window.addEventListener('forge-orders-updated',load);window.addEventListener('storage',load);return()=>{window.removeEventListener('forge-orders-updated',load);window.removeEventListener('storage',load)}},[session.companyId]);
 const pending=orders.filter(o=>['Reçue','À traiter'].includes(o.status));
 const corrections=time?.corrections.filter(c=>c.status==='pending')||[];
 const weeks=time?.submissions.filter(s=>s.status==='submitted')||[];
 const matches=(text:string)=>text.toLocaleLowerCase('fr-CA').includes(query.toLocaleLowerCase('fr-CA'));
 const tasks=[...pending.map(o=>({id:o.id,title:o.job,detail:`Commande · ${o.requester}`,status:o.priority==='Urgente'?'Urgente':o.status,route:`commands/received/${o.id}`})),...corrections.map(c=>({id:c.id,title:time?.employees.find(e=>e.id===c.employee_id)?.name||'Employé',detail:'Correction de Punch',status:'À examiner',route:`teams/corrections/${c.id}`}))].filter(t=>matches(t.title+' '+t.detail));
 return <div className="operations-home"><header><div><small>ESPACE ADJOINTE</small><h1>Centre des opérations</h1><p>Gestion quotidienne · {session.companyName}</p></div><button onClick={()=>go('commands/catalog')}><BookOpen size={18}/> Catalogue et pliages</button></header><p className="operations-mode">Démo locale · mêmes commandes et heures que les vues terrain. Aucun envoi externe.</p><label className="operations-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher dans les commandes, jobs et demandes affichées…"/></label>{error&&<p role="alert">{error}</p>}
 <div className="operations-kpis">{[{label:'Commandes à traiter',value:pending.length,route:'commands/received',icon:ClipboardList},{label:'Corrections à examiner',value:corrections.length,route:'teams/corrections',icon:Clock3},{label:'Semaines à approuver',value:weeks.length,route:'teams/corrections',icon:Clock3},{label:'Jobs du terrain',value:time?.jobs.length??'—',route:'jobs',icon:HardHat}].map(k=><button key={k.label} onClick={()=>go(k.route)}><k.icon/><span>{k.label}</span><b>{k.value}</b><ChevronRight size={16}/></button>)}</div>
 <div className="operations-columns"><section><h2>À traiter</h2>{tasks.length?tasks.map(t=><button className="operations-row" key={t.id} onClick={()=>go(t.route)}><span><b>{t.title}</b><small>{t.detail}</small></span><em>{t.status}</em><ChevronRight size={16}/></button>):<p>Aucune action correspondante dans les données disponibles.</p>}</section><section><h2>Approbations à examiner</h2>{weeks.map(w=><button className="operations-row" key={w.id} onClick={()=>go(`teams/corrections/${w.id}`)}><span><b>{time?.employees.find(e=>e.id===w.employee_id)?.name||'Employé'}</b><small>Semaine du {w.week}</small></span><span>Voir</span></button>)}{!weeks.length&&<p>Aucune semaine en attente.</p>}<p>Les demandes sont ouvertes avant toute décision.</p></section></div>
 <section><h2>Commandes récentes</h2>{orders.slice().sort((a,b)=>b.date.localeCompare(a.date)).filter(o=>matches(`${o.job} ${o.requester} ${o.id}`)).slice(0,15).map(o=><button className="operations-row" key={o.id} onClick={()=>go(`commands/received/${o.id}`)}><span><b>{o.job}</b><small>{o.requester} · {o.date} · {o.items.length} article(s)</small></span><em>{o.status}</em><ChevronRight size={16}/></button>)}{!orders.length&&<p>Les commandes créées par l’équipe apparaîtront ici.</p>}</section>
 <section><h2>Jobs et équipes</h2>{time?.jobs.filter(j=>matches(`${j.number} ${j.name}`)).map(j=><button className="operations-row" key={j.id} onClick={()=>go(`jobs/${j.id}/overview`)}><span><b>{j.number} · {j.name}</b><small>{j.members.length} membre(s) assigné(s)</small></span><ChevronRight size={16}/></button>)}</section><p className="operations-mode">Les indicateurs financiers, réceptions, outils et absences seront ajoutés lorsque leurs sources communes seront reliées. Aucun montant estimé n’est affiché.</p></div>;
}
