'use client';
import {useState} from 'react';
import {ArrowLeft,ChevronLeft,ChevronRight,Search,CalendarDays,Users,HardHat} from 'lucide-react';
import type {TimeData} from '../lib/time-domain';
export type FieldJob=TimeData['jobs'][number];
const sitePhoto='https://media.angi.com/s3fs-public/workers-working-framing-house-398986233.jpeg?impolicy=leadImage';
// Presentation metadata augments the existing Job identity; no second list is persisted.
function details(job:FieldJob){return job.number==='JOB-214'?{title:'Résidence Breton',city:'Québec',address:'1280, rue Industrielle, Québec',status:'En cours',progress:68}: {title:job.name,city:job.number==='JOB-418'?'Lévis':'Québec',address:job.number==='JOB-315'?'480, boulevard Leduc, Québec':job.number==='JOB-418'?'72, rue Bélanger, Lévis':'Adresse à confirmer',status:'Assigné',progress:null};}
export function ProjectsOverview({jobs,activeJob,onOpen}:{jobs:FieldJob[];activeJob:string;onOpen:(job:FieldJob)=>void}){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('Tous');const [page,setPage]=useState(0);
 const matches=jobs.filter(j=>{const d=details(j);return (filter==='Tous'||d.status===(filter==='Assignés'?'Assigné':filter))&&`${j.number} ${j.name} ${d.title} ${d.city}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase())}).sort((a,b)=>Number(b.number===activeJob)-Number(a.number===activeJob));
 const pages=Math.max(1,Math.ceil(matches.length/4));const current=Math.min(page,pages-1);
 return <section className="projects-overview"><header><span>Forge</span><h1>Projets</h1></header><label className="projects-search"><Search/><input aria-label="Rechercher un projet" placeholder="Rechercher un projet…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><div className="projects-filters" aria-label="Filtrer les projets">{['Tous','En cours','Assignés'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>{setFilter(f);setPage(0)}}>{f} ({jobs.filter(j=>f==='Tous'||details(j).status===(f==='Assignés'?'Assigné':f)).length})</button>)}</div><div className="projects-compact-list">{matches.slice(current*4,current*4+4).map(job=>{const d=details(job);return <button key={job.id} className={job.number===activeJob?'active':''} onClick={()=>onOpen(job)}><img src={sitePhoto} alt=""/><span><small>{job.number}</small><b>{d.title}</b><small>{d.city} · {d.status}</small></span><ChevronRight/></button>})}{!matches.length&&<p className="projects-empty">Aucun projet ne correspond à votre recherche.</p>}</div>{pages>1&&<nav className="projects-pages" aria-label="Autres projets"><button aria-label="Projets précédents" disabled={!current} onClick={()=>setPage(current-1)}><ChevronLeft/></button><span>{current+1} / {pages}</span><button aria-label="Projets suivants" disabled={current===pages-1} onClick={()=>setPage(current+1)}><ChevronRight/></button></nav>}</section>;
}
export function JobHero({job,onBack}:{job:FieldJob;onBack:()=>void}){const d=details(job);return <><section className="job-premium-hero" data-job-id={job.id}><img src={sitePhoto} alt="Chantier en construction"/><div className="job-hero-overlay"/><button className="job-hero-back" onClick={onBack}><ArrowLeft/> Projets</button><span className="job-hero-status">{d.status}</span><div className="job-hero-caption"><small>{job.number}</small><h1>{d.title}</h1><p>{d.address}</p></div></section>{d.progress!==null&&<div className="job-progress"><progress value={d.progress} max={100} aria-label="Progression du chantier"/><b>{d.progress} %</b></div>}<div className="job-facts"><article><CalendarDays/><span><b>{job.number==='JOB-214'?'18 août 2026':'À confirmer'}</b><small>Début</small></span></article><article><CalendarDays/><span><b>{job.number==='JOB-214'?'30 octobre 2026':'À confirmer'}</b><small>Livraison</small></span></article><article><HardHat/><span><b>{job.number==='JOB-214'?'Fred G.':'À confirmer'}</b><small>Chef d’équipe</small></span></article><article><Users/><span><b>{job.members.length}</b><small>Membres assignés</small></span></article></div></>}
