'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, Check, ChevronRight, Clipboard, Clock3, Folder, MapPin, Navigation, X } from 'lucide-react';

const jobs:Record<string,{name:string;address:string}>={
 'JOB-214':{name:'Breton',address:'1280, rue Industrielle, Québec'},'JOB-315':{name:'Leduc',address:'480, boulevard Leduc, Québec'},'JOB-418':{name:'Bélanger',address:'72, rue Bélanger, Lévis'}
};
const progressItems=[['Élévation droite',75],['Élévation arrière',25],['Élévation gauche',75],['Façade',100]] as const;

export function PunchPreview({role,punched,selectedJob,activeJob,startedAt,onJob,onToggle,onOpenJob,onHours,onSwitch,todayLabel,todaySegments}:{activeJob:string;onSwitch:()=>void;todayLabel:string;todaySegments:{id:string;job:string;start:string;end:string|null}[];role:'Chef'|'Employé';punched:boolean;selectedJob:string;startedAt:number|null;onJob:(v:string)=>void;onToggle:()=>void;onOpenJob:()=>void;onHours:()=>void}){
 const [now,setNow]=useState(0);const [reportOpen,setReportOpen]=useState(false);const [navigationOpen,setNavigationOpen]=useState(false);const [copied,setCopied]=useState(false);const [progress,setProgress]=useState<Record<string,number>>(()=>Object.fromEntries(progressItems));
 useEffect(()=>{if(!punched)return;const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[punched]);
 const elapsed=startedAt?Math.max(0,now-startedAt):0;const total=Math.floor(elapsed/1000);const timer=`${Math.floor(total/3600)} h ${String(Math.floor(total/60)%60).padStart(2,'0')} min ${String(total%60).padStart(2,'0')} s`;const job=jobs[selectedJob]||{name:'Chantier',address:'Adresse à confirmer'};
 const mapsUrl=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(job.address)}`;const wazeUrl=`https://www.waze.com/ul?q=${encodeURIComponent(job.address)}&navigate=yes`;
 const switching=punched&&selectedJob!==activeJob;const clock=(value:string)=>new Date(value).toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).replace(' h ',':');const uniqueJobs=[...new Set(todaySegments.map(s=>s.job))];const visibleSegments=todaySegments.slice(-3);
 const punch=()=>{if(switching)onSwitch();else if(role==='Chef'&&punched)setReportOpen(true);else onToggle()};
 return <div className="punch-redesign punch-v5">
  <header className="new-punch-title"><h1>PUNCH</h1>{role==='Chef'&&<span>CHEF D’ÉQUIPE</span>}</header>
  <div className="new-punch-layout"><div className="new-punch-main">
   <section className={`new-punch-status ${punched?'active':''}`}><div><i/><span>{punched?'EN COURS':'PRÊT À COMMENCER'}</span></div>{punched?<><h2>{activeJob} — {jobs[activeJob]?.name||'Chantier'}</h2><p>Depuis {new Date(startedAt||now).toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'})} · Temps actuel : {timer}</p>{switching&&<small>Le segment {activeJob} sera fermé et {selectedJob} commencera au prochain Punch In.</small>}</>:<p>Vous n’êtes pas pointé.<br/>Sélectionnez un job puis pointez.</p>}</section>
   <label className="new-job-picker"><span>CHOISIR LE JOB</span><select value={selectedJob} onChange={e=>onJob(e.target.value)}><option value="JOB-214">★ SUGGÉRÉ · JOB-214 — Breton · 86 m</option><option value="JOB-315">JOB-315 — Leduc</option><option value="JOB-418">JOB-418 — Bélanger</option></select></label>
   <button className="new-punch-address" onClick={()=>setNavigationOpen(true)} aria-label={`Options de navigation vers ${job.address}`}><MapPin/><span>{job.address}</span><i><Navigation/></i></button>
   <button className="new-job-folder" onClick={onOpenJob}><Folder/><span><b>Dossier de job</b><small>Plans, photos et extras</small></span><ChevronRight/></button>
   <button className="new-punch-action" onClick={punch}>{switching?`PUNCH IN · ${selectedJob}`:punched?`PUNCH OUT · ${activeJob}`:`PUNCH IN · ${selectedJob}`}</button>
  </div><aside className="new-punch-side"><section><span>AUJOURD’HUI</span><small>Total d’heures</small><b>{todayLabel}</b><div>{uniqueJobs.slice(0,3).map(jobId=><i key={jobId}>{jobId}</i>)}{uniqueJobs.length>3&&<i>+{uniqueJobs.length-3}</i>}</div></section><section><span>MA JOURNÉE</span><div className="new-timeline">{visibleSegments.map(s=><p key={s.id}><b>{clock(s.start)} → {s.end?clock(s.end):'En cours'}</b><small>{s.job}</small></p>)}{!todaySegments.length&&<p>Aucun segment aujourd’hui</p>}</div>{todaySegments.length>3&&<button className="all-segments" onClick={onHours}>Voir les {todaySegments.length} segments <ChevronRight/></button>}</section></aside></div>
  <footer className="new-punch-footer"><button onClick={onHours}>Voir / modifier mes heures <ArrowRight/></button><p><Clock3/> Déduction automatique selon les paramètres de la compagnie.</p></footer>
  {navigationOpen&&<div className="gps-sheet-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setNavigationOpen(false)}}><dialog open className="gps-sheet" aria-labelledby="gps-title"><header><h2 id="gps-title">Ouvrir avec</h2><button onClick={()=>setNavigationOpen(false)} aria-label="Fermer"><X/></button></header><a href={wazeUrl} target="_blank" rel="noreferrer"><Navigation/><span><b>Waze</b><small>Ouvrir dans Waze</small></span><ChevronRight/></a><a href={mapsUrl} target="_blank" rel="noreferrer"><MapPin/><span><b>Google Maps</b><small>Ouvrir dans Google Maps</small></span><ChevronRight/></a><button className="gps-copy" onClick={async()=>{await navigator.clipboard.writeText(job.address);setCopied(true)}}><Clipboard/><span><b>{copied?'Adresse copiée':'Copier l’adresse'}</b><small>{job.address}</small></span></button><button className="gps-cancel" onClick={()=>setNavigationOpen(false)}>Annuler</button></dialog></div>}
  {reportOpen&&<div className="quick-report-backdrop"><section className="quick-report"><button className="quick-close" onClick={()=>setReportOpen(false)}>×</button><span>COMPTE RENDU RAPIDE</span><h2>Avant de terminer votre journée</h2><p><b>{selectedJob} — {job.name}</b><br/>Vos dernières valeurs sont déjà préremplies.</p>{progressItems.map(([label])=><div className="progress-row" key={label}><b>{label}</b><div>{[0,25,75,100].map(v=><button key={v} className={progress[label]===v?'active':''} onClick={()=>setProgress({...progress,[label]:v})}>{v} %</button>)}</div></div>)}<button className="confirm-report" onClick={()=>{setReportOpen(false);onToggle()}}><Check/> CONFIRMER ET PUNCH OUT</button></section></div>}
 </div>
}
