'use client';
import { useState, useEffect } from 'react';
import { changeTimeDemo } from '../lib/time-demo';
import { adminCorrectSegment, addDays, canReview, dateKey, duration, reviewCorrection, reviewWeek, timeLabel, totals, updateSettings, weekOf, type Actor, type Proposal } from '../lib/time-domain';
import { useTimeData } from './use-time-data';
import { Breakdown, CorrectionForm, periodLabel } from './my-hours';
import './my-hours.css';

export function TimeNotifications({actor,onOpen}:{actor:Actor;onOpen:()=>void}){const data=useTimeData(actor.companyId);if(!data)return null;const notices=data.notifications.filter(n=>n.company_id===actor.companyId&&n.recipient_user_id===actor.email).slice().reverse();return <div className="time-notices">{notices.map(n=><button key={n.id} onClick={async()=>{try{await changeTimeDemo(actor,d=>{const item=d.notifications.find(x=>x.id===n.id&&x.recipient_user_id===actor.email);if(item)item.read_at=new Date().toISOString();});}finally{window.location.hash=n.deep_link;onOpen();}}}><span><b>{n.title}</b><small>{n.read_at?'Lue · ':''}{new Date(n.created_at).toLocaleString('fr-CA')}</small></span></button>)}</div>;}
export function TimeSettings({actor}:{actor:Actor}){const data=useTimeData(actor.companyId);const [message,setMessage]=useState('');if(!data||!canReview(actor))return null;return <form className="time-settings time-admin" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await changeTimeDemo(actor,d=>updateSettings(d,actor,{...d.settings,minimum:Number(f.get('min')),maximum:Number(f.get('max')),deduction:Number(f.get('deduction')),weekStartsOn:Number(f.get('week'))}));setMessage('Paramètres enregistrés. Les totaux des vues d’heures ont été recalculés.');}catch(e){setMessage((e as Error).message);}}}><h2>Déduction automatique Punch</h2><label>Début de semaine<select name="week" defaultValue={data.settings.weekStartsOn}><option value="1">Lundi</option><option value="0">Dimanche</option></select></label><label>Durée minimale du quart (minutes)<input name="min" type="number" min="0" required defaultValue={data.settings.minimum}/></label><label>Durée maximale du quart (minutes)<input name="max" type="number" min="0" required defaultValue={data.settings.maximum}/></label><label>Déduction (minutes)<input name="deduction" type="number" min="0" required defaultValue={data.settings.deduction}/></label><p>Une déduction par quart, même après un changement de Job. Fuseau : {data.settings.timezone}.</p><button className="mh-primary">Enregistrer</button>{message&&<p role="status">{message}</p>}</form>;}
export function TimeAdmin({actor,mode='punches',jobId,requestId}:{actor:Actor;mode?:string;jobId?:string;requestId?:string}){
 const [now,setNow]=useState(()=>Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(t)},[]);
 const [adminVersion,setAdminVersion]=useState(0),[adminEdit,setAdminEdit]=useState<string|null>(null),[correctionFilter,setCorrectionFilter]=useState('pending'),[refusing,setRefusing]=useState<string|null>(null),[refusalReason,setRefusalReason]=useState('');
 const data=useTimeData(actor.companyId);const [period,setPeriod]=useState(''),[employee,setEmployee]=useState('all'),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 if(!data)return <p>Chargement des heures…</p>;if(!canReview(actor))return <p>Accès non autorisé.</p>;
 const week=period||weekOf(dateKey(new Date(),data.settings.timezone),data.settings.weekStartsOn),all=totals(data.segments.filter(s=>s.company_id===actor.companyId),data.settings,now),rows=data.segments.filter(s=>s.company_id===actor.companyId&&(!jobId||s.job_id===jobId)&&(employee==='all'||s.employee_id===employee)&&dateKey(s.start_time,data.settings.timezone)>=week&&dateKey(s.start_time,data.settings.timezone)<addDays(week,7)).sort((a,b)=>a.start_time.localeCompare(b.start_time));
 const sum=rows.reduce((a,s)=>{const v=all.byId[s.id];return {gross:a.gross+v.gross,deduction:a.deduction+v.deduction,payable:a.payable+v.payable};},{gross:0,deduction:0,payable:0});
 const run=async(fn:()=>Promise<void>)=>{setError('');setBusy(true);try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const decide=(id:string,decision:'approved'|'rejected',p?:Proposal,note='')=>changeTimeDemo(actor,d=>reviewCorrection(d,actor,id,decision,note,p));
 function exportRows(){const quote=(v:unknown)=>`"${String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;const header=['company_id','employee_id','segment_id','job_id','start_time','end_time','gross_minutes','deduction_minutes','payable_minutes'];const csv=[header,...rows.map(s=>[s.company_id,s.employee_id,s.id,s.job_id,s.start_time,s.end_time,all.byId[s.id].gross,all.byId[s.id].deduction,all.byId[s.id].payable])].map(r=>r.map(quote).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`forge-heures-${week}.csv`;link.click();URL.revokeObjectURL(url);}
 return <section className="time-admin"><span>ÉQUIPES & HEURES</span><h1>{mode==='corrections'?'Corrections et approbations':mode==='time-reports'?'Rapports d’heures':jobId?'Équipe & heures':'Centre de contrôle des Punchs'}</h1>
 {error&&<p role="alert" className="mh-error">{error}</p>}
 {mode!=='corrections'&&<><div className="time-filters"><label>Semaine<input type="date" value={week} onChange={e=>e.target.value&&setPeriod(weekOf(e.target.value,data.settings.weekStartsOn))}/></label><label>Employé<select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="all">Tous les employés</option>{data.employees.filter(e=>e.role==='Chef'||e.role==='Employé').map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><button onClick={exportRows}>Exporter CSV</button></div><p>{periodLabel(week)}</p>{mode!=='punches'&&<Breakdown value={sum}/>}<div className="time-table-wrap"><table><thead><tr>{['Employé','Date','Job','Entrée','Sortie','Brut','Déduction','Payable','État','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.id}><td data-label="Employé">{data.employees.find(e=>e.id===s.employee_id)?.name}</td><td data-label="Date">{dateKey(s.start_time,data.settings.timezone)}</td><td data-label="Job">{data.jobs.find(j=>j.id===s.job_id)?.number}</td><td data-label="Entrée">{timeLabel(s.start_time,data.settings.timezone)}</td><td data-label="Sortie">{s.end_time?timeLabel(s.end_time,data.settings.timezone):'En cours'}</td><td data-label="Brut">{duration(all.byId[s.id].gross)}</td><td data-label="Déduction">{duration(all.byId[s.id].deduction)}</td><td data-label="Payable">{duration(all.byId[s.id].payable)}</td><td data-label="État">{data.corrections.some(c=>c.original_segment_id===s.id&&c.status==='pending')?'Modification en attente':s.gps_context||'Enregistré'}</td><td data-label="Actions"><button onClick={()=>{setAdminVersion(s.version);setAdminEdit(s.id)}}>Modifier</button></td></tr>)}</tbody></table>{!rows.length&&<p>Aucune heure pour cette période.</p>}</div></>}
 {adminEdit&&data.segments.find(s=>s.id===adminEdit)&&<details open><summary>Correction administrative</summary><CorrectionForm data={{...data,jobs:data.jobs.filter(j=>j.members.includes(data.employees.find(e=>e.id===data.segments.find(s=>s.id===adminEdit)?.employee_id)?.user_id||''))}} segment={data.segments.find(s=>s.id===adminEdit)} day={dateKey(data.segments.find(s=>s.id===adminEdit)!.start_time,data.settings.timezone)} label="Enregistrer la correction" onCancel={()=>setAdminEdit(null)} onSubmit={async(p,reason,note)=>{const s=data.segments.find(s=>s.id===adminEdit)!;await changeTimeDemo(actor,d=>adminCorrectSegment(d,actor,s.id,adminVersion,p,reason,note));setAdminEdit(null)}}/></details>}
 {mode==='corrections'&&<><h2>Demandes de correction</h2><div className="time-review-actions">{[['pending','En attente'],['approved','Approuvées'],['rejected','Refusées'],['all','Toutes']].map(([value,label])=><button key={value} aria-pressed={correctionFilter===value} onClick={()=>setCorrectionFilter(value)}>{label}</button>)}</div>{!data.corrections.length&&<p>Aucune demande. Les corrections envoyées depuis « Mes heures » apparaîtront ici.</p>}{data.corrections.filter(c=>c.company_id===actor.companyId&&(correctionFilter==='all'||c.status===correctionFilter||c.id===requestId)).slice().reverse().map(c=><details key={`${c.id}:${requestId||''}`} open={c.id===requestId||c.status==='pending'}><summary>{data.employees.find(e=>e.id===c.employee_id)?.name} · {dateKey(c.proposed.start_time,data.settings.timezone)} · {c.original_segment_id?'Correction':'Segment oublié'} — {c.status==='pending'?'En attente':c.status==='approved'?'Approuvée':'Refusée'}</summary><p>{c.reason} {c.note&&`— ${c.note}`}</p><div className="mh-comparison"><article><span>ORIGINAL</span><b>{c.original?`${timeLabel(c.original.start_time,data.settings.timezone)} → ${timeLabel(c.original.end_time!,data.settings.timezone)}`:'Aucun segment'}</b><small>{data.jobs.find(j=>j.id===c.original?.job_id)?.number}</small></article><article><span>PROPOSITION</span><b>{timeLabel(c.proposed.start_time,data.settings.timezone)} → {timeLabel(c.proposed.end_time,data.settings.timezone)}</b><small>{data.jobs.find(j=>j.id===c.proposed.job_id)?.number}</small></article></div>{c.status==='pending'&&editing!==c.id&&<div className="time-review-actions"><button disabled={busy} className="mh-primary" onClick={()=>void run(()=>decide(c.id,'approved'))}>Approuver</button><button disabled={busy} onClick={()=>{setRefusing(c.id);setRefusalReason('')}}>Refuser</button><button disabled={busy} onClick={()=>setEditing(c.id)}>Modifier puis approuver</button></div>}{refusing===c.id&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await decide(c.id,'rejected',undefined,refusalReason);setRefusing(null)})}}><label>Raison du refus<input required value={refusalReason} onChange={e=>setRefusalReason(e.target.value)}/></label><button disabled={busy||!refusalReason.trim()}>Confirmer le refus</button><button type="button" onClick={()=>setRefusing(null)}>Annuler</button></form>}{editing===c.id&&<CorrectionForm data={{...data,jobs:data.jobs.filter(j=>j.members.includes(c.requested_by_user_id))}} initial={c.proposed} segment={c.original} day={dateKey(c.proposed.start_time,data.settings.timezone)} label="Approuver ces valeurs" onCancel={()=>setEditing(null)} onSubmit={async(p,reason,note)=>{await decide(c.id,'approved',p,`${reason} ${note}`);setEditing(null);}}/>}{c.reviewed_at&&<p>{c.reviewed_by_user_id} · {new Date(c.reviewed_at).toLocaleString('fr-CA')} {c.reviewer_note}</p>}</details>)}
 <h2>Semaines soumises</h2>{data.submissions.slice().reverse().map(s=><details key={`${s.id}:${requestId||''}`} open={s.id===requestId}><summary>{data.employees.find(e=>e.id===s.employee_id)?.name} · {periodLabel(s.week)} · {s.status==='submitted'?'Soumise':s.status==='approved'?'Approuvée':'Refusée'}</summary>{s.status==='submitted'&&<div className="time-review-actions"><button disabled={busy} onClick={()=>void run(()=>changeTimeDemo(actor,d=>reviewWeek(d,actor,s.id,'approved')))}>Approuver</button><button disabled={busy} onClick={()=>void run(()=>changeTimeDemo(actor,d=>reviewWeek(d,actor,s.id,'rejected')))}>Refuser</button></div>}</details>)}
 <h2>Journal d’audit</h2><div className="time-audit">{data.audit.slice().reverse().map(a=><article key={a.id}><b>{a.action}</b><small>{a.actor_id} · {new Date(a.created_at).toLocaleString('fr-CA')}</small><details><summary>Valeurs et motif</summary><p>{a.reason}</p><pre>{JSON.stringify({before:a.before,after:a.after},null,2)}</pre></details></article>)}</div></>}
 <p className="mh-demo">Mode Démo · les mêmes segments alimentent Punch, Mes heures, Jobs et rapports.</p></section>;
}
