import {readTimeDemo} from './time-demo';
import {type Actor} from './time-domain';
import {type ExpenseLedger,expenseEmployee,visibleExpenses} from './expense-domain';
// Explicit, device-local demo adapter. Not a production database or authentication boundary.
const key='forge:mir-demo:expenses';
let cachedRaw:string|null|undefined,cached:ExpenseLedger|null=null;
export function readExpenseDemo(){if(typeof window==='undefined')return null;const raw=localStorage.getItem(key);if(cached&&raw===cachedRaw)return cached;cachedRaw=raw;cached=raw?JSON.parse(raw):{company_id:'mir-demo',expenses:[],attachments:[],items:[],audit:[],notifications:[],approvals:[],categories:['Matériaux','Outils','Essence','Location','Stationnement','Repas','Fournitures','Autre'].map((name,sort_order)=>({id:`expense-category-${sort_order}`,company_id:'mir-demo',name,active:true,sort_order}))};return cached;}
export async function changeExpenseDemo(a:Actor,change:(d:ExpenseLedger)=>void){if(a.companyId!=='mir-demo')throw Error('Disponible en démo seulement. Le service central des achats n’est pas encore connecté.');const apply=()=>{expenseEmployee(readTimeDemo(a.companyId)!,a);const d=structuredClone(readExpenseDemo()!);change(d);localStorage.setItem(key,JSON.stringify(d));cached=null;window.dispatchEvent(new Event('forge-expenses-updated'));};if(navigator.locks)await navigator.locks.request(key,apply);else apply();}
function files(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('forge-demo-files',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('attachments'))request.result.createObjectStore('attachments')};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('Stockage des photos indisponible.'))});}
export async function putReceiptFile(id:string,file:File){if(file.size>15*1024*1024)throw Error('Le reçu doit faire moins de 15 Mo.');if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))throw Error('Choisissez une image JPG, PNG, WebP ou un PDF.');const db=await files();await new Promise<void>((resolve,reject)=>{const tx=db.transaction('attachments','readwrite');tx.objectStore('attachments').put(file,id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(Error('La photo n’a pas pu être sauvegardée.'))});db.close();}
export async function receiptFile(a:Actor,id:string){if(a.companyId!=='mir-demo')throw Error('Fichier inaccessible.');const d=readExpenseDemo()!,i=readTimeDemo(a.companyId)!;const attachment=d.attachments.find(f=>f.id===id&&f.company_id===a.companyId&&visibleExpenses(d,i,a).some(x=>x.id===f.owner_id));if(!attachment)throw Error('Fichier inaccessible.');const db=await files();const result=await new Promise<Blob|undefined>((resolve,reject)=>{const tx=db.transaction('attachments','readonly');const r=tx.objectStore('attachments').get(attachment.file_reference);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('Fichier indisponible.'))});db.close();return result;}
