import {canReview,type Actor,type TimeData} from './time-domain';

export const payments={personal_reimbursement:'À rembourser',company_card:'Carte de compagnie',supplier_account:'Porter au compte'};
export const validations={draft:'Brouillon',submitted:'À vérifier',under_review:'En vérification',approved:'Approuvé',rejected:'Refusé'};
export const reimbursements={not_applicable:'Sans remboursement',to_reimburse:'À rembourser',reimbursed:'Remboursé',supplier_account:'Compte fournisseur'};
export type ExpenseFields={job_id:string;supplier_id:string|null;supplier_name_snapshot:string;purchase_date:string;invoice_number:string;description:string;category:string;subtotal:number|null;tax_1:number|null;tax_2:number|null;total:number;currency:string;payment_method:keyof typeof payments;note:string;receipt_document_id:string|null};
export type Expense=ExpenseFields&{id:string;company_id:string;employee_id:string;submitted_by_user_id:string;validation_status:keyof typeof validations;reimbursement_status:keyof typeof reimbursements;ocr_status:'not_requested'|'pending'|'processing'|'completed'|'needs_review'|'failed';ocr_confidence?:number;detected_values?:Partial<ExpenseFields>;approved_values?:ExpenseFields;created_at:string;updated_at:string;submitted_at?:string;approved_at?:string;rejected_at?:string;reimbursed_at?:string;approved_by_user_id?:string;rejected_by_user_id?:string;reimbursed_by_user_id?:string;rejection_reason?:string;payment_reference?:string;version:number};
export type ExpenseItem={id:string;company_id:string;expense_id:string;job_id:string;description:string;quantity:number;unit:string;unit_cost:number;inventory_item_id?:string;inventory_transaction_id?:string;delivery_batch_id?:string};
// Metadata uses the existing Attachment, Audit and Approval conventions. Files are referenced once.
export type ExpenseLedger={company_id:string;expenses:Expense[];attachments:{id:string;company_id:string;owner_type:'expense';owner_id:string;job_id:string;filename:string;content_type:string;file_reference:string;uploaded_by:string;uploaded_by_employee_id:string;created_at:string}[];categories:{id:string;company_id:string;name:string;active:boolean;sort_order:number}[];items:ExpenseItem[];audit:TimeData['audit'];notifications:TimeData['notifications'];approvals:{id:string;company_id:string;object_type:'expense';object_id:string;decision:string;decided_by_user_id:string;note:string;created_at:string}[]};
export function emptyExpenseFields():ExpenseFields{return {job_id:'',supplier_id:null,supplier_name_snapshot:'',purchase_date:new Date().toLocaleDateString('en-CA'),invoice_number:'',description:'',category:'',subtotal:null,tax_1:null,tax_2:null,total:0,currency:'CAD',payment_method:'personal_reimbursement',note:'',receipt_document_id:null};}
export function expenseEmployee(identity:TimeData,a:Actor){const e=identity.employees.find(e=>e.company_id===a.companyId&&e.user_id===a.email&&e.role===a.role);if(identity.company_id!==a.companyId||!e)throw Error('Employé ou compagnie non autorisé.');return e;}
export function visibleExpenses(d:ExpenseLedger,identity:TimeData,a:Actor){const e=expenseEmployee(identity,a);if(d.company_id!==a.companyId)throw Error('Compagnie inaccessible.');return d.expenses.filter(x=>x.company_id===a.companyId&&(x.employee_id===e.id||(canReview(a)&&x.validation_status!=='draft')));}
function audit(d:ExpenseLedger,a:Actor,action:string,x:Expense,before:unknown,reason=''){d.audit.push({id:crypto.randomUUID(),company_id:a.companyId,actor_id:a.email,action,entity_id:x.id,before,after:structuredClone(x),reason,created_at:new Date().toISOString()});}
function get(d:ExpenseLedger,i:TimeData,a:Actor,id:string){const x=visibleExpenses(d,i,a).find(x=>x.id===id);if(!x)throw Error('Reçu inaccessible.');return x;}
function valid(d:ExpenseLedger,i:TimeData,a:Actor,x:Expense,submit:boolean){const employee=i.employees.find(e=>e.id===x.employee_id);const job=i.jobs.find(j=>j.id===x.job_id&&j.company_id===a.companyId);if(!job||!employee||!job.members.includes(employee.user_id))throw Error('Choisissez une Job assignée à l’employé.');if(!Object.hasOwn(payments,x.payment_method))throw Error('Mode de paiement invalide.');if(!/^\d{4}-\d{2}-\d{2}$/.test(x.purchase_date)||!Number.isFinite(Date.parse(x.purchase_date)))throw Error('Date invalide.');if(![x.total,x.subtotal??0,x.tax_1??0,x.tax_2??0].every(n=>Number.isFinite(n)&&n>=0))throw Error('Montants invalides.');if(x.receipt_document_id&&!d.attachments.some(f=>f.id===x.receipt_document_id&&f.company_id===a.companyId&&f.owner_id===x.id&&f.job_id===x.job_id))throw Error('Le reçu joint ne correspond pas à cet achat.');if(submit&&(!x.description.trim()||!x.supplier_name_snapshot.trim()||x.total<=0||!d.categories.some(c=>c.id===x.category&&c.company_id===a.companyId&&c.active)||!x.receipt_document_id))throw Error('Complétez le fournisseur, la description, la catégorie, le montant et le reçu.');}
export function saveExpense(d:ExpenseLedger,i:TimeData,a:Actor,id:string,fields:ExpenseFields,version?:number){const employee=expenseEmployee(i,a);if(d.company_id!==a.companyId)throw Error('Compagnie inaccessible.');let x=d.expenses.find(x=>x.id===id);if(x&&(x.company_id!==a.companyId||x.employee_id!==employee.id||x.validation_status!=='draft'))throw Error('Ce reçu ne peut plus être modifié.');if(x&&version!==x.version)throw Error('Ce reçu a changé. Rouvrez-le avant de modifier.');const before=x?structuredClone(x):null;const stamp=new Date().toISOString();const next:Expense={...fields,id,company_id:a.companyId,employee_id:employee.id,submitted_by_user_id:a.email,validation_status:'draft',reimbursement_status:fields.payment_method==='personal_reimbursement'?'to_reimburse':fields.payment_method==='supplier_account'?'supplier_account':'not_applicable',ocr_status:'not_requested',created_at:x?.created_at||stamp,updated_at:stamp,version:(x?.version||0)+1};valid(d,i,a,next,false);if(x)Object.assign(x,next);else{d.expenses.push(next);x=next;}audit(d,a,before?'expense_draft_updated':'expense_draft_created',x,before);return x;}
export function submitExpense(d:ExpenseLedger,i:TimeData,a:Actor,id:string){const x=get(d,i,a,id);if(x.employee_id!==expenseEmployee(i,a).id)throw Error('Soumission non autorisée.');if(x.validation_status==='submitted')return x;if(x.validation_status!=='draft')throw Error('Ce reçu a déjà été soumis.');valid(d,i,a,x,true);const before=structuredClone(x);x.validation_status='submitted';x.submitted_at=x.updated_at=new Date().toISOString();x.version++;audit(d,a,'expense_submitted',x,before);for(const recipient of i.employees.filter(canReview))d.notifications.push({id:crypto.randomUUID(),company_id:a.companyId,recipient_user_id:recipient.user_id,source_type:'expense',source_id:x.id,employee_id:x.employee_id,original_segment_id:null,job_id:x.job_id,title:`Nouveau reçu à vérifier · ${x.total.toFixed(2)} ${x.currency}`,deep_link:`#admin/purchases/${x.id}`,read_at:null,created_at:x.updated_at});return x;}
export function reviewExpense(d:ExpenseLedger,i:TimeData,a:Actor,id:string,action:'under_review'|'approved'|'rejected'|'reimbursed',version:number,reason='',correction?:ExpenseFields){if(!canReview(a))throw Error('Action réservée à l’administration.');const x=get(d,i,a,id);if(x.version!==version)throw Error('Ce reçu a changé. Rouvrez-le avant de continuer.');const before=structuredClone(x);const stamp=new Date().toISOString();if(action==='reimbursed'){if(x.validation_status!=='approved'||x.payment_method!=='personal_reimbursement'||x.reimbursement_status!=='to_reimburse')throw Error('Ce reçu ne peut pas être remboursé.');x.reimbursement_status='reimbursed';x.reimbursed_at=stamp;x.reimbursed_by_user_id=a.email;x.payment_reference=reason;}else{if(!['submitted','under_review'].includes(x.validation_status))throw Error('Ce reçu a déjà été traité.');if(action==='rejected'&&!reason.trim())throw Error('Indiquez la raison du refus.');if(correction){if(!reason.trim())throw Error('Expliquez la correction.');const candidate={...x,...correction};valid(d,i,a,candidate,true);Object.assign(x,correction);x.reimbursement_status=x.payment_method==='personal_reimbursement'?'to_reimburse':x.payment_method==='supplier_account'?'supplier_account':'not_applicable';}x.validation_status=action;if(action==='approved'){x.approved_at=stamp;x.approved_by_user_id=a.email;x.approved_values=structuredClone(x); }if(action==='rejected'){x.rejected_at=stamp;x.rejected_by_user_id=a.email;x.rejection_reason=reason;}if(action!=='under_review')d.approvals.push({id:crypto.randomUUID(),company_id:a.companyId,object_type:'expense',object_id:id,decision:action,decided_by_user_id:a.email,note:reason,created_at:stamp});}x.version++;x.updated_at=stamp;audit(d,a,`expense_${action}`,x,before,reason);}
