// Shared domain for the demo adapter and the future authenticated repository.
import type {EmployeeProfile} from './employee-profile';
// Durations are minutes; segment timestamps are ISO instants. No UI owns a copy.
export type Actor = { companyId:string; email:string; userName:string; role:'Boss'|'Adjointe'|'Chef'|'Employé' };
export type Segment = { id:string; company_id:string; employee_id:string; job_id:string; shift_id:string; start_time:string; end_time:string|null; source:string; gps_context?:string; created_at:string; updated_at:string; version:number };
export type Proposal = { job_id:string; start_time:string; end_time:string };
export type Correction = { id:string; company_id:string; employee_id:string; original_segment_id:string|null; original:Segment|null; proposed:Proposal; reason:string; note:string; requested_by_user_id:string; requested_at:string; status:'pending'|'approved'|'rejected'; reviewed_by_user_id?:string; reviewed_at?:string; reviewer_note?:string; resulting_segment_id?:string };
export type Submission = { id:string; company_id:string; employee_id:string; week:string; status:'submitted'|'approved'|'rejected'; submitted_at:string; submitted_by_user_id:string; reviewed_at?:string; reviewed_by_user_id?:string };
export type Settings = { timezone:string; weekStartsOn:number; minimum:number; maximum:number; deduction:number };
export type Team={id:string;company_id:string;name:string;lead_id:string|null;job_id:string|null;member_ids:string[]};
export type JobRecord={id:string;company_id:string;number:string;name:string;members:string[];cover_photo?:string;cover_photo_name?:string;cover_photo_crop?:{x:number;y:number;zoom:number};address?:string;unit?:string;city?:string;province?:string;postal_code?:string;client?:string;contractor?:string;phone?:string;project_type?:string;description?:string;site_instructions?:string;status?:string;estimated_hours?:number;planned_start?:string;planned_end?:string;planned_delivery?:string;planning_notes?:string;lead_id?:string;team_id?:string;version?:number};
export type TimeData = { company_id:string; revision:number; settings:Settings; teams?:Team[]; jobs:JobRecord[]; employees:{id:string; company_id:string; user_id:string; name:string; role:Actor['role'];phone?:string;trade?:string;status?:'active'|'inactive';employee_number?:string;profile?:EmployeeProfile;profile_version?:number}[]; segments:Segment[]; corrections:Correction[]; submissions:Submission[]; audit:{id:string; company_id:string; actor_id:string; action:string; entity_id:string; before:unknown; after:unknown; reason:string; created_at:string}[]; notifications:{id:string; company_id:string; recipient_user_id:string; source_type:string; source_id:string; employee_id:string; original_segment_id:string|null; job_id:string|null; title:string; deep_link:string; read_at:string|null; created_at:string}[] };
export function saveJob(d:TimeData,a:Actor,input:JobRecord){
 authorize(d,a,true);if(input.company_id!==a.companyId)throw Error('Compagnie invalide.');
 if(!input.number.trim()||!input.name.trim())throw Error('Numéro et nom obligatoires.');
 if(d.jobs.some(j=>j.id!==input.id&&j.number.toLowerCase()===input.number.trim().toLowerCase()))throw Error('Ce numéro de Job existe déjà.');
 if(input.members.some(m=>!d.employees.some(e=>e.user_id===m&&m&&e.company_id===a.companyId)))throw Error('Membre inaccessible.');
 if(input.lead_id&&!d.employees.some(e=>e.id===input.lead_id&&e.role==='Chef'&&input.members.includes(e.user_id)))throw Error('Choisissez un chef membre de cette Job.');
 if(input.team_id&&!(d.teams||[]).some(t=>t.id===input.team_id&&t.company_id===a.companyId))throw Error('Équipe inaccessible.');
 if(input.estimated_hours!==undefined&&(!Number.isFinite(input.estimated_hours)||input.estimated_hours<0))throw Error('Estimation invalide.');
 if(input.planned_start&&input.planned_delivery&&input.planned_delivery<input.planned_start)throw Error('La livraison doit suivre le début prévu.');
 if(input.planned_start&&input.planned_end&&input.planned_end<input.planned_start)throw Error('L’échéance doit suivre le début prévu.');
 const existing=d.jobs.find(j=>j.id===input.id);if(existing&&(existing.version||0)!==(input.version||0))throw Error('La Job a changé. Ouvrez-la à nouveau.');
 const before=existing?structuredClone(existing):null;const value={...input,number:input.number.trim(),name:input.name.trim(),version:(existing?.version||0)+1};
 if(existing)Object.assign(existing,value);else d.jobs.push(value);
 audit(d,a,existing?'job_updated':'job_created',input.id,before,value);
}
export const employeeId=(a:Actor)=>`employee:${a.companyId}:${a.email}`;
export const canReview=(a:Pick<Actor,'role'>|undefined)=>a?.role==='Boss'||a?.role==='Adjointe';
export const duration=(minutes:number)=>`${Math.floor(minutes/60)} h ${String(Math.round(minutes%60)).padStart(2,'0')}`;
export function dateKey(instant:string|Date,timezone:string){return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(instant));}
export function addDays(day:string,n:number){const d=new Date(`${day}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
export function weekOf(day:string,start=1){return addDays(day,-((new Date(`${day}T12:00:00Z`).getUTCDay()-start+7)%7));}
export function timeLabel(instant:string,timezone:string){return new Intl.DateTimeFormat('fr-CA',{timeZone:timezone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(instant)).replace(' h ',':');}
export function localInstant(day:string,time:string,timezone:string){
 const match=/^(\d{2}):(\d{2})$/.exec(time);if(!match||+match[1]>23||+match[2]>59)throw Error('Heure invalide.');
 const target=Date.parse(`${day}T${time}:00Z`);let stamp=target;
 for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(stamp));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));stamp+=target-Date.parse(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}Z`);}
 const result=new Date(stamp).toISOString();if(dateKey(result,timezone)!==day||timeLabel(result,timezone)!==time)throw Error('Cette heure locale n’existe pas (changement d’heure).');return result;
}
export function totals(segments:Segment[],settings:Settings,now=Date.now()){
 const groups=new Map<string,Segment[]>();for(const s of segments){const k=`${s.employee_id}:${s.shift_id}`;groups.set(k,[...(groups.get(k)||[]),s]);}
 const byId:Record<string,{gross:number;deduction:number;payable:number}>={};
 for(const group of groups.values()){const sorted=[...group].sort((a,b)=>a.start_time.localeCompare(b.start_time));const gross=sorted.map(s=>Math.max(0,Math.floor(((s.end_time?Date.parse(s.end_time):now)-Date.parse(s.start_time))/60000)));const sum=gross.reduce((a,b)=>a+b,0);let remaining=sum>=settings.minimum&&sum<=settings.maximum?settings.deduction:0;
 // One deduction per shift, allocated to its first minutes, never per Job.
 sorted.forEach((s,i)=>{const deduction=Math.min(remaining,gross[i]);remaining-=deduction;byId[s.id]={gross:gross[i],deduction,payable:gross[i]-deduction};});}
 return {byId,...Object.values(byId).reduce((a,b)=>({gross:a.gross+b.gross,deduction:a.deduction+b.deduction,payable:a.payable+b.payable}),{gross:0,deduction:0,payable:0})};
}
export function weekStatus(d:TimeData,id:string,week:string){const end=addDays(week,7);if(d.corrections.some(c=>c.employee_id===id&&c.status==='pending'&&[c.proposed.start_time,c.original?.start_time].some(t=>t&&dateKey(t,d.settings.timezone)>=week&&dateKey(t,d.settings.timezone)<end)))return 'Modification en attente';const s=d.submissions.find(s=>s.employee_id===id&&s.week===week);return s?({submitted:'Soumise',approved:'Approuvée',rejected:'Refusée'}[s.status]):'À confirmer';}
function authorize(d:TimeData,a:Actor,review=false){if(d.company_id!==a.companyId||!d.employees.some(e=>e.company_id===a.companyId&&e.user_id===a.email&&e.role===a.role))throw Error('Accès non autorisé.');if(review&&!canReview(a))throw Error('Approbation réservée au Boss et à l’Adjointe.');}
function audit(d:TimeData,a:Actor,action:string,id:string,before:unknown,after:unknown,reason=''){d.audit.push({id:crypto.randomUUID(),company_id:a.companyId,actor_id:a.email,action,entity_id:id,before:structuredClone(before),after:structuredClone(after),reason,created_at:new Date().toISOString()});}
function notify(d:TimeData,a:Actor,source:Correction|Submission,title:string,recipients:string[]){for(const recipient of recipients)d.notifications.push({id:crypto.randomUUID(),company_id:a.companyId,recipient_user_id:recipient,source_type:'proposed' in source?'time_correction':'week_submission',source_id:source.id,employee_id:source.employee_id,original_segment_id:'original_segment_id' in source?source.original_segment_id:null,job_id:'proposed' in source?source.proposed.job_id:null,title,deep_link:canReview(d.employees.find(e=>e.user_id===recipient))?`#admin/teams/corrections/${source.id}`:`#field/hours/request/${source.id}`,read_at:null,created_at:new Date().toISOString()});}
function validateProposal(d:TimeData,employee:string,p:Proposal,ignore?:string,now=Date.now()){
 const member=d.employees.find(e=>e.id===employee&&e.company_id===d.company_id);const job=d.jobs.find(j=>j.id===p.job_id&&j.company_id===d.company_id);
 if(!member||!job?.members.includes(member.user_id))throw Error('Choisissez une Job assignée à cet employé.');
 const start=Date.parse(p.start_time),end=Date.parse(p.end_time);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end>now||end-start>86400000)throw Error('La fin doit suivre le début, sans dépasser maintenant ni 24 heures.');
 if(d.segments.some(s=>s.employee_id===employee&&s.id!==ignore&&start<(s.end_time?Date.parse(s.end_time):Infinity)&&end>Date.parse(s.start_time)))throw Error('Ce segment chevauche une période déjà pointée.');
}
export function requestCorrection(d:TimeData,a:Actor,originalId:string|null,p:Proposal,reason:string,note:string){authorize(d,a);const original=originalId?d.segments.find(s=>s.id===originalId&&s.company_id===a.companyId&&s.employee_id===employeeId(a)):null;if(originalId&&!original)throw Error('Segment introuvable.');if(original&&!original.end_time)throw Error('Terminez le Punch avant de demander une correction.');if(!reason.trim())throw Error('La raison est obligatoire.');if(d.corrections.some(c=>c.status==='pending'&&c.employee_id===employeeId(a)&&(originalId?c.original_segment_id===originalId:Date.parse(p.start_time)<Date.parse(c.proposed.end_time)&&Date.parse(p.end_time)>Date.parse(c.proposed.start_time))))throw Error('Une demande est déjà en attente pour cette période.');validateProposal(d,employeeId(a),p,originalId||undefined);const c:Correction={id:crypto.randomUUID(),company_id:a.companyId,employee_id:employeeId(a),original_segment_id:originalId,original:original?structuredClone(original):null,proposed:p,reason:reason.trim(),note:note.trim(),requested_by_user_id:a.email,requested_at:new Date().toISOString(),status:'pending'};d.corrections.push(c);audit(d,a,'correction_requested',c.id,c.original,c,reason);notify(d,a,c,'Correction d’heures à approuver',d.employees.filter(e=>e.role==='Boss'||e.role==='Adjointe').map(e=>e.user_id));return c;}
export function reviewCorrection(d:TimeData,a:Actor,id:string,decision:'approved'|'rejected',reviewerNote:string,proposal?:Proposal){authorize(d,a,true);const c=d.corrections.find(c=>c.id===id&&c.company_id===a.companyId);if(!c||c.status!=='pending')throw Error('Cette demande a déjà été traitée.');if(c.requested_by_user_id===a.email)throw Error('Vous ne pouvez pas approuver vos propres heures.');const before=structuredClone(c);if(decision==='approved'){const p=proposal||c.proposed;validateProposal(d,c.employee_id,p,c.original_segment_id||undefined);const s=d.segments.find(s=>s.id===c.original_segment_id);if(c.original_segment_id&&(!s||s.version!==c.original?.version))throw Error('Le segment a changé. Refusez cette demande devenue obsolète.');if(s){const old=structuredClone(s);Object.assign(s,p,{updated_at:new Date().toISOString(),version:s.version+1});audit(d,a,'segment_corrected',s.id,old,s,reviewerNote||c.reason);c.resulting_segment_id=s.id;}else{const stamp=new Date().toISOString();const segment:Segment={id:crypto.randomUUID(),company_id:a.companyId,employee_id:c.employee_id,shift_id:crypto.randomUUID(),...p,source:'approved_correction',created_at:stamp,updated_at:stamp,version:1};d.segments.push(segment);c.resulting_segment_id=segment.id;audit(d,a,'missing_segment_approved',segment.id,null,segment,c.reason);}c.proposed=p;
 for(const week of new Set([p.start_time,c.original?.start_time].filter(Boolean).map(t=>weekOf(dateKey(t!,d.settings.timezone),d.settings.weekStartsOn)))){const submission=d.submissions.find(s=>s.employee_id===c.employee_id&&s.week===week);if(submission&&submission.status!=='submitted'){const old=structuredClone(submission);submission.status='submitted';delete submission.reviewed_at;delete submission.reviewed_by_user_id;audit(d,a,'week_reopened',submission.id,old,submission,c.reason);}}}
 c.status=decision;c.reviewed_by_user_id=a.email;c.reviewed_at=new Date().toISOString();c.reviewer_note=reviewerNote;audit(d,a,`correction_${decision}`,id,before,c,reviewerNote);notify(d,a,c,decision==='approved'?'Correction approuvée':'Correction refusée',[c.requested_by_user_id]);}
export function submitWeek(d:TimeData,a:Actor,week:string){authorize(d,a);if(weekOf(week,d.settings.weekStartsOn)!==week)throw Error('Semaine invalide.');const end=addDays(week,7),rows=d.segments.filter(s=>s.employee_id===employeeId(a)&&dateKey(s.start_time,d.settings.timezone)>=week&&dateKey(s.start_time,d.settings.timezone)<end);if(!rows.length||rows.some(s=>!s.end_time))throw Error('Ajoutez des heures et terminez les Punchs avant de confirmer.');if(weekStatus(d,employeeId(a),week)==='Modification en attente')throw Error('Une correction est encore en attente.');let s=d.submissions.find(s=>s.employee_id===employeeId(a)&&s.week===week);if(s&&s.status!=='rejected')throw Error('Cette semaine a déjà été soumise.');const before=s?structuredClone(s):null;const values={id:s?.id||crypto.randomUUID(),company_id:a.companyId,employee_id:employeeId(a),week,status:'submitted' as const,submitted_at:new Date().toISOString(),submitted_by_user_id:a.email};if(s)Object.assign(s,values);else{ s=values;d.submissions.push(s);}audit(d,a,'week_submitted',s.id,before,s);notify(d,a,s,'Semaine à approuver',d.employees.filter(e=>canReview(e)).map(e=>e.user_id));}
export function reviewWeek(d:TimeData,a:Actor,id:string,decision:'approved'|'rejected'){authorize(d,a,true);const s=d.submissions.find(s=>s.id===id&&s.company_id===a.companyId);if(!s||s.status!=='submitted'||s.submitted_by_user_id===a.email)throw Error('Semaine non admissible.');if(weekStatus(d,s.employee_id,s.week)==='Modification en attente')throw Error('Traitez les corrections avant la semaine.');const old=structuredClone(s);s.status=decision;s.reviewed_at=new Date().toISOString();s.reviewed_by_user_id=a.email;audit(d,a,`week_${decision}`,id,old,s);notify(d,a,s,decision==='approved'?'Semaine approuvée':'Semaine refusée',[s.submitted_by_user_id]);}
export function punch(d:TimeData,a:Actor,jobId:string,action:'toggle'|'switch',now=new Date().toISOString()){authorize(d,a);const job=d.jobs.find(j=>j.id===jobId&&j.company_id===a.companyId&&j.members.includes(a.email));if(!job)throw Error('Job non assignée.');const active=d.segments.find(s=>s.employee_id===employeeId(a)&&!s.end_time);if(action==='switch'&&active?.job_id===jobId)return;if(active){if(Date.parse(now)<=Date.parse(active.start_time))throw Error('Veuillez attendre avant de terminer ce segment.');const old=structuredClone(active);active.end_time=now;active.updated_at=now;active.version++;audit(d,a,'punch_out',active.id,old,active);}if(!active||action==='switch'){const s:Segment={id:crypto.randomUUID(),company_id:a.companyId,employee_id:employeeId(a),job_id:jobId,shift_id:active?.shift_id||crypto.randomUUID(),start_time:now,end_time:null,source:'punch',created_at:now,updated_at:now,version:1};d.segments.push(s);audit(d,a,'punch_in',s.id,null,s);}}
export function updateSettings(d:TimeData,a:Actor,s:Settings){authorize(d,a,true);if(!Number.isInteger(s.weekStartsOn)||s.weekStartsOn<0||s.weekStartsOn>6||![s.minimum,s.maximum,s.deduction].every(Number.isInteger)||s.minimum<0||s.maximum<s.minimum||s.deduction<0||s.deduction>s.minimum)throw Error('Paramètres de déduction invalides.');new Intl.DateTimeFormat('fr-CA',{timeZone:s.timezone});const old=d.settings;d.settings=s;audit(d,a,'time_settings_updated',d.company_id,old,s);}
export function adminCorrectSegment(d:TimeData,a:Actor,id:string,version:number,p:Proposal,reason:string,note:string){
 authorize(d,a,true);const s=d.segments.find(s=>s.id===id&&s.company_id===a.companyId);
 if(!s||s.version!==version)throw Error('Ce Punch a changé. Ouvrez-le à nouveau.');
 if(!reason.trim())throw Error('La raison est obligatoire.');
 if(d.corrections.some(c=>c.original_segment_id===id&&c.status==='pending'))throw Error('Traitez d’abord la demande de correction en attente.');
 validateProposal(d,s.employee_id,p,id);const before=structuredClone(s);
 Object.assign(s,p,{version:s.version+1,updated_at:new Date().toISOString()});
 audit(d,a,'administrative_correction',id,before,s,reason.trim()+(note.trim()?' — '+note.trim():''));
 for(const w of new Set([before.start_time,p.start_time].map(t=>weekOf(dateKey(t,d.settings.timezone),d.settings.weekStartsOn)))){
  const submission=d.submissions.find(x=>x.employee_id===s.employee_id&&x.week===w);
  if(submission&&submission.status!=='submitted'){const old=structuredClone(submission);submission.status='submitted';delete submission.reviewed_at;delete submission.reviewed_by_user_id;audit(d,a,'week_reopened',submission.id,old,submission,reason);}
 }
}
export function saveTeam(d:TimeData,a:Actor,input:Omit<Team,'company_id'>){
 authorize(d,a,true);
 if(!input.name.trim())throw Error('Le nom est obligatoire.');
 const members=[...new Set(input.member_ids)];
 if(!members.length||members.some(id=>!d.employees.some(e=>e.id===id&&e.company_id===a.companyId)))throw Error('Choisissez des membres de la compagnie.');
 if(input.lead_id&&(!members.includes(input.lead_id)||!d.employees.some(e=>e.id===input.lead_id&&e.role==='Chef')))throw Error('Le chef doit faire partie de l’équipe et avoir le rôle Chef.');
 if(input.job_id&&!d.jobs.some(j=>j.id===input.job_id&&j.company_id===a.companyId))throw Error('Job inaccessible.');
 const teams=d.teams??=[];const existing=teams.find(t=>t.id===input.id);
 if(existing&&existing.company_id!==a.companyId)throw Error('Équipe inaccessible.');
 const before=existing?structuredClone(existing):null;
 const value={...input,name:input.name.trim(),company_id:a.companyId,member_ids:members};
 if(existing)Object.assign(existing,value);else teams.push(value);
 if(input.job_id){const job=d.jobs.find(j=>j.id===input.job_id)!;const old=structuredClone(job);job.members=[...new Set([...job.members,...members.map(id=>d.employees.find(e=>e.id===id)!.user_id).filter(Boolean)])];audit(d,a,'job_members_assigned',job.id,old,job);}
 audit(d,a,'team_saved',input.id,before,value);
}
export function createDemoEmployee(d:TimeData,a:Actor,input:{name:string;phone:string;role:'Chef'|'Employé'}){
 authorize(d,a,true);if(!input.name.trim())throw Error('Le nom est obligatoire.');
 const e={id:crypto.randomUUID(),company_id:a.companyId,user_id:'',name:input.name.trim(),phone:input.phone.trim(),role:input.role,status:'active' as const};
 d.employees.push(e);audit(d,a,'employee_created',e.id,null,e);return e.id;
}
