export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS companies (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, company_id TEXT NOT NULL, email TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('boss','adjointe','chef','employe')), active INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(company_id) REFERENCES companies(id))`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_users_company_email ON users(company_id, email)`,
  `CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, company_id TEXT NOT NULL, job_number TEXT NOT NULL, name TEXT NOT NULL, address TEXT, status TEXT NOT NULL, estimated_hours REAL, temporary INTEGER NOT NULL DEFAULT 0, created_by TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(company_id) REFERENCES companies(id))`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_jobs_company_number ON jobs(company_id, job_number)`,
  `CREATE TABLE IF NOT EXISTS job_members (job_id TEXT NOT NULL, user_id TEXT NOT NULL, is_lead INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(job_id,user_id), FOREIGN KEY(job_id) REFERENCES jobs(id), FOREIGN KEY(user_id) REFERENCES users(id))`,
  `CREATE INDEX IF NOT EXISTS idx_job_members_user ON job_members(user_id)`,
  `CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, company_id TEXT NOT NULL, job_id TEXT NOT NULL, requested_by TEXT NOT NULL, category TEXT NOT NULL, priority TEXT NOT NULL, status TEXT NOT NULL, notes TEXT, created_at TEXT NOT NULL, handled_by TEXT, FOREIGN KEY(job_id) REFERENCES jobs(id))`,
  `CREATE INDEX IF NOT EXISTS idx_orders_job_status ON orders(job_id,status)`,
  `CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL, name TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT NOT NULL, supplier_id TEXT, FOREIGN KEY(order_id) REFERENCES orders(id))`,
  `CREATE TABLE IF NOT EXISTS attachments (id TEXT PRIMARY KEY, company_id TEXT NOT NULL, owner_type TEXT NOT NULL, owner_id TEXT NOT NULL, r2_key TEXT NOT NULL, filename TEXT NOT NULL, content_type TEXT NOT NULL, uploaded_by TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_attachments_owner ON attachments(owner_type,owner_id)`,
  `CREATE TABLE IF NOT EXISTS suppliers (id TEXT PRIMARY KEY, company_id TEXT NOT NULL, name TEXT NOT NULL, order_email TEXT, phone TEXT, representative TEXT, notes TEXT)`,
  `CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, company_id TEXT NOT NULL, job_id TEXT, chef_user_id TEXT, created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS conversation_members (conversation_id TEXT NOT NULL, user_id TEXT NOT NULL, PRIMARY KEY(conversation_id,user_id))`,
  `CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, sender_id TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_messages_conversation_time ON messages(conversation_id,created_at)`,
  `CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY, company_id TEXT NOT NULL, actor_id TEXT NOT NULL, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, detail_json TEXT, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_company_time ON audit_log(company_id,created_at)`
] as const;
